// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyAgentRSSAdjudicationEntry = `-- name: ApplyAgentRSSAdjudicationEntry :one
WITH decision AS (
    UPDATE rss_entry_adjudications AS adjudication
    SET state = $1,
        source = $5,
        resolution_id = $6,
        related_entry_id = $7,
        updated_at = now()
    WHERE adjudication.entry_id = $8
      AND adjudication.batch_id = $9
      AND adjudication.state = 'pending'
    RETURNING adjudication.entry_id
)
UPDATE rss_entries AS entry
SET source_season = CASE WHEN $1::text = 'selected' THEN $2 ELSE entry.source_season END,
    source_episode = CASE WHEN $1::text = 'selected' THEN $3 ELSE entry.source_episode END,
    downloadable = $1::text = 'selected',
    rejection_reasons = CASE
        WHEN $1::text = 'selected' THEN ARRAY[]::text[]
        ELSE $4::text[]
    END,
    coordinate_source = CASE WHEN $1::text = 'selected' THEN $5 ELSE entry.coordinate_source END,
    agent_resolution_id = CASE WHEN $1::text = 'selected' THEN $6 ELSE entry.agent_resolution_id END,
    last_error_code = NULL,
    last_error_message = NULL,
    last_error_retryable = false,
    updated_at = now()
FROM decision
WHERE entry.id = decision.entry_id
  AND entry.status IN ('discovered', 'enqueue_failed')
RETURNING entry.id, entry.subscription_id, entry.release_candidate_id, entry.identity_key, entry.guid, entry.btih, entry.canonical_url, entry.title, entry.published_at, entry.status, entry.enqueue_attempts, entry.last_error_code, entry.last_error_message, entry.upstream_payload, entry.discovered_at, entry.enqueued_at, entry.updated_at, entry.download_uri, entry.downloadable, entry.rejection_reasons, entry.source_season, entry.source_episode, entry.duplicate_count, entry.last_error_retryable, entry.imported_at, entry.coordinate_source, entry.agent_resolution_id, entry.fulfillment_source
`

type ApplyAgentRSSAdjudicationEntryParams struct {
	AdjudicationState        string      `db:"adjudication_state" json:"adjudication_state"`
	SourceSeason             *int32      `db:"source_season" json:"source_season"`
	SourceEpisode            *int32      `db:"source_episode" json:"source_episode"`
	RejectionReasons         []string    `db:"rejection_reasons" json:"rejection_reasons"`
	AdjudicationSource       *string     `db:"adjudication_source" json:"adjudication_source"`
	AdjudicationResolutionID pgtype.UUID `db:"adjudication_resolution_id" json:"adjudication_resolution_id"`
	RelatedEntryID           pgtype.UUID `db:"related_entry_id" json:"related_entry_id"`
	ID                       pgtype.UUID `db:"id" json:"id"`
	AdjudicationBatchID      pgtype.UUID `db:"adjudication_batch_id" json:"adjudication_batch_id"`
}

func (q *Queries) ApplyAgentRSSAdjudicationEntry(ctx context.Context, arg ApplyAgentRSSAdjudicationEntryParams) (RssEntry, error) {
	row := q.db.QueryRow(ctx, applyAgentRSSAdjudicationEntry,
		arg.AdjudicationState,
		arg.SourceSeason,
		arg.SourceEpisode,
		arg.RejectionReasons,
		arg.AdjudicationSource,
		arg.AdjudicationResolutionID,
		arg.RelatedEntryID,
		arg.ID,
		arg.AdjudicationBatchID,
	)
	var i RssEntry
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ReleaseCandidateID,
		&i.IdentityKey,
		&i.Guid,
		&i.Btih,
		&i.CanonicalUrl,
		&i.Title,
		&i.PublishedAt,
		&i.Status,
		&i.EnqueueAttempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.UpstreamPayload,
		&i.DiscoveredAt,
		&i.EnqueuedAt,
		&i.UpdatedAt,
		&i.DownloadUri,
		&i.Downloadable,
		&i.RejectionReasons,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.DuplicateCount,
		&i.LastErrorRetryable,
		&i.ImportedAt,
		&i.CoordinateSource,
		&i.AgentResolutionID,
		&i.FulfillmentSource,
	)
	return i, err
}

const applyAgentRSSCoordinate = `-- name: ApplyAgentRSSCoordinate :one
UPDATE rss_entries
SET source_season = $1,
    source_episode = $2,
    downloadable = true,
    rejection_reasons = ARRAY[]::text[],
    coordinate_source = $3,
    agent_resolution_id = $4,
    last_error_code = NULL,
    last_error_message = NULL,
    last_error_retryable = false,
    updated_at = now()
WHERE id = $5
RETURNING id, subscription_id, release_candidate_id, identity_key, guid, btih, canonical_url, title, published_at, status, enqueue_attempts, last_error_code, last_error_message, upstream_payload, discovered_at, enqueued_at, updated_at, download_uri, downloadable, rejection_reasons, source_season, source_episode, duplicate_count, last_error_retryable, imported_at, coordinate_source, agent_resolution_id, fulfillment_source
`

type ApplyAgentRSSCoordinateParams struct {
	SourceSeason      *int32      `db:"source_season" json:"source_season"`
	SourceEpisode     *int32      `db:"source_episode" json:"source_episode"`
	CoordinateSource  *string     `db:"coordinate_source" json:"coordinate_source"`
	AgentResolutionID pgtype.UUID `db:"agent_resolution_id" json:"agent_resolution_id"`
	ID                pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ApplyAgentRSSCoordinate(ctx context.Context, arg ApplyAgentRSSCoordinateParams) (RssEntry, error) {
	row := q.db.QueryRow(ctx, applyAgentRSSCoordinate,
		arg.SourceSeason,
		arg.SourceEpisode,
		arg.CoordinateSource,
		arg.AgentResolutionID,
		arg.ID,
	)
	var i RssEntry
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ReleaseCandidateID,
		&i.IdentityKey,
		&i.Guid,
		&i.Btih,
		&i.CanonicalUrl,
		&i.Title,
		&i.PublishedAt,
		&i.Status,
		&i.EnqueueAttempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.UpstreamPayload,
		&i.DiscoveredAt,
		&i.EnqueuedAt,
		&i.UpdatedAt,
		&i.DownloadUri,
		&i.Downloadable,
		&i.RejectionReasons,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.DuplicateCount,
		&i.LastErrorRetryable,
		&i.ImportedAt,
		&i.CoordinateSource,
		&i.AgentResolutionID,
		&i.FulfillmentSource,
	)
	return i, err
}

const completeAgentResolution = `-- name: CompleteAgentResolution :one
UPDATE agent_resolutions
SET status = $1,
    validation = $2,
    completed_at = now(),
    applied_at = CASE WHEN $1::text = 'applied' THEN now() ELSE NULL END,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND status IN ('running', 'proposed', 'review_required')
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

type CompleteAgentResolutionParams struct {
	Status     string      `db:"status" json:"status"`
	Validation []byte      `db:"validation" json:"validation"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) CompleteAgentResolution(ctx context.Context, arg CompleteAgentResolutionParams) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, completeAgentResolution, arg.Status, arg.Validation, arg.ID)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeRSSAdjudicationBatch = `-- name: CompleteRSSAdjudicationBatch :one
UPDATE rss_adjudication_batches
SET status = 'applied',
    updated_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, subscription_id, status, entry_count, created_at, updated_at
`

func (q *Queries) CompleteRSSAdjudicationBatch(ctx context.Context, id pgtype.UUID) (RssAdjudicationBatch, error) {
	row := q.db.QueryRow(ctx, completeRSSAdjudicationBatch, id)
	var i RssAdjudicationBatch
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.Status,
		&i.EntryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentResolution = `-- name: CreateAgentResolution :one
INSERT INTO agent_resolutions (
    id,
    operation_id,
    resource_version,
    capability,
    resource_type,
    resource_id,
    trigger,
    input_fingerprint,
    configuration_version,
    protocol,
    provider_origin,
    model,
    prompt_version,
    toolset_version,
    created_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
ON CONFLICT (id) DO UPDATE
SET id = agent_resolutions.id
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

type CreateAgentResolutionParams struct {
	ID                   pgtype.UUID `db:"id" json:"id"`
	OperationID          pgtype.UUID `db:"operation_id" json:"operation_id"`
	ResourceVersion      *int32      `db:"resource_version" json:"resource_version"`
	Capability           string      `db:"capability" json:"capability"`
	ResourceType         string      `db:"resource_type" json:"resource_type"`
	ResourceID           pgtype.UUID `db:"resource_id" json:"resource_id"`
	Trigger              string      `db:"trigger" json:"trigger"`
	InputFingerprint     []byte      `db:"input_fingerprint" json:"input_fingerprint"`
	ConfigurationVersion int32       `db:"configuration_version" json:"configuration_version"`
	Protocol             string      `db:"protocol" json:"protocol"`
	ProviderOrigin       string      `db:"provider_origin" json:"provider_origin"`
	Model                string      `db:"model" json:"model"`
	PromptVersion        string      `db:"prompt_version" json:"prompt_version"`
	ToolsetVersion       string      `db:"toolset_version" json:"toolset_version"`
	CreatedBy            pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateAgentResolution(ctx context.Context, arg CreateAgentResolutionParams) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, createAgentResolution,
		arg.ID,
		arg.OperationID,
		arg.ResourceVersion,
		arg.Capability,
		arg.ResourceType,
		arg.ResourceID,
		arg.Trigger,
		arg.InputFingerprint,
		arg.ConfigurationVersion,
		arg.Protocol,
		arg.ProviderOrigin,
		arg.Model,
		arg.PromptVersion,
		arg.ToolsetVersion,
		arg.CreatedBy,
	)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentResolutionStep = `-- name: CreateAgentResolutionStep :one
INSERT INTO agent_resolution_steps (
    id,
    resolution_id,
    sequence,
    tool_name,
    status,
    arguments_digest,
    result_digest,
    duration_milliseconds,
    error_code
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
ON CONFLICT (resolution_id, sequence) DO UPDATE
SET tool_name = EXCLUDED.tool_name,
    status = EXCLUDED.status,
    arguments_digest = EXCLUDED.arguments_digest,
    result_digest = EXCLUDED.result_digest,
    duration_milliseconds = EXCLUDED.duration_milliseconds,
    error_code = EXCLUDED.error_code
RETURNING id, resolution_id, sequence, tool_name, status, arguments_digest, result_digest, duration_milliseconds, error_code, created_at
`

type CreateAgentResolutionStepParams struct {
	ID                   pgtype.UUID `db:"id" json:"id"`
	ResolutionID         pgtype.UUID `db:"resolution_id" json:"resolution_id"`
	Sequence             int32       `db:"sequence" json:"sequence"`
	ToolName             string      `db:"tool_name" json:"tool_name"`
	Status               string      `db:"status" json:"status"`
	ArgumentsDigest      []byte      `db:"arguments_digest" json:"arguments_digest"`
	ResultDigest         []byte      `db:"result_digest" json:"result_digest"`
	DurationMilliseconds *int64      `db:"duration_milliseconds" json:"duration_milliseconds"`
	ErrorCode            *string     `db:"error_code" json:"error_code"`
}

func (q *Queries) CreateAgentResolutionStep(ctx context.Context, arg CreateAgentResolutionStepParams) (AgentResolutionStep, error) {
	row := q.db.QueryRow(ctx, createAgentResolutionStep,
		arg.ID,
		arg.ResolutionID,
		arg.Sequence,
		arg.ToolName,
		arg.Status,
		arg.ArgumentsDigest,
		arg.ResultDigest,
		arg.DurationMilliseconds,
		arg.ErrorCode,
	)
	var i AgentResolutionStep
	err := row.Scan(
		&i.ID,
		&i.ResolutionID,
		&i.Sequence,
		&i.ToolName,
		&i.Status,
		&i.ArgumentsDigest,
		&i.ResultDigest,
		&i.DurationMilliseconds,
		&i.ErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const createRSSFeedCatalogLookup = `-- name: CreateRSSFeedCatalogLookup :one
WITH expired AS (
    DELETE FROM rss_feed_catalog_lookups
    WHERE expires_at <= now()
)
INSERT INTO rss_feed_catalog_lookups (
    id,
    feed_title,
    suggested_queries,
    sample_titles,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, feed_title, suggested_queries, sample_titles, created_at, expires_at
`

type CreateRSSFeedCatalogLookupParams struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	FeedTitle        string             `db:"feed_title" json:"feed_title"`
	SuggestedQueries []string           `db:"suggested_queries" json:"suggested_queries"`
	SampleTitles     []string           `db:"sample_titles" json:"sample_titles"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateRSSFeedCatalogLookup(ctx context.Context, arg CreateRSSFeedCatalogLookupParams) (RssFeedCatalogLookup, error) {
	row := q.db.QueryRow(ctx, createRSSFeedCatalogLookup,
		arg.ID,
		arg.FeedTitle,
		arg.SuggestedQueries,
		arg.SampleTitles,
		arg.ExpiresAt,
	)
	var i RssFeedCatalogLookup
	err := row.Scan(
		&i.ID,
		&i.FeedTitle,
		&i.SuggestedQueries,
		&i.SampleTitles,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const failAgentResolution = `-- name: FailAgentResolution :one
UPDATE agent_resolutions
SET status = $1,
    error_code = $2,
    error_message = $3,
    completed_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $4
  AND status IN ('queued', 'running', 'proposed')
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

type FailAgentResolutionParams struct {
	Status       string      `db:"status" json:"status"`
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) FailAgentResolution(ctx context.Context, arg FailAgentResolutionParams) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, failAgentResolution,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failValidatedAgentResolution = `-- name: FailValidatedAgentResolution :one
UPDATE agent_resolutions
SET status = 'failed',
    validation = $1,
    error_code = $2,
    error_message = $3,
    completed_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $4
  AND status IN ('running', 'proposed')
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

type FailValidatedAgentResolutionParams struct {
	Validation   []byte      `db:"validation" json:"validation"`
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) FailValidatedAgentResolution(ctx context.Context, arg FailValidatedAgentResolutionParams) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, failValidatedAgentResolution,
		arg.Validation,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentCatalogContext = `-- name: GetAgentCatalogContext :one
SELECT
    acquisition.id,
    acquisition.updated_at,
    acquisition.source_kind,
    series.title AS current_title,
    COALESCE(candidate.title, entry.title, series.title)::text AS source_title
FROM acquisitions AS acquisition
JOIN media_series AS series ON series.id = acquisition.series_id
LEFT JOIN release_candidates AS candidate ON candidate.id = acquisition.release_candidate_id
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
WHERE acquisition.id = $1
`

type GetAgentCatalogContextRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SourceKind   string             `db:"source_kind" json:"source_kind"`
	CurrentTitle string             `db:"current_title" json:"current_title"`
	SourceTitle  string             `db:"source_title" json:"source_title"`
}

func (q *Queries) GetAgentCatalogContext(ctx context.Context, id pgtype.UUID) (GetAgentCatalogContextRow, error) {
	row := q.db.QueryRow(ctx, getAgentCatalogContext, id)
	var i GetAgentCatalogContextRow
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.CurrentTitle,
		&i.SourceTitle,
	)
	return i, err
}

const getAgentDownloadContext = `-- name: GetAgentDownloadContext :one
SELECT
    download.id,
    download.acquisition_id,
    download.version,
    download.status,
    download.failure_stage,
    download.file_resolution_source,
    download.updated_at,
    acquisition.source_kind,
    COALESCE(entry.source_season, 1)::integer AS default_source_season,
    entry.source_episode AS default_source_episode
FROM downloads AS download
JOIN acquisitions AS acquisition ON acquisition.id = download.acquisition_id
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
WHERE download.id = $1
  AND download.deleted_at IS NULL
`

type GetAgentDownloadContextRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	AcquisitionID        pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	Version              int32              `db:"version" json:"version"`
	Status               string             `db:"status" json:"status"`
	FailureStage         *string            `db:"failure_stage" json:"failure_stage"`
	FileResolutionSource *string            `db:"file_resolution_source" json:"file_resolution_source"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SourceKind           string             `db:"source_kind" json:"source_kind"`
	DefaultSourceSeason  int32              `db:"default_source_season" json:"default_source_season"`
	DefaultSourceEpisode *int32             `db:"default_source_episode" json:"default_source_episode"`
}

func (q *Queries) GetAgentDownloadContext(ctx context.Context, id pgtype.UUID) (GetAgentDownloadContextRow, error) {
	row := q.db.QueryRow(ctx, getAgentDownloadContext, id)
	var i GetAgentDownloadContextRow
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Version,
		&i.Status,
		&i.FailureStage,
		&i.FileResolutionSource,
		&i.UpdatedAt,
		&i.SourceKind,
		&i.DefaultSourceSeason,
		&i.DefaultSourceEpisode,
	)
	return i, err
}

const getAgentMappingContext = `-- name: GetAgentMappingContext :one
SELECT
    acquisition.id,
    acquisition.series_id,
    acquisition.mapping_profile_id,
    acquisition.updated_at,
    series.title,
    series.tmdb_series_id
FROM acquisitions AS acquisition
JOIN media_series AS series ON series.id = acquisition.series_id
WHERE acquisition.id = $1
`

type GetAgentMappingContextRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	SeriesID         pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Title            string             `db:"title" json:"title"`
	TmdbSeriesID     *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
}

func (q *Queries) GetAgentMappingContext(ctx context.Context, id pgtype.UUID) (GetAgentMappingContextRow, error) {
	row := q.db.QueryRow(ctx, getAgentMappingContext, id)
	var i GetAgentMappingContextRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.UpdatedAt,
		&i.Title,
		&i.TmdbSeriesID,
	)
	return i, err
}

const getAgentRSSAdjudicationBatch = `-- name: GetAgentRSSAdjudicationBatch :one
SELECT
    batch.id, batch.subscription_id, batch.status, batch.entry_count, batch.created_at, batch.updated_at,
    subscription.source_season AS default_source_season,
    subscription.include_keywords,
    subscription.exclude_keywords,
    subscription.enabled AS subscription_enabled,
    subscription.completed_at AS subscription_completed_at,
    subscription.deleted_at AS subscription_deleted_at,
    subscription.series_id,
    subscription.mapping_profile_id
FROM rss_adjudication_batches AS batch
JOIN rss_subscriptions AS subscription ON subscription.id = batch.subscription_id
WHERE batch.id = $1
`

type GetAgentRSSAdjudicationBatchRow struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID          pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	Status                  string             `db:"status" json:"status"`
	EntryCount              int32              `db:"entry_count" json:"entry_count"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DefaultSourceSeason     int32              `db:"default_source_season" json:"default_source_season"`
	IncludeKeywords         []string           `db:"include_keywords" json:"include_keywords"`
	ExcludeKeywords         []string           `db:"exclude_keywords" json:"exclude_keywords"`
	SubscriptionEnabled     bool               `db:"subscription_enabled" json:"subscription_enabled"`
	SubscriptionCompletedAt pgtype.Timestamptz `db:"subscription_completed_at" json:"subscription_completed_at"`
	SubscriptionDeletedAt   pgtype.Timestamptz `db:"subscription_deleted_at" json:"subscription_deleted_at"`
	SeriesID                pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID        pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
}

func (q *Queries) GetAgentRSSAdjudicationBatch(ctx context.Context, id pgtype.UUID) (GetAgentRSSAdjudicationBatchRow, error) {
	row := q.db.QueryRow(ctx, getAgentRSSAdjudicationBatch, id)
	var i GetAgentRSSAdjudicationBatchRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.Status,
		&i.EntryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultSourceSeason,
		&i.IncludeKeywords,
		&i.ExcludeKeywords,
		&i.SubscriptionEnabled,
		&i.SubscriptionCompletedAt,
		&i.SubscriptionDeletedAt,
		&i.SeriesID,
		&i.MappingProfileID,
	)
	return i, err
}

const getAgentRSSContext = `-- name: GetAgentRSSContext :one
SELECT
    entry.id,
    entry.subscription_id,
    entry.title,
    (entry.download_uri IS NOT NULL)::boolean AS has_download_uri,
    entry.rejection_reasons,
    entry.source_season,
    entry.source_episode,
    entry.discovered_at,
    entry.updated_at,
    subscription.source_season AS default_source_season,
    subscription.include_keywords,
    subscription.exclude_keywords,
    subscription.enabled,
    subscription.mapping_profile_id,
    subscription.version AS subscription_version,
    subscription.completed_at
FROM rss_entries AS entry
JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
WHERE entry.id = $1
`

type GetAgentRSSContextRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID      pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	Title               string             `db:"title" json:"title"`
	HasDownloadUri      bool               `db:"has_download_uri" json:"has_download_uri"`
	RejectionReasons    []string           `db:"rejection_reasons" json:"rejection_reasons"`
	SourceSeason        *int32             `db:"source_season" json:"source_season"`
	SourceEpisode       *int32             `db:"source_episode" json:"source_episode"`
	DiscoveredAt        pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DefaultSourceSeason int32              `db:"default_source_season" json:"default_source_season"`
	IncludeKeywords     []string           `db:"include_keywords" json:"include_keywords"`
	ExcludeKeywords     []string           `db:"exclude_keywords" json:"exclude_keywords"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	MappingProfileID    pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	SubscriptionVersion int32              `db:"subscription_version" json:"subscription_version"`
	CompletedAt         pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) GetAgentRSSContext(ctx context.Context, id pgtype.UUID) (GetAgentRSSContextRow, error) {
	row := q.db.QueryRow(ctx, getAgentRSSContext, id)
	var i GetAgentRSSContextRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.Title,
		&i.HasDownloadUri,
		&i.RejectionReasons,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.DiscoveredAt,
		&i.UpdatedAt,
		&i.DefaultSourceSeason,
		&i.IncludeKeywords,
		&i.ExcludeKeywords,
		&i.Enabled,
		&i.MappingProfileID,
		&i.SubscriptionVersion,
		&i.CompletedAt,
	)
	return i, err
}

const getAgentRSSFeedCatalogLookup = `-- name: GetAgentRSSFeedCatalogLookup :one
SELECT id, feed_title, suggested_queries, sample_titles, created_at, expires_at
FROM rss_feed_catalog_lookups
WHERE id = $1
  AND expires_at > now()
`

func (q *Queries) GetAgentRSSFeedCatalogLookup(ctx context.Context, id pgtype.UUID) (RssFeedCatalogLookup, error) {
	row := q.db.QueryRow(ctx, getAgentRSSFeedCatalogLookup, id)
	var i RssFeedCatalogLookup
	err := row.Scan(
		&i.ID,
		&i.FeedTitle,
		&i.SuggestedQueries,
		&i.SampleTitles,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getAgentRSSPreacquisitionMappingContext = `-- name: GetAgentRSSPreacquisitionMappingContext :one
SELECT
    scope.id,
    scope.subscription_id,
    scope.subscription_version,
    scope.source_fingerprint,
    scope.status,
    subscription.series_id,
    subscription.mapping_profile_id,
    subscription.enabled AS subscription_enabled,
    subscription.auto_episode_mapping,
    subscription.deleted_at AS subscription_deleted_at,
    subscription.completed_at AS subscription_completed_at,
    series.tmdb_series_id,
    series.title AS series_title
FROM rss_preacquisition_mapping_scopes AS scope
JOIN rss_subscriptions AS subscription ON subscription.id = scope.subscription_id
JOIN media_series AS series ON series.id = subscription.series_id
WHERE scope.id = $1
`

type GetAgentRSSPreacquisitionMappingContextRow struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID          pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	SubscriptionVersion     int32              `db:"subscription_version" json:"subscription_version"`
	SourceFingerprint       []byte             `db:"source_fingerprint" json:"source_fingerprint"`
	Status                  string             `db:"status" json:"status"`
	SeriesID                pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID        pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	SubscriptionEnabled     bool               `db:"subscription_enabled" json:"subscription_enabled"`
	AutoEpisodeMapping      bool               `db:"auto_episode_mapping" json:"auto_episode_mapping"`
	SubscriptionDeletedAt   pgtype.Timestamptz `db:"subscription_deleted_at" json:"subscription_deleted_at"`
	SubscriptionCompletedAt pgtype.Timestamptz `db:"subscription_completed_at" json:"subscription_completed_at"`
	TmdbSeriesID            *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
	SeriesTitle             string             `db:"series_title" json:"series_title"`
}

func (q *Queries) GetAgentRSSPreacquisitionMappingContext(ctx context.Context, id pgtype.UUID) (GetAgentRSSPreacquisitionMappingContextRow, error) {
	row := q.db.QueryRow(ctx, getAgentRSSPreacquisitionMappingContext, id)
	var i GetAgentRSSPreacquisitionMappingContextRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.SubscriptionVersion,
		&i.SourceFingerprint,
		&i.Status,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.SubscriptionEnabled,
		&i.AutoEpisodeMapping,
		&i.SubscriptionDeletedAt,
		&i.SubscriptionCompletedAt,
		&i.TmdbSeriesID,
		&i.SeriesTitle,
	)
	return i, err
}

const getAgentResolution = `-- name: GetAgentResolution :one
SELECT id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
FROM agent_resolutions
WHERE id = $1
`

func (q *Queries) GetAgentResolution(ctx context.Context, id pgtype.UUID) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, getAgentResolution, id)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentResolutionByOperation = `-- name: GetAgentResolutionByOperation :one
SELECT id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
FROM agent_resolutions
WHERE operation_id = $1
`

func (q *Queries) GetAgentResolutionByOperation(ctx context.Context, operationID pgtype.UUID) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, getAgentResolutionByOperation, operationID)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentResolutionDashboardStats = `-- name: GetAgentResolutionDashboardStats :one
SELECT
    count(*)::bigint AS total,
    count(*) FILTER (WHERE status = 'review_required')::bigint AS review_pending,
    count(*) FILTER (WHERE status = 'applied')::bigint AS applied,
    count(*) FILTER (WHERE status = 'applied' AND review_decision IS NULL)::bigint AS auto_applied,
    count(*) FILTER (WHERE status = 'applied' AND review_decision = 'accepted')::bigint AS accepted,
    count(*) FILTER (WHERE status = 'rejected')::bigint AS rejected,
    count(*) FILTER (WHERE status = 'failed')::bigint AS failed,
    COALESCE(sum(input_tokens), 0)::bigint AS input_tokens,
    COALESCE(sum(output_tokens), 0)::bigint AS output_tokens,
    COALESCE(avg(latency_milliseconds), 0)::bigint AS average_latency_milliseconds
FROM agent_resolutions
`

type GetAgentResolutionDashboardStatsRow struct {
	Total                      int64 `db:"total" json:"total"`
	ReviewPending              int64 `db:"review_pending" json:"review_pending"`
	Applied                    int64 `db:"applied" json:"applied"`
	AutoApplied                int64 `db:"auto_applied" json:"auto_applied"`
	Accepted                   int64 `db:"accepted" json:"accepted"`
	Rejected                   int64 `db:"rejected" json:"rejected"`
	Failed                     int64 `db:"failed" json:"failed"`
	InputTokens                int64 `db:"input_tokens" json:"input_tokens"`
	OutputTokens               int64 `db:"output_tokens" json:"output_tokens"`
	AverageLatencyMilliseconds int64 `db:"average_latency_milliseconds" json:"average_latency_milliseconds"`
}

func (q *Queries) GetAgentResolutionDashboardStats(ctx context.Context) (GetAgentResolutionDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAgentResolutionDashboardStats)
	var i GetAgentResolutionDashboardStatsRow
	err := row.Scan(
		&i.Total,
		&i.ReviewPending,
		&i.Applied,
		&i.AutoApplied,
		&i.Accepted,
		&i.Rejected,
		&i.Failed,
		&i.InputTokens,
		&i.OutputTokens,
		&i.AverageLatencyMilliseconds,
	)
	return i, err
}

const isAutomaticEpisodeMappingEnabled = `-- name: IsAutomaticEpisodeMappingEnabled :one
SELECT CASE
    WHEN acquisition.source_kind <> 'rss' THEN true
    ELSE COALESCE(subscription.auto_episode_mapping AND subscription.deleted_at IS NULL, false)
END::boolean AS enabled
FROM acquisitions AS acquisition
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
LEFT JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
WHERE acquisition.id = $1
`

func (q *Queries) IsAutomaticEpisodeMappingEnabled(ctx context.Context, acquisitionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAutomaticEpisodeMappingEnabled, acquisitionID)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const isCanonicalRSSAgentMappingAcquisition = `-- name: IsCanonicalRSSAgentMappingAcquisition :one
WITH source AS (
    SELECT acquisition.id, entry.subscription_id
    FROM acquisitions AS acquisition
    LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
    WHERE acquisition.id = $1
)
SELECT COALESCE(
    source.subscription_id IS NULL
    OR source.id = (
        SELECT candidate.id
        FROM acquisitions AS candidate
        JOIN rss_entries AS candidate_entry ON candidate_entry.id = candidate.rss_entry_id
        WHERE candidate_entry.subscription_id = source.subscription_id
          AND candidate.mapping_profile_id IS NULL
          AND candidate.deletion_requested_at IS NULL
          AND EXISTS (
              SELECT 1
              FROM downloads AS download
              JOIN download_files AS file ON file.download_id = download.id
              WHERE download.acquisition_id = candidate.id
                AND download.deleted_at IS NULL
                AND file.selected
                AND file.media_kind = 'video'
          )
        ORDER BY candidate.created_at, candidate.id
        LIMIT 1
    ),
    false
)::boolean AS canonical
FROM source
`

func (q *Queries) IsCanonicalRSSAgentMappingAcquisition(ctx context.Context, acquisitionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isCanonicalRSSAgentMappingAcquisition, acquisitionID)
	var canonical bool
	err := row.Scan(&canonical)
	return canonical, err
}

const listAgentDownloadFiles = `-- name: ListAgentDownloadFiles :many
SELECT id, file_index, relative_path, size_bytes, media_kind, selected, source_season, source_episode, language
FROM download_files
WHERE download_id = $1
ORDER BY file_index
`

type ListAgentDownloadFilesRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	FileIndex     int32       `db:"file_index" json:"file_index"`
	RelativePath  string      `db:"relative_path" json:"relative_path"`
	SizeBytes     int64       `db:"size_bytes" json:"size_bytes"`
	MediaKind     string      `db:"media_kind" json:"media_kind"`
	Selected      bool        `db:"selected" json:"selected"`
	SourceSeason  *int32      `db:"source_season" json:"source_season"`
	SourceEpisode *int32      `db:"source_episode" json:"source_episode"`
	Language      *string     `db:"language" json:"language"`
}

func (q *Queries) ListAgentDownloadFiles(ctx context.Context, downloadID pgtype.UUID) ([]ListAgentDownloadFilesRow, error) {
	rows, err := q.db.Query(ctx, listAgentDownloadFiles, downloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentDownloadFilesRow{}
	for rows.Next() {
		var i ListAgentDownloadFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.FileIndex,
			&i.RelativePath,
			&i.SizeBytes,
			&i.MediaKind,
			&i.Selected,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMappingAcquisitionsByRSSSubscription = `-- name: ListAgentMappingAcquisitionsByRSSSubscription :many
SELECT acquisition.id
FROM acquisitions AS acquisition
JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
WHERE entry.subscription_id = $1
  AND subscription.auto_episode_mapping
  AND subscription.deleted_at IS NULL
  AND acquisition.mapping_profile_id IS NULL
  AND acquisition.deletion_requested_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM downloads AS download
      JOIN download_files AS file ON file.download_id = download.id
      WHERE download.acquisition_id = acquisition.id
        AND download.deleted_at IS NULL
        AND file.selected
        AND file.media_kind = 'video'
  )
ORDER BY acquisition.created_at, acquisition.id
LIMIT 1
`

func (q *Queries) ListAgentMappingAcquisitionsByRSSSubscription(ctx context.Context, subscriptionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentMappingAcquisitionsByRSSSubscription, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMappingAcquisitionsBySeries = `-- name: ListAgentMappingAcquisitionsBySeries :many
SELECT DISTINCT ON (COALESCE(entry.subscription_id, acquisition.id)) acquisition.id
FROM acquisitions AS acquisition
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
LEFT JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
WHERE acquisition.series_id = $1
  AND acquisition.mapping_profile_id IS NULL
  AND acquisition.deletion_requested_at IS NULL
  AND (
      entry.id IS NULL
      OR (
          subscription.auto_episode_mapping
          AND subscription.deleted_at IS NULL
      )
  )
  AND EXISTS (
      SELECT 1
      FROM downloads AS download
      JOIN download_files AS file ON file.download_id = download.id
      WHERE download.acquisition_id = acquisition.id
        AND download.deleted_at IS NULL
        AND file.selected
        AND file.media_kind = 'video'
  )
ORDER BY COALESCE(entry.subscription_id, acquisition.id), acquisition.created_at, acquisition.id
LIMIT 100
`

func (q *Queries) ListAgentMappingAcquisitionsBySeries(ctx context.Context, seriesID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentMappingAcquisitionsBySeries, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMappingFiles = `-- name: ListAgentMappingFiles :many
SELECT file.id, file.relative_path, file.source_season, file.source_episode
FROM download_files AS file
JOIN downloads AS download ON download.id = file.download_id
WHERE download.acquisition_id = $1
  AND download.deleted_at IS NULL
  AND file.selected
  AND file.media_kind = 'video'
  AND download.attempt = (
      SELECT max(candidate.attempt)
      FROM downloads AS candidate
      WHERE candidate.acquisition_id = $1
        AND candidate.deleted_at IS NULL
  )
ORDER BY file.file_index
`

type ListAgentMappingFilesRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	RelativePath  string      `db:"relative_path" json:"relative_path"`
	SourceSeason  *int32      `db:"source_season" json:"source_season"`
	SourceEpisode *int32      `db:"source_episode" json:"source_episode"`
}

func (q *Queries) ListAgentMappingFiles(ctx context.Context, acquisitionID pgtype.UUID) ([]ListAgentMappingFilesRow, error) {
	rows, err := q.db.Query(ctx, listAgentMappingFiles, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentMappingFilesRow{}
	for rows.Next() {
		var i ListAgentMappingFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.RelativePath,
			&i.SourceSeason,
			&i.SourceEpisode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRSSAdjudicationEntries = `-- name: ListAgentRSSAdjudicationEntries :many
SELECT
    entry.id,
    entry.title,
    entry.published_at,
    entry.status,
    entry.downloadable,
    entry.rejection_reasons,
    entry.source_season,
    entry.source_episode,
    entry.imported_at,
    entry.discovered_at,
    entry.updated_at
FROM rss_entries AS entry
JOIN rss_entry_adjudications AS adjudication ON adjudication.entry_id = entry.id
WHERE adjudication.batch_id = $1
ORDER BY entry.discovered_at, entry.id
`

type ListAgentRSSAdjudicationEntriesRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	Title            string             `db:"title" json:"title"`
	PublishedAt      pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Status           string             `db:"status" json:"status"`
	Downloadable     bool               `db:"downloadable" json:"downloadable"`
	RejectionReasons []string           `db:"rejection_reasons" json:"rejection_reasons"`
	SourceSeason     *int32             `db:"source_season" json:"source_season"`
	SourceEpisode    *int32             `db:"source_episode" json:"source_episode"`
	ImportedAt       pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	DiscoveredAt     pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAgentRSSAdjudicationEntries(ctx context.Context, batchID pgtype.UUID) ([]ListAgentRSSAdjudicationEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAgentRSSAdjudicationEntries, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentRSSAdjudicationEntriesRow{}
	for rows.Next() {
		var i ListAgentRSSAdjudicationEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PublishedAt,
			&i.Status,
			&i.Downloadable,
			&i.RejectionReasons,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.ImportedAt,
			&i.DiscoveredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRSSAdjudicationHistory = `-- name: ListAgentRSSAdjudicationHistory :many
SELECT
    entry.id,
    entry.title,
    entry.published_at,
    entry.status,
    COALESCE(adjudication.state, 'not_required')::text AS adjudication_state,
    entry.source_season,
    entry.source_episode,
    entry.imported_at,
    entry.discovered_at
FROM rss_entries AS entry
LEFT JOIN rss_entry_adjudications AS adjudication ON adjudication.entry_id = entry.id
WHERE entry.subscription_id = $1
  AND entry.discovered_at < $2
  AND (adjudication.batch_id IS NULL OR adjudication.batch_id <> $3)
ORDER BY entry.discovered_at DESC, entry.id DESC
LIMIT 50
`

type ListAgentRSSAdjudicationHistoryParams struct {
	SubscriptionID   pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	DiscoveredBefore pgtype.Timestamptz `db:"discovered_before" json:"discovered_before"`
	BatchID          pgtype.UUID        `db:"batch_id" json:"batch_id"`
}

type ListAgentRSSAdjudicationHistoryRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Title             string             `db:"title" json:"title"`
	PublishedAt       pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Status            string             `db:"status" json:"status"`
	AdjudicationState string             `db:"adjudication_state" json:"adjudication_state"`
	SourceSeason      *int32             `db:"source_season" json:"source_season"`
	SourceEpisode     *int32             `db:"source_episode" json:"source_episode"`
	ImportedAt        pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	DiscoveredAt      pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
}

func (q *Queries) ListAgentRSSAdjudicationHistory(ctx context.Context, arg ListAgentRSSAdjudicationHistoryParams) ([]ListAgentRSSAdjudicationHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAgentRSSAdjudicationHistory, arg.SubscriptionID, arg.DiscoveredBefore, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentRSSAdjudicationHistoryRow{}
	for rows.Next() {
		var i ListAgentRSSAdjudicationHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PublishedAt,
			&i.Status,
			&i.AdjudicationState,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.ImportedAt,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRSSNeighbors = `-- name: ListAgentRSSNeighbors :many
SELECT id, title, source_season, source_episode
FROM rss_entries
WHERE subscription_id = $1
  AND id <> $2
  AND source_season IS NOT NULL
  AND source_episode IS NOT NULL
ORDER BY abs(EXTRACT(EPOCH FROM (discovered_at - $3::timestamptz))), id
LIMIT 12
`

type ListAgentRSSNeighborsParams struct {
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	EntryID        pgtype.UUID        `db:"entry_id" json:"entry_id"`
	DiscoveredAt   pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
}

type ListAgentRSSNeighborsRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	Title         string      `db:"title" json:"title"`
	SourceSeason  *int32      `db:"source_season" json:"source_season"`
	SourceEpisode *int32      `db:"source_episode" json:"source_episode"`
}

func (q *Queries) ListAgentRSSNeighbors(ctx context.Context, arg ListAgentRSSNeighborsParams) ([]ListAgentRSSNeighborsRow, error) {
	rows, err := q.db.Query(ctx, listAgentRSSNeighbors, arg.SubscriptionID, arg.EntryID, arg.DiscoveredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentRSSNeighborsRow{}
	for rows.Next() {
		var i ListAgentRSSNeighborsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SourceSeason,
			&i.SourceEpisode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRSSPreacquisitionMappingSources = `-- name: ListAgentRSSPreacquisitionMappingSources :many
SELECT
    source.entry_id,
    source.source_season,
    source.source_episode,
    entry.title
FROM rss_preacquisition_mapping_sources AS source
JOIN rss_entries AS entry ON entry.id = source.entry_id
WHERE source.scope_id = $1
ORDER BY source.source_season, source.source_episode, source.entry_id
`

type ListAgentRSSPreacquisitionMappingSourcesRow struct {
	EntryID       pgtype.UUID `db:"entry_id" json:"entry_id"`
	SourceSeason  int32       `db:"source_season" json:"source_season"`
	SourceEpisode int32       `db:"source_episode" json:"source_episode"`
	Title         string      `db:"title" json:"title"`
}

func (q *Queries) ListAgentRSSPreacquisitionMappingSources(ctx context.Context, scopeID pgtype.UUID) ([]ListAgentRSSPreacquisitionMappingSourcesRow, error) {
	rows, err := q.db.Query(ctx, listAgentRSSPreacquisitionMappingSources, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentRSSPreacquisitionMappingSourcesRow{}
	for rows.Next() {
		var i ListAgentRSSPreacquisitionMappingSourcesRow
		if err := rows.Scan(
			&i.EntryID,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRSSPreacquisitionTMDbEpisodes = `-- name: ListAgentRSSPreacquisitionTMDbEpisodes :many
SELECT
    episode.id,
    season.season_number,
    episode.episode_number,
    episode.title
FROM rss_preacquisition_mapping_scopes AS scope
JOIN rss_subscriptions AS subscription ON subscription.id = scope.subscription_id
JOIN tmdb_seasons AS season ON season.series_id = subscription.series_id
JOIN media_episodes AS episode ON episode.season_id = season.id
WHERE scope.id = $1
  AND season.season_number > 0
  AND episode.episode_number > 0
ORDER BY season.season_number, episode.episode_number
`

type ListAgentRSSPreacquisitionTMDbEpisodesRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	SeasonNumber  int32       `db:"season_number" json:"season_number"`
	EpisodeNumber int32       `db:"episode_number" json:"episode_number"`
	Title         string      `db:"title" json:"title"`
}

func (q *Queries) ListAgentRSSPreacquisitionTMDbEpisodes(ctx context.Context, scopeID pgtype.UUID) ([]ListAgentRSSPreacquisitionTMDbEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listAgentRSSPreacquisitionTMDbEpisodes, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentRSSPreacquisitionTMDbEpisodesRow{}
	for rows.Next() {
		var i ListAgentRSSPreacquisitionTMDbEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentResolutionSteps = `-- name: ListAgentResolutionSteps :many
SELECT id, resolution_id, sequence, tool_name, status, arguments_digest, result_digest, duration_milliseconds, error_code, created_at
FROM agent_resolution_steps
WHERE resolution_id = $1
ORDER BY sequence
`

func (q *Queries) ListAgentResolutionSteps(ctx context.Context, resolutionID pgtype.UUID) ([]AgentResolutionStep, error) {
	rows, err := q.db.Query(ctx, listAgentResolutionSteps, resolutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentResolutionStep{}
	for rows.Next() {
		var i AgentResolutionStep
		if err := rows.Scan(
			&i.ID,
			&i.ResolutionID,
			&i.Sequence,
			&i.ToolName,
			&i.Status,
			&i.ArgumentsDigest,
			&i.ResultDigest,
			&i.DurationMilliseconds,
			&i.ErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentResolutions = `-- name: ListAgentResolutions :many
SELECT resolution.id, resolution.operation_id, resolution.version, resolution.capability, resolution.resource_type, resolution.resource_id, resolution.resource_version, resolution.trigger, resolution.status, resolution.input_fingerprint, resolution.configuration_version, resolution.protocol, resolution.provider_origin, resolution.model, resolution.prompt_version, resolution.toolset_version, resolution.proposal, resolution.validation, resolution.error_code, resolution.error_message, resolution.input_tokens, resolution.output_tokens, resolution.tool_call_count, resolution.latency_milliseconds, resolution.created_by, resolution.reviewed_by, resolution.review_decision, resolution.created_at, resolution.started_at, resolution.completed_at, resolution.reviewed_at, resolution.applied_at, resolution.updated_at
FROM agent_resolutions AS resolution
WHERE ($1::text IS NULL OR resolution.status = $1)
  AND ($2::text IS NULL OR resolution.capability = $2)
  AND ($3::text IS NULL OR resolution.resource_type = $3)
  AND ($4::uuid IS NULL OR resolution.resource_id = $4)
  AND (
      $5::uuid IS NULL
      OR (resolution.created_at, resolution.id) < (
          SELECT cursor.created_at, cursor.id
          FROM agent_resolutions AS cursor
          WHERE cursor.id = $5
      )
  )
ORDER BY resolution.created_at DESC, resolution.id DESC
LIMIT $6
`

type ListAgentResolutionsParams struct {
	Status       *string     `db:"status" json:"status"`
	Capability   *string     `db:"capability" json:"capability"`
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	CursorID     pgtype.UUID `db:"cursor_id" json:"cursor_id"`
	PageSize     int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListAgentResolutions(ctx context.Context, arg ListAgentResolutionsParams) ([]AgentResolution, error) {
	rows, err := q.db.Query(ctx, listAgentResolutions,
		arg.Status,
		arg.Capability,
		arg.ResourceType,
		arg.ResourceID,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentResolution{}
	for rows.Next() {
		var i AgentResolution
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Version,
			&i.Capability,
			&i.ResourceType,
			&i.ResourceID,
			&i.ResourceVersion,
			&i.Trigger,
			&i.Status,
			&i.InputFingerprint,
			&i.ConfigurationVersion,
			&i.Protocol,
			&i.ProviderOrigin,
			&i.Model,
			&i.PromptVersion,
			&i.ToolsetVersion,
			&i.Proposal,
			&i.Validation,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ToolCallCount,
			&i.LatencyMilliseconds,
			&i.CreatedBy,
			&i.ReviewedBy,
			&i.ReviewDecision,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ReviewedAt,
			&i.AppliedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentResolvableRSSEntries = `-- name: ListAgentResolvableRSSEntries :many
SELECT entry.id
FROM rss_entries AS entry
JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
WHERE entry.subscription_id = $1
  AND subscription.enabled
  AND subscription.deleted_at IS NULL
  AND subscription.completed_at IS NULL
  AND entry.status IN ('discovered', 'enqueue_failed')
  AND NOT EXISTS (
      SELECT 1 FROM rss_entry_adjudications AS adjudication
      WHERE adjudication.entry_id = entry.id
  )
  AND NOT entry.downloadable
  AND entry.download_uri IS NOT NULL
  AND cardinality(entry.rejection_reasons) > 0
  AND entry.rejection_reasons <@ ARRAY['episode_not_detected', 'episode_ambiguous']::text[]
ORDER BY entry.discovered_at, entry.id
LIMIT 100
`

func (q *Queries) ListAgentResolvableRSSEntries(ctx context.Context, subscriptionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAgentResolvableRSSEntries, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTMDbEpisodes = `-- name: ListAgentTMDbEpisodes :many
SELECT
    episode.id,
    season.season_number,
    episode.episode_number,
    episode.title
FROM acquisitions AS acquisition
JOIN tmdb_seasons AS season ON season.series_id = acquisition.series_id
JOIN media_episodes AS episode ON episode.season_id = season.id
WHERE acquisition.id = $1
  AND season.season_number > 0
ORDER BY season.season_number, episode.episode_number
`

type ListAgentTMDbEpisodesRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	SeasonNumber  int32       `db:"season_number" json:"season_number"`
	EpisodeNumber int32       `db:"episode_number" json:"episode_number"`
	Title         string      `db:"title" json:"title"`
}

func (q *Queries) ListAgentTMDbEpisodes(ctx context.Context, acquisitionID pgtype.UUID) ([]ListAgentTMDbEpisodesRow, error) {
	rows, err := q.db.Query(ctx, listAgentTMDbEpisodes, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAgentTMDbEpisodesRow{}
	for rows.Next() {
		var i ListAgentTMDbEpisodesRow
		if err := rows.Scan(
			&i.ID,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomaticRSSMappingAcquisitions = `-- name: ListAutomaticRSSMappingAcquisitions :many
SELECT DISTINCT ON (subscription.id) acquisition.id
FROM rss_subscriptions AS subscription
JOIN rss_entries AS entry ON entry.subscription_id = subscription.id
JOIN acquisitions AS acquisition ON acquisition.rss_entry_id = entry.id
WHERE subscription.auto_episode_mapping
  AND subscription.deleted_at IS NULL
  AND acquisition.mapping_profile_id IS NULL
  AND acquisition.deletion_requested_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM downloads AS download
      JOIN download_files AS file ON file.download_id = download.id
      WHERE download.acquisition_id = acquisition.id
        AND download.deleted_at IS NULL
        AND file.selected
        AND file.media_kind = 'video'
  )
ORDER BY subscription.id, acquisition.created_at, acquisition.id
LIMIT 100
`

func (q *Queries) ListAutomaticRSSMappingAcquisitions(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAutomaticRSSMappingAcquisitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentResolution = `-- name: LockAgentResolution :one
SELECT id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
FROM agent_resolutions
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAgentResolution(ctx context.Context, id pgtype.UUID) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, lockAgentResolution, id)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRSSAdjudicationBatch = `-- name: LockRSSAdjudicationBatch :one
SELECT id, subscription_id, status, entry_count, created_at, updated_at
FROM rss_adjudication_batches
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockRSSAdjudicationBatch(ctx context.Context, id pgtype.UUID) (RssAdjudicationBatch, error) {
	row := q.db.QueryRow(ctx, lockRSSAdjudicationBatch, id)
	var i RssAdjudicationBatch
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.Status,
		&i.EntryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockRSSAdjudicationEntries = `-- name: LockRSSAdjudicationEntries :many
SELECT
    entry.id, entry.subscription_id, entry.release_candidate_id, entry.identity_key, entry.guid, entry.btih, entry.canonical_url, entry.title, entry.published_at, entry.status, entry.enqueue_attempts, entry.last_error_code, entry.last_error_message, entry.upstream_payload, entry.discovered_at, entry.enqueued_at, entry.updated_at, entry.download_uri, entry.downloadable, entry.rejection_reasons, entry.source_season, entry.source_episode, entry.duplicate_count, entry.last_error_retryable, entry.imported_at, entry.coordinate_source, entry.agent_resolution_id, entry.fulfillment_source,
    adjudication.state AS adjudication_state,
    adjudication.source AS adjudication_source,
    adjudication.resolution_id AS adjudication_resolution_id,
    adjudication.related_entry_id
FROM rss_entries AS entry
JOIN rss_entry_adjudications AS adjudication ON adjudication.entry_id = entry.id
WHERE adjudication.batch_id = $1
ORDER BY entry.discovered_at, entry.id
FOR UPDATE OF entry, adjudication
`

type LockRSSAdjudicationEntriesRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID           pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	ReleaseCandidateID       pgtype.UUID        `db:"release_candidate_id" json:"release_candidate_id"`
	IdentityKey              string             `db:"identity_key" json:"identity_key"`
	Guid                     *string            `db:"guid" json:"guid"`
	Btih                     *string            `db:"btih" json:"btih"`
	CanonicalUrl             *string            `db:"canonical_url" json:"canonical_url"`
	Title                    string             `db:"title" json:"title"`
	PublishedAt              pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Status                   string             `db:"status" json:"status"`
	EnqueueAttempts          int32              `db:"enqueue_attempts" json:"enqueue_attempts"`
	LastErrorCode            *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage         *string            `db:"last_error_message" json:"last_error_message"`
	UpstreamPayload          []byte             `db:"upstream_payload" json:"upstream_payload"`
	DiscoveredAt             pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
	EnqueuedAt               pgtype.Timestamptz `db:"enqueued_at" json:"enqueued_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DownloadUri              *string            `db:"download_uri" json:"download_uri"`
	Downloadable             bool               `db:"downloadable" json:"downloadable"`
	RejectionReasons         []string           `db:"rejection_reasons" json:"rejection_reasons"`
	SourceSeason             *int32             `db:"source_season" json:"source_season"`
	SourceEpisode            *int32             `db:"source_episode" json:"source_episode"`
	DuplicateCount           int32              `db:"duplicate_count" json:"duplicate_count"`
	LastErrorRetryable       bool               `db:"last_error_retryable" json:"last_error_retryable"`
	ImportedAt               pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	CoordinateSource         *string            `db:"coordinate_source" json:"coordinate_source"`
	AgentResolutionID        pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
	FulfillmentSource        *string            `db:"fulfillment_source" json:"fulfillment_source"`
	AdjudicationState        string             `db:"adjudication_state" json:"adjudication_state"`
	AdjudicationSource       *string            `db:"adjudication_source" json:"adjudication_source"`
	AdjudicationResolutionID pgtype.UUID        `db:"adjudication_resolution_id" json:"adjudication_resolution_id"`
	RelatedEntryID           pgtype.UUID        `db:"related_entry_id" json:"related_entry_id"`
}

func (q *Queries) LockRSSAdjudicationEntries(ctx context.Context, batchID pgtype.UUID) ([]LockRSSAdjudicationEntriesRow, error) {
	rows, err := q.db.Query(ctx, lockRSSAdjudicationEntries, batchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockRSSAdjudicationEntriesRow{}
	for rows.Next() {
		var i LockRSSAdjudicationEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ReleaseCandidateID,
			&i.IdentityKey,
			&i.Guid,
			&i.Btih,
			&i.CanonicalUrl,
			&i.Title,
			&i.PublishedAt,
			&i.Status,
			&i.EnqueueAttempts,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.UpstreamPayload,
			&i.DiscoveredAt,
			&i.EnqueuedAt,
			&i.UpdatedAt,
			&i.DownloadUri,
			&i.Downloadable,
			&i.RejectionReasons,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.DuplicateCount,
			&i.LastErrorRetryable,
			&i.ImportedAt,
			&i.CoordinateSource,
			&i.AgentResolutionID,
			&i.FulfillmentSource,
			&i.AdjudicationState,
			&i.AdjudicationSource,
			&i.AdjudicationResolutionID,
			&i.RelatedEntryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRSSEntryForAgentCoordinate = `-- name: LockRSSEntryForAgentCoordinate :one
SELECT
    entry.id, entry.subscription_id, entry.release_candidate_id, entry.identity_key, entry.guid, entry.btih, entry.canonical_url, entry.title, entry.published_at, entry.status, entry.enqueue_attempts, entry.last_error_code, entry.last_error_message, entry.upstream_payload, entry.discovered_at, entry.enqueued_at, entry.updated_at, entry.download_uri, entry.downloadable, entry.rejection_reasons, entry.source_season, entry.source_episode, entry.duplicate_count, entry.last_error_retryable, entry.imported_at, entry.coordinate_source, entry.agent_resolution_id, entry.fulfillment_source,
    subscription.series_id,
    subscription.mapping_profile_id,
    subscription.source_season AS default_source_season,
    subscription.include_keywords,
    subscription.exclude_keywords,
    subscription.enabled AS subscription_enabled,
    subscription.version AS subscription_version,
    subscription.completed_at AS subscription_completed_at,
    subscription.deleted_at AS subscription_deleted_at
FROM rss_entries AS entry
JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
WHERE entry.id = $1
FOR UPDATE OF entry
`

type LockRSSEntryForAgentCoordinateRow struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID          pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	ReleaseCandidateID      pgtype.UUID        `db:"release_candidate_id" json:"release_candidate_id"`
	IdentityKey             string             `db:"identity_key" json:"identity_key"`
	Guid                    *string            `db:"guid" json:"guid"`
	Btih                    *string            `db:"btih" json:"btih"`
	CanonicalUrl            *string            `db:"canonical_url" json:"canonical_url"`
	Title                   string             `db:"title" json:"title"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Status                  string             `db:"status" json:"status"`
	EnqueueAttempts         int32              `db:"enqueue_attempts" json:"enqueue_attempts"`
	LastErrorCode           *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage        *string            `db:"last_error_message" json:"last_error_message"`
	UpstreamPayload         []byte             `db:"upstream_payload" json:"upstream_payload"`
	DiscoveredAt            pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
	EnqueuedAt              pgtype.Timestamptz `db:"enqueued_at" json:"enqueued_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DownloadUri             *string            `db:"download_uri" json:"download_uri"`
	Downloadable            bool               `db:"downloadable" json:"downloadable"`
	RejectionReasons        []string           `db:"rejection_reasons" json:"rejection_reasons"`
	SourceSeason            *int32             `db:"source_season" json:"source_season"`
	SourceEpisode           *int32             `db:"source_episode" json:"source_episode"`
	DuplicateCount          int32              `db:"duplicate_count" json:"duplicate_count"`
	LastErrorRetryable      bool               `db:"last_error_retryable" json:"last_error_retryable"`
	ImportedAt              pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	CoordinateSource        *string            `db:"coordinate_source" json:"coordinate_source"`
	AgentResolutionID       pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
	FulfillmentSource       *string            `db:"fulfillment_source" json:"fulfillment_source"`
	SeriesID                pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID        pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	DefaultSourceSeason     int32              `db:"default_source_season" json:"default_source_season"`
	IncludeKeywords         []string           `db:"include_keywords" json:"include_keywords"`
	ExcludeKeywords         []string           `db:"exclude_keywords" json:"exclude_keywords"`
	SubscriptionEnabled     bool               `db:"subscription_enabled" json:"subscription_enabled"`
	SubscriptionVersion     int32              `db:"subscription_version" json:"subscription_version"`
	SubscriptionCompletedAt pgtype.Timestamptz `db:"subscription_completed_at" json:"subscription_completed_at"`
	SubscriptionDeletedAt   pgtype.Timestamptz `db:"subscription_deleted_at" json:"subscription_deleted_at"`
}

func (q *Queries) LockRSSEntryForAgentCoordinate(ctx context.Context, id pgtype.UUID) (LockRSSEntryForAgentCoordinateRow, error) {
	row := q.db.QueryRow(ctx, lockRSSEntryForAgentCoordinate, id)
	var i LockRSSEntryForAgentCoordinateRow
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.ReleaseCandidateID,
		&i.IdentityKey,
		&i.Guid,
		&i.Btih,
		&i.CanonicalUrl,
		&i.Title,
		&i.PublishedAt,
		&i.Status,
		&i.EnqueueAttempts,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.UpstreamPayload,
		&i.DiscoveredAt,
		&i.EnqueuedAt,
		&i.UpdatedAt,
		&i.DownloadUri,
		&i.Downloadable,
		&i.RejectionReasons,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.DuplicateCount,
		&i.LastErrorRetryable,
		&i.ImportedAt,
		&i.CoordinateSource,
		&i.AgentResolutionID,
		&i.FulfillmentSource,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.DefaultSourceSeason,
		&i.IncludeKeywords,
		&i.ExcludeKeywords,
		&i.SubscriptionEnabled,
		&i.SubscriptionVersion,
		&i.SubscriptionCompletedAt,
		&i.SubscriptionDeletedAt,
	)
	return i, err
}

const markAgentResolutionOperationTerminal = `-- name: MarkAgentResolutionOperationTerminal :one
UPDATE agent_resolutions
SET status = $1,
    error_code = $2,
    error_message = $3,
    completed_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $4
  AND status IN ('queued', 'running', 'proposed')
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

type MarkAgentResolutionOperationTerminalParams struct {
	Status       string      `db:"status" json:"status"`
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkAgentResolutionOperationTerminal(ctx context.Context, arg MarkAgentResolutionOperationTerminalParams) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, markAgentResolutionOperationTerminal,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requeueAgentResolution = `-- name: RequeueAgentResolution :one
UPDATE agent_resolutions
SET status = CASE
        WHEN status = 'failed' AND proposal <> '{}'::jsonb THEN 'proposed'
        ELSE 'queued'
    END,
    operation_id = $1,
    proposal = CASE WHEN status = 'rejected' THEN '{}'::jsonb ELSE proposal END,
    validation = '{}'::jsonb,
    error_code = NULL,
    error_message = NULL,
    input_tokens = CASE WHEN status = 'rejected' THEN NULL ELSE input_tokens END,
    output_tokens = CASE WHEN status = 'rejected' THEN NULL ELSE output_tokens END,
    tool_call_count = CASE WHEN status = 'rejected' THEN 0 ELSE tool_call_count END,
    latency_milliseconds = CASE WHEN status = 'rejected' THEN NULL ELSE latency_milliseconds END,
    reviewed_by = NULL,
    review_decision = NULL,
    reviewed_at = NULL,
    completed_at = NULL,
    started_at = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $2
  AND version = $3
  AND status IN ('failed', 'rejected')
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

type RequeueAgentResolutionParams struct {
	OperationID     pgtype.UUID `db:"operation_id" json:"operation_id"`
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueAgentResolution(ctx context.Context, arg RequeueAgentResolutionParams) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, requeueAgentResolution, arg.OperationID, arg.ID, arg.ExpectedVersion)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveAgentResolutionProposal = `-- name: SaveAgentResolutionProposal :one
UPDATE agent_resolutions
SET status = 'proposed',
    proposal = $1,
    input_tokens = $2,
    output_tokens = $3,
    tool_call_count = $4,
    latency_milliseconds = $5,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $6
  AND status = 'running'
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

type SaveAgentResolutionProposalParams struct {
	Proposal            []byte      `db:"proposal" json:"proposal"`
	InputTokens         *int64      `db:"input_tokens" json:"input_tokens"`
	OutputTokens        *int64      `db:"output_tokens" json:"output_tokens"`
	ToolCallCount       int32       `db:"tool_call_count" json:"tool_call_count"`
	LatencyMilliseconds *int64      `db:"latency_milliseconds" json:"latency_milliseconds"`
	ID                  pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SaveAgentResolutionProposal(ctx context.Context, arg SaveAgentResolutionProposalParams) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, saveAgentResolutionProposal,
		arg.Proposal,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ToolCallCount,
		arg.LatencyMilliseconds,
		arg.ID,
	)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startAgentResolution = `-- name: StartAgentResolution :one
UPDATE agent_resolutions
SET status = 'running',
    started_at = COALESCE(started_at, now()),
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status IN ('queued', 'running')
RETURNING id, operation_id, version, capability, resource_type, resource_id, resource_version, trigger, status, input_fingerprint, configuration_version, protocol, provider_origin, model, prompt_version, toolset_version, proposal, validation, error_code, error_message, input_tokens, output_tokens, tool_call_count, latency_milliseconds, created_by, reviewed_by, review_decision, created_at, started_at, completed_at, reviewed_at, applied_at, updated_at
`

func (q *Queries) StartAgentResolution(ctx context.Context, id pgtype.UUID) (AgentResolution, error) {
	row := q.db.QueryRow(ctx, startAgentResolution, id)
	var i AgentResolution
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Version,
		&i.Capability,
		&i.ResourceType,
		&i.ResourceID,
		&i.ResourceVersion,
		&i.Trigger,
		&i.Status,
		&i.InputFingerprint,
		&i.ConfigurationVersion,
		&i.Protocol,
		&i.ProviderOrigin,
		&i.Model,
		&i.PromptVersion,
		&i.ToolsetVersion,
		&i.Proposal,
		&i.Validation,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.InputTokens,
		&i.OutputTokens,
		&i.ToolCallCount,
		&i.LatencyMilliseconds,
		&i.CreatedBy,
		&i.ReviewedBy,
		&i.ReviewDecision,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReviewedAt,
		&i.AppliedAt,
		&i.UpdatedAt,
	)
	return i, err
}
