// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT count(*)
FROM admin_users
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (
    id,
    username,
    password_hash
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, username, password_hash, disabled, created_at, updated_at
`

type CreateAdminUserParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Username     string      `db:"username" json:"username"`
	PasswordHash string      `db:"password_hash" json:"password_hash"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.ID, arg.Username, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    admin_user_id,
    token_hash,
    expires_at
) VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, admin_user_id, token_hash, expires_at, last_seen_at, revoked_at, created_at
`

type CreateSessionParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	AdminUserID pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	TokenHash   []byte             `db:"token_hash" json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.AdminUserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT
    session.id AS session_id,
    session.expires_at,
    admin_user.id AS admin_user_id,
    admin_user.username
FROM sessions AS session
JOIN admin_users AS admin_user ON admin_user.id = session.admin_user_id
WHERE session.token_hash = $1
  AND session.revoked_at IS NULL
  AND session.expires_at > now()
  AND NOT admin_user.disabled
`

type GetActiveSessionByTokenHashRow struct {
	SessionID   pgtype.UUID        `db:"session_id" json:"session_id"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	AdminUserID pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	Username    string             `db:"username" json:"username"`
}

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, tokenHash []byte) (GetActiveSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, tokenHash)
	var i GetActiveSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.AdminUserID,
		&i.Username,
	)
	return i, err
}

const getAdminUserByUsername = `-- name: GetAdminUserByUsername :one
SELECT id, username, password_hash, disabled, created_at, updated_at
FROM admin_users
WHERE lower(username) = lower($1)
`

func (q *Queries) GetAdminUserByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
UPDATE sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE token_hash = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :execrows
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
  AND last_seen_at < now() - interval '5 minutes'
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
