// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyMappingProfileToRSSSubscription = `-- name: ApplyMappingProfileToRSSSubscription :one
UPDATE rss_subscriptions AS subscription
SET mapping_profile_id = $1,
    version = version + 1,
    updated_at = now()
FROM acquisitions AS acquisition
JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
WHERE acquisition.id = $2
  AND subscription.id = entry.subscription_id
  AND subscription.deleted_at IS NULL
RETURNING subscription.id
`

type ApplyMappingProfileToRSSSubscriptionParams struct {
	MappingProfileID pgtype.UUID `db:"mapping_profile_id" json:"mapping_profile_id"`
	AcquisitionID    pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
}

func (q *Queries) ApplyMappingProfileToRSSSubscription(ctx context.Context, arg ApplyMappingProfileToRSSSubscriptionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, applyMappingProfileToRSSSubscription, arg.MappingProfileID, arg.AcquisitionID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const completeEmbyScanRun = `-- name: CompleteEmbyScanRun :one
UPDATE emby_scan_runs
SET status = 'succeeded',
    library_count = $1,
    item_count = $2,
    error_code = NULL,
    error_message = NULL,
    completed_at = now(),
    updated_at = now()
WHERE id = $3
  AND status = 'running'
RETURNING id, operation_id, status, library_count, item_count, error_code, error_message, started_at, completed_at, created_by, created_at, updated_at
`

type CompleteEmbyScanRunParams struct {
	LibraryCount int32       `db:"library_count" json:"library_count"`
	ItemCount    int32       `db:"item_count" json:"item_count"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) CompleteEmbyScanRun(ctx context.Context, arg CompleteEmbyScanRunParams) (EmbyScanRun, error) {
	row := q.db.QueryRow(ctx, completeEmbyScanRun, arg.LibraryCount, arg.ItemCount, arg.ID)
	var i EmbyScanRun
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Status,
		&i.LibraryCount,
		&i.ItemCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeInstallation = `-- name: CompleteInstallation :one
INSERT INTO installation_state (id, completed_by)
VALUES (true, $1)
ON CONFLICT (id) DO NOTHING
RETURNING id, completed_by, completed_at
`

func (q *Queries) CompleteInstallation(ctx context.Context, completedBy pgtype.UUID) (InstallationState, error) {
	row := q.db.QueryRow(ctx, completeInstallation, completedBy)
	var i InstallationState
	err := row.Scan(&i.ID, &i.CompletedBy, &i.CompletedAt)
	return i, err
}

const countInstallationState = `-- name: CountInstallationState :one
SELECT count(*)
FROM installation_state
`

func (q *Queries) CountInstallationState(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInstallationState)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmbyScanRun = `-- name: CreateEmbyScanRun :one
INSERT INTO emby_scan_runs (
    id,
    operation_id,
    created_by
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (id) DO NOTHING
RETURNING id, operation_id, status, library_count, item_count, error_code, error_message, started_at, completed_at, created_by, created_at, updated_at
`

type CreateEmbyScanRunParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	OperationID pgtype.UUID `db:"operation_id" json:"operation_id"`
	CreatedBy   pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) CreateEmbyScanRun(ctx context.Context, arg CreateEmbyScanRunParams) (EmbyScanRun, error) {
	row := q.db.QueryRow(ctx, createEmbyScanRun, arg.ID, arg.OperationID, arg.CreatedBy)
	var i EmbyScanRun
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Status,
		&i.LibraryCount,
		&i.ItemCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEpisodeMapping = `-- name: CreateEpisodeMapping :one
INSERT INTO episode_mappings (
    id,
    profile_id,
    source_season,
    source_episode,
    absolute_episode,
    target_episode_id,
    mapping_status,
    match_source,
    error_code
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, profile_id, source_season, source_episode, absolute_episode, target_episode_id, mapping_status, match_source, error_code, created_at, updated_at
`

type CreateEpisodeMappingParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ProfileID       pgtype.UUID `db:"profile_id" json:"profile_id"`
	SourceSeason    int32       `db:"source_season" json:"source_season"`
	SourceEpisode   int32       `db:"source_episode" json:"source_episode"`
	AbsoluteEpisode *int32      `db:"absolute_episode" json:"absolute_episode"`
	TargetEpisodeID pgtype.UUID `db:"target_episode_id" json:"target_episode_id"`
	MappingStatus   string      `db:"mapping_status" json:"mapping_status"`
	MatchSource     string      `db:"match_source" json:"match_source"`
	ErrorCode       *string     `db:"error_code" json:"error_code"`
}

func (q *Queries) CreateEpisodeMapping(ctx context.Context, arg CreateEpisodeMappingParams) (EpisodeMapping, error) {
	row := q.db.QueryRow(ctx, createEpisodeMapping,
		arg.ID,
		arg.ProfileID,
		arg.SourceSeason,
		arg.SourceEpisode,
		arg.AbsoluteEpisode,
		arg.TargetEpisodeID,
		arg.MappingStatus,
		arg.MatchSource,
		arg.ErrorCode,
	)
	var i EpisodeMapping
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.AbsoluteEpisode,
		&i.TargetEpisodeID,
		&i.MappingStatus,
		&i.MatchSource,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMappingProfile = `-- name: CreateMappingProfile :one
INSERT INTO episode_mapping_profiles (
    id,
    series_id,
    name,
    version,
    source_season_lengths,
    anchor_source_season,
    anchor_source_episode,
    anchor_target_episode_id,
    target_episode_offset,
    active,
    created_by,
    decision_source,
    agent_resolution_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    NULL,
    $5,
    $6,
    $7,
    $8,
    true,
    $9,
    $10,
    $11
)
RETURNING id, series_id, name, version, source_season_lengths, active, created_at, created_by, anchor_source_season, anchor_source_episode, anchor_target_episode_id, target_episode_offset, decision_source, agent_resolution_id
`

type CreateMappingProfileParams struct {
	ID                    pgtype.UUID `db:"id" json:"id"`
	SeriesID              pgtype.UUID `db:"series_id" json:"series_id"`
	Name                  string      `db:"name" json:"name"`
	Version               int32       `db:"version" json:"version"`
	AnchorSourceSeason    *int32      `db:"anchor_source_season" json:"anchor_source_season"`
	AnchorSourceEpisode   *int32      `db:"anchor_source_episode" json:"anchor_source_episode"`
	AnchorTargetEpisodeID pgtype.UUID `db:"anchor_target_episode_id" json:"anchor_target_episode_id"`
	TargetEpisodeOffset   *int32      `db:"target_episode_offset" json:"target_episode_offset"`
	CreatedBy             pgtype.UUID `db:"created_by" json:"created_by"`
	DecisionSource        string      `db:"decision_source" json:"decision_source"`
	AgentResolutionID     pgtype.UUID `db:"agent_resolution_id" json:"agent_resolution_id"`
}

func (q *Queries) CreateMappingProfile(ctx context.Context, arg CreateMappingProfileParams) (EpisodeMappingProfile, error) {
	row := q.db.QueryRow(ctx, createMappingProfile,
		arg.ID,
		arg.SeriesID,
		arg.Name,
		arg.Version,
		arg.AnchorSourceSeason,
		arg.AnchorSourceEpisode,
		arg.AnchorTargetEpisodeID,
		arg.TargetEpisodeOffset,
		arg.CreatedBy,
		arg.DecisionSource,
		arg.AgentResolutionID,
	)
	var i EpisodeMappingProfile
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.Name,
		&i.Version,
		&i.SourceSeasonLengths,
		&i.Active,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.AnchorSourceSeason,
		&i.AnchorSourceEpisode,
		&i.AnchorTargetEpisodeID,
		&i.TargetEpisodeOffset,
		&i.DecisionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const createMappingSave = `-- name: CreateMappingSave :one
INSERT INTO episode_mapping_saves (
    id,
    acquisition_id,
    profile_id,
    idempotency_key,
    request_fingerprint,
    result_payload,
    created_by,
    decision_source,
    agent_resolution_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, acquisition_id, profile_id, idempotency_key, request_fingerprint, result_payload, created_by, created_at, decision_source, agent_resolution_id
`

type CreateMappingSaveParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	AcquisitionID      pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
	ProfileID          pgtype.UUID `db:"profile_id" json:"profile_id"`
	IdempotencyKey     string      `db:"idempotency_key" json:"idempotency_key"`
	RequestFingerprint []byte      `db:"request_fingerprint" json:"request_fingerprint"`
	ResultPayload      []byte      `db:"result_payload" json:"result_payload"`
	CreatedBy          pgtype.UUID `db:"created_by" json:"created_by"`
	DecisionSource     string      `db:"decision_source" json:"decision_source"`
	AgentResolutionID  pgtype.UUID `db:"agent_resolution_id" json:"agent_resolution_id"`
}

func (q *Queries) CreateMappingSave(ctx context.Context, arg CreateMappingSaveParams) (EpisodeMappingSafe, error) {
	row := q.db.QueryRow(ctx, createMappingSave,
		arg.ID,
		arg.AcquisitionID,
		arg.ProfileID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.ResultPayload,
		arg.CreatedBy,
		arg.DecisionSource,
		arg.AgentResolutionID,
	)
	var i EpisodeMappingSafe
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.ProfileID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ResultPayload,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DecisionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const deactivateMappingProfiles = `-- name: DeactivateMappingProfiles :execrows
UPDATE episode_mapping_profiles
SET active = false
WHERE series_id = $1
  AND name = $2
  AND active
`

type DeactivateMappingProfilesParams struct {
	SeriesID pgtype.UUID `db:"series_id" json:"series_id"`
	Name     string      `db:"name" json:"name"`
}

func (q *Queries) DeactivateMappingProfiles(ctx context.Context, arg DeactivateMappingProfilesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateMappingProfiles, arg.SeriesID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleTMDbEpisodes = `-- name: DeleteStaleTMDbEpisodes :execrows
DELETE FROM media_episodes
WHERE season_id = $1
  AND episode_number <> ALL($2::integer[])
`

type DeleteStaleTMDbEpisodesParams struct {
	SeasonID       pgtype.UUID `db:"season_id" json:"season_id"`
	EpisodeNumbers []int32     `db:"episode_numbers" json:"episode_numbers"`
}

func (q *Queries) DeleteStaleTMDbEpisodes(ctx context.Context, arg DeleteStaleTMDbEpisodesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleTMDbEpisodes, arg.SeasonID, arg.EpisodeNumbers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleTMDbSeasons = `-- name: DeleteStaleTMDbSeasons :execrows
DELETE FROM tmdb_seasons
WHERE series_id = $1
  AND season_number <> ALL($2::integer[])
`

type DeleteStaleTMDbSeasonsParams struct {
	SeriesID      pgtype.UUID `db:"series_id" json:"series_id"`
	SeasonNumbers []int32     `db:"season_numbers" json:"season_numbers"`
}

func (q *Queries) DeleteStaleTMDbSeasons(ctx context.Context, arg DeleteStaleTMDbSeasonsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleTMDbSeasons, arg.SeriesID, arg.SeasonNumbers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failEmbyScanRun = `-- name: FailEmbyScanRun :one
UPDATE emby_scan_runs
SET status = $1,
    error_code = $2,
    error_message = $3,
    completed_at = now(),
    updated_at = now()
WHERE id = $4
  AND status IN ('queued', 'running')
RETURNING id, operation_id, status, library_count, item_count, error_code, error_message, started_at, completed_at, created_by, created_at, updated_at
`

type FailEmbyScanRunParams struct {
	Status       string      `db:"status" json:"status"`
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) FailEmbyScanRun(ctx context.Context, arg FailEmbyScanRunParams) (EmbyScanRun, error) {
	row := q.db.QueryRow(ctx, failEmbyScanRun,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
	)
	var i EmbyScanRun
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Status,
		&i.LibraryCount,
		&i.ItemCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcquisitionMappingContext = `-- name: GetAcquisitionMappingContext :one
SELECT acquisition.id, acquisition.series_id, acquisition.mapping_profile_id, acquisition.source_kind, acquisition.release_candidate_id, acquisition.rss_entry_id, acquisition.source_uri, acquisition.source_payload, acquisition.legacy_id, acquisition.created_by, acquisition.created_at, acquisition.updated_at, acquisition.deletion_requested_at, series.tmdb_series_id, entry.subscription_id AS rss_subscription_id
FROM acquisitions AS acquisition
JOIN media_series AS series ON series.id = acquisition.series_id
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
WHERE acquisition.id = $1
`

type GetAcquisitionMappingContextRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SeriesID            pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID    pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	SourceKind          string             `db:"source_kind" json:"source_kind"`
	ReleaseCandidateID  pgtype.UUID        `db:"release_candidate_id" json:"release_candidate_id"`
	RssEntryID          pgtype.UUID        `db:"rss_entry_id" json:"rss_entry_id"`
	SourceUri           *string            `db:"source_uri" json:"source_uri"`
	SourcePayload       []byte             `db:"source_payload" json:"source_payload"`
	LegacyID            *string            `db:"legacy_id" json:"legacy_id"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletionRequestedAt pgtype.Timestamptz `db:"deletion_requested_at" json:"deletion_requested_at"`
	TmdbSeriesID        *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
	RssSubscriptionID   pgtype.UUID        `db:"rss_subscription_id" json:"rss_subscription_id"`
}

func (q *Queries) GetAcquisitionMappingContext(ctx context.Context, id pgtype.UUID) (GetAcquisitionMappingContextRow, error) {
	row := q.db.QueryRow(ctx, getAcquisitionMappingContext, id)
	var i GetAcquisitionMappingContextRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.SourceKind,
		&i.ReleaseCandidateID,
		&i.RssEntryID,
		&i.SourceUri,
		&i.SourcePayload,
		&i.LegacyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.TmdbSeriesID,
		&i.RssSubscriptionID,
	)
	return i, err
}

const getCompatibleActiveMappingProfile = `-- name: GetCompatibleActiveMappingProfile :one
SELECT profile.id
FROM episode_mapping_profiles AS profile
WHERE profile.id = $1
  AND profile.series_id = $2
  AND profile.active
  AND (
      (
          profile.anchor_source_season = $3
          AND profile.anchor_target_episode_id IS NOT NULL
          AND EXISTS (
              SELECT 1
              FROM episode_mappings AS mapping
              JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
              JOIN tmdb_seasons AS season ON season.id = episode.season_id
              WHERE mapping.profile_id = profile.id
                AND mapping.source_season = $3
                AND mapping.mapping_status = 'mapped'
                AND season.series_id = profile.series_id
          )
          AND NOT EXISTS (
              SELECT 1
              FROM episode_mappings AS mapping
              WHERE mapping.profile_id = profile.id
                AND mapping.source_season = $3
                AND mapping.mapping_status <> 'mapped'
          )
      )
      OR (
          profile.anchor_source_season IS NULL
          AND cardinality(profile.source_season_lengths) >= $3::integer
          AND profile.source_season_lengths[$3::integer] > 0
          AND NOT EXISTS (
              SELECT 1
              FROM generate_series(
                  1,
                  profile.source_season_lengths[$3::integer]
              ) AS expected(source_episode)
              WHERE NOT EXISTS (
                  SELECT 1
                  FROM episode_mappings AS mapping
                  JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
                  JOIN tmdb_seasons AS season ON season.id = episode.season_id
                  WHERE mapping.profile_id = profile.id
                    AND mapping.source_season = $3
                    AND mapping.source_episode = expected.source_episode
                    AND mapping.mapping_status = 'mapped'
                    AND season.series_id = profile.series_id
              )
          )
          AND NOT EXISTS (
              SELECT 1
              FROM episode_mappings AS mapping
              WHERE mapping.profile_id = profile.id
                AND mapping.source_season = $3
                AND (
                    mapping.source_episode < 1
                    OR mapping.source_episode > profile.source_season_lengths[$3::integer]
                    OR mapping.mapping_status <> 'mapped'
                )
          )
      )
  )
`

type GetCompatibleActiveMappingProfileParams struct {
	ProfileID    pgtype.UUID `db:"profile_id" json:"profile_id"`
	SeriesID     pgtype.UUID `db:"series_id" json:"series_id"`
	SourceSeason *int32      `db:"source_season" json:"source_season"`
}

func (q *Queries) GetCompatibleActiveMappingProfile(ctx context.Context, arg GetCompatibleActiveMappingProfileParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCompatibleActiveMappingProfile, arg.ProfileID, arg.SeriesID, arg.SourceSeason)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEmbyLibrary = `-- name: GetEmbyLibrary :one
SELECT id, emby_id, name, collection_type, locations, present, last_scan_run_id, last_seen_at, upstream_payload, created_at, updated_at
FROM emby_libraries
WHERE id = $1
`

func (q *Queries) GetEmbyLibrary(ctx context.Context, id pgtype.UUID) (EmbyLibrary, error) {
	row := q.db.QueryRow(ctx, getEmbyLibrary, id)
	var i EmbyLibrary
	err := row.Scan(
		&i.ID,
		&i.EmbyID,
		&i.Name,
		&i.CollectionType,
		&i.Locations,
		&i.Present,
		&i.LastScanRunID,
		&i.LastSeenAt,
		&i.UpstreamPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbyScanRun = `-- name: GetEmbyScanRun :one
SELECT id, operation_id, status, library_count, item_count, error_code, error_message, started_at, completed_at, created_by, created_at, updated_at
FROM emby_scan_runs
WHERE id = $1
`

func (q *Queries) GetEmbyScanRun(ctx context.Context, id pgtype.UUID) (EmbyScanRun, error) {
	row := q.db.QueryRow(ctx, getEmbyScanRun, id)
	var i EmbyScanRun
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Status,
		&i.LibraryCount,
		&i.ItemCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmbyScanRunByOperation = `-- name: GetEmbyScanRunByOperation :one
SELECT id, operation_id, status, library_count, item_count, error_code, error_message, started_at, completed_at, created_by, created_at, updated_at
FROM emby_scan_runs
WHERE operation_id = $1
`

func (q *Queries) GetEmbyScanRunByOperation(ctx context.Context, operationID pgtype.UUID) (EmbyScanRun, error) {
	row := q.db.QueryRow(ctx, getEmbyScanRunByOperation, operationID)
	var i EmbyScanRun
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Status,
		&i.LibraryCount,
		&i.ItemCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstAdminUser = `-- name: GetFirstAdminUser :one
SELECT id, username, password_hash, disabled, created_at, updated_at
FROM admin_users
ORDER BY created_at, id
LIMIT 1
`

func (q *Queries) GetFirstAdminUser(ctx context.Context) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getFirstAdminUser)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationState = `-- name: GetInstallationState :one
SELECT id, completed_by, completed_at
FROM installation_state
WHERE id = true
`

func (q *Queries) GetInstallationState(ctx context.Context) (InstallationState, error) {
	row := q.db.QueryRow(ctx, getInstallationState)
	var i InstallationState
	err := row.Scan(&i.ID, &i.CompletedBy, &i.CompletedAt)
	return i, err
}

const getLatestDownloadForAcquisition = `-- name: GetLatestDownloadForAcquisition :one
SELECT id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
FROM downloads
WHERE acquisition_id = $1
ORDER BY attempt DESC
LIMIT 1
`

func (q *Queries) GetLatestDownloadForAcquisition(ctx context.Context, acquisitionID pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getLatestDownloadForAcquisition, acquisitionID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const getMappingProfileAudit = `-- name: GetMappingProfileAudit :one
SELECT decision_source, agent_resolution_id
FROM episode_mapping_profiles
WHERE id = $1
`

type GetMappingProfileAuditRow struct {
	DecisionSource    string      `db:"decision_source" json:"decision_source"`
	AgentResolutionID pgtype.UUID `db:"agent_resolution_id" json:"agent_resolution_id"`
}

func (q *Queries) GetMappingProfileAudit(ctx context.Context, id pgtype.UUID) (GetMappingProfileAuditRow, error) {
	row := q.db.QueryRow(ctx, getMappingProfileAudit, id)
	var i GetMappingProfileAuditRow
	err := row.Scan(&i.DecisionSource, &i.AgentResolutionID)
	return i, err
}

const getMappingSaveByIdempotencyKey = `-- name: GetMappingSaveByIdempotencyKey :one
SELECT save.id, save.acquisition_id, save.profile_id, save.idempotency_key, save.request_fingerprint, save.result_payload, save.created_by, save.created_at, save.decision_source, save.agent_resolution_id, profile.version
FROM episode_mapping_saves AS save
JOIN episode_mapping_profiles AS profile ON profile.id = save.profile_id
WHERE save.idempotency_key = $1
`

type GetMappingSaveByIdempotencyKeyRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	AcquisitionID      pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	ProfileID          pgtype.UUID        `db:"profile_id" json:"profile_id"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	RequestFingerprint []byte             `db:"request_fingerprint" json:"request_fingerprint"`
	ResultPayload      []byte             `db:"result_payload" json:"result_payload"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DecisionSource     string             `db:"decision_source" json:"decision_source"`
	AgentResolutionID  pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
	Version            int32              `db:"version" json:"version"`
}

func (q *Queries) GetMappingSaveByIdempotencyKey(ctx context.Context, idempotencyKey string) (GetMappingSaveByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getMappingSaveByIdempotencyKey, idempotencyKey)
	var i GetMappingSaveByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.ProfileID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ResultPayload,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DecisionSource,
		&i.AgentResolutionID,
		&i.Version,
	)
	return i, err
}

const getMediaSeriesByID = `-- name: GetMediaSeriesByID :one
SELECT id, tmdb_series_id, title, original_title, media_type, metadata, legacy_id, created_at, updated_at, tmdb_movie_id, release_year
FROM media_series
WHERE id = $1
`

func (q *Queries) GetMediaSeriesByID(ctx context.Context, id pgtype.UUID) (MediaSeries, error) {
	row := q.db.QueryRow(ctx, getMediaSeriesByID, id)
	var i MediaSeries
	err := row.Scan(
		&i.ID,
		&i.TmdbSeriesID,
		&i.Title,
		&i.OriginalTitle,
		&i.MediaType,
		&i.Metadata,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TmdbMovieID,
		&i.ReleaseYear,
	)
	return i, err
}

const getMediaSeriesByTMDbID = `-- name: GetMediaSeriesByTMDbID :one
SELECT id, tmdb_series_id, title, original_title, media_type, metadata, legacy_id, created_at, updated_at, tmdb_movie_id, release_year
FROM media_series
WHERE tmdb_series_id = $1
`

func (q *Queries) GetMediaSeriesByTMDbID(ctx context.Context, tmdbSeriesID *int64) (MediaSeries, error) {
	row := q.db.QueryRow(ctx, getMediaSeriesByTMDbID, tmdbSeriesID)
	var i MediaSeries
	err := row.Scan(
		&i.ID,
		&i.TmdbSeriesID,
		&i.Title,
		&i.OriginalTitle,
		&i.MediaType,
		&i.Metadata,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TmdbMovieID,
		&i.ReleaseYear,
	)
	return i, err
}

const getSeriesLastSync = `-- name: GetSeriesLastSync :one
SELECT max(fetched_at)
FROM tmdb_seasons
WHERE series_id = $1
`

func (q *Queries) GetSeriesLastSync(ctx context.Context, seriesID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getSeriesLastSync, seriesID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const listAcquisitionSelectedVideos = `-- name: ListAcquisitionSelectedVideos :many
SELECT
    file.id,
    file.relative_path,
    file.source_season,
    file.source_episode
FROM download_files AS file
JOIN downloads AS download ON download.id = file.download_id
WHERE download.acquisition_id = $1
  AND download.attempt = (
      SELECT max(candidate.attempt)
      FROM downloads AS candidate
      WHERE candidate.acquisition_id = $1
        AND EXISTS (
            SELECT 1
            FROM download_files AS candidate_file
            WHERE candidate_file.download_id = candidate.id
              AND candidate_file.selected
              AND candidate_file.media_kind = 'video'
        )
  )
  AND file.selected
  AND file.media_kind = 'video'
ORDER BY file.source_season, file.source_episode, file.file_index
`

type ListAcquisitionSelectedVideosRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	RelativePath  string      `db:"relative_path" json:"relative_path"`
	SourceSeason  *int32      `db:"source_season" json:"source_season"`
	SourceEpisode *int32      `db:"source_episode" json:"source_episode"`
}

func (q *Queries) ListAcquisitionSelectedVideos(ctx context.Context, acquisitionID pgtype.UUID) ([]ListAcquisitionSelectedVideosRow, error) {
	rows, err := q.db.Query(ctx, listAcquisitionSelectedVideos, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcquisitionSelectedVideosRow{}
	for rows.Next() {
		var i ListAcquisitionSelectedVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.RelativePath,
			&i.SourceSeason,
			&i.SourceEpisode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompatibleActiveMappingProfiles = `-- name: ListCompatibleActiveMappingProfiles :many
SELECT profile.id
FROM episode_mapping_profiles AS profile
WHERE profile.series_id = $1
  AND profile.active
  AND (
      (
          profile.anchor_source_season = $2
          AND profile.anchor_target_episode_id IS NOT NULL
          AND EXISTS (
              SELECT 1
              FROM episode_mappings AS mapping
              JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
              JOIN tmdb_seasons AS season ON season.id = episode.season_id
              WHERE mapping.profile_id = profile.id
                AND mapping.source_season = $2
                AND mapping.mapping_status = 'mapped'
                AND season.series_id = profile.series_id
          )
          AND NOT EXISTS (
              SELECT 1
              FROM episode_mappings AS mapping
              WHERE mapping.profile_id = profile.id
                AND mapping.source_season = $2
                AND mapping.mapping_status <> 'mapped'
          )
      )
      OR (
          profile.anchor_source_season IS NULL
          AND cardinality(profile.source_season_lengths) >= $2::integer
          AND profile.source_season_lengths[$2::integer] > 0
          AND NOT EXISTS (
              SELECT 1
              FROM generate_series(
                  1,
                  profile.source_season_lengths[$2::integer]
              ) AS expected(source_episode)
              WHERE NOT EXISTS (
                  SELECT 1
                  FROM episode_mappings AS mapping
                  JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
                  JOIN tmdb_seasons AS season ON season.id = episode.season_id
                  WHERE mapping.profile_id = profile.id
                    AND mapping.source_season = $2
                    AND mapping.source_episode = expected.source_episode
                    AND mapping.mapping_status = 'mapped'
                    AND season.series_id = profile.series_id
              )
          )
          AND NOT EXISTS (
              SELECT 1
              FROM episode_mappings AS mapping
              WHERE mapping.profile_id = profile.id
                AND mapping.source_season = $2
                AND (
                    mapping.source_episode < 1
                    OR mapping.source_episode > profile.source_season_lengths[$2::integer]
                    OR mapping.mapping_status <> 'mapped'
                )
          )
      )
  )
ORDER BY profile.created_at DESC, profile.id
LIMIT 2
`

type ListCompatibleActiveMappingProfilesParams struct {
	SeriesID     pgtype.UUID `db:"series_id" json:"series_id"`
	SourceSeason *int32      `db:"source_season" json:"source_season"`
}

func (q *Queries) ListCompatibleActiveMappingProfiles(ctx context.Context, arg ListCompatibleActiveMappingProfilesParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listCompatibleActiveMappingProfiles, arg.SeriesID, arg.SourceSeason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbyLibraries = `-- name: ListEmbyLibraries :many
SELECT id, emby_id, name, collection_type, locations, present, last_scan_run_id, last_seen_at, upstream_payload, created_at, updated_at
FROM emby_libraries
ORDER BY present DESC, lower(name), id
`

func (q *Queries) ListEmbyLibraries(ctx context.Context) ([]EmbyLibrary, error) {
	rows, err := q.db.Query(ctx, listEmbyLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbyLibrary{}
	for rows.Next() {
		var i EmbyLibrary
		if err := rows.Scan(
			&i.ID,
			&i.EmbyID,
			&i.Name,
			&i.CollectionType,
			&i.Locations,
			&i.Present,
			&i.LastScanRunID,
			&i.LastSeenAt,
			&i.UpstreamPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbyLibraryItems = `-- name: ListEmbyLibraryItems :many
SELECT
    item.id, item.emby_id, item.library_id, item.parent_emby_id, item.item_type, item.name, item.file_path, item.provider_ids, item.season_number, item.episode_number, item.present, item.last_scan_run_id, item.last_seen_at, item.upstream_payload, item.created_at, item.updated_at,
    related_task.id AS imported_task_id
FROM emby_library_items AS item
LEFT JOIN LATERAL (
    SELECT task.id
    FROM episode_tasks AS task
    LEFT JOIN LATERAL (
        SELECT import.destination_video_path
        FROM imports AS import
        WHERE import.task_id = task.id
          AND import.status = 'succeeded'
        ORDER BY import.attempt DESC
        LIMIT 1
    ) AS latest_import ON true
    LEFT JOIN episode_mappings AS mapping ON mapping.id = task.mapping_id
    LEFT JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
    WHERE latest_import.destination_video_path = item.file_path
       OR (
           episode.tmdb_episode_id IS NOT NULL
           AND EXISTS (
               SELECT 1
               FROM jsonb_each_text(item.provider_ids) AS provider
               WHERE lower(provider.key) IN ('tmdb', 'themoviedb')
                 AND provider.value = episode.tmdb_episode_id::text
           )
       )
    ORDER BY (latest_import.destination_video_path = item.file_path) DESC, task.updated_at DESC, task.id
    LIMIT 1
) AS related_task ON true
WHERE item.library_id = $1
  AND ($2::text IS NULL OR item.item_type = $2)
  AND ($3::text IS NULL OR item.name ILIKE '%' || $3::text || '%')
  AND ($4::boolean IS NULL OR item.present = $4::boolean)
  AND (
      $5::text IS NULL
      OR EXISTS (
          SELECT 1
          FROM jsonb_each_text(item.provider_ids) AS provider
          WHERE provider.value = $5::text
      )
  )
  AND ($6::uuid IS NULL OR item.id > $6)
ORDER BY item.id
LIMIT $7
`

type ListEmbyLibraryItemsParams struct {
	LibraryID  pgtype.UUID `db:"library_id" json:"library_id"`
	ItemType   *string     `db:"item_type" json:"item_type"`
	Name       *string     `db:"name" json:"name"`
	Present    *bool       `db:"present" json:"present"`
	ProviderID *string     `db:"provider_id" json:"provider_id"`
	Cursor     pgtype.UUID `db:"cursor" json:"cursor"`
	PageSize   int32       `db:"page_size" json:"page_size"`
}

type ListEmbyLibraryItemsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	EmbyID          string             `db:"emby_id" json:"emby_id"`
	LibraryID       pgtype.UUID        `db:"library_id" json:"library_id"`
	ParentEmbyID    *string            `db:"parent_emby_id" json:"parent_emby_id"`
	ItemType        string             `db:"item_type" json:"item_type"`
	Name            string             `db:"name" json:"name"`
	FilePath        *string            `db:"file_path" json:"file_path"`
	ProviderIds     []byte             `db:"provider_ids" json:"provider_ids"`
	SeasonNumber    *int32             `db:"season_number" json:"season_number"`
	EpisodeNumber   *int32             `db:"episode_number" json:"episode_number"`
	Present         bool               `db:"present" json:"present"`
	LastScanRunID   pgtype.UUID        `db:"last_scan_run_id" json:"last_scan_run_id"`
	LastSeenAt      pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ImportedTaskID  pgtype.UUID        `db:"imported_task_id" json:"imported_task_id"`
}

func (q *Queries) ListEmbyLibraryItems(ctx context.Context, arg ListEmbyLibraryItemsParams) ([]ListEmbyLibraryItemsRow, error) {
	rows, err := q.db.Query(ctx, listEmbyLibraryItems,
		arg.LibraryID,
		arg.ItemType,
		arg.Name,
		arg.Present,
		arg.ProviderID,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbyLibraryItemsRow{}
	for rows.Next() {
		var i ListEmbyLibraryItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmbyID,
			&i.LibraryID,
			&i.ParentEmbyID,
			&i.ItemType,
			&i.Name,
			&i.FilePath,
			&i.ProviderIds,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.Present,
			&i.LastScanRunID,
			&i.LastSeenAt,
			&i.UpstreamPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ImportedTaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbyScanRuns = `-- name: ListEmbyScanRuns :many
SELECT scan.id, scan.operation_id, scan.status, scan.library_count, scan.item_count, scan.error_code, scan.error_message, scan.started_at, scan.completed_at, scan.created_by, scan.created_at, scan.updated_at
FROM emby_scan_runs AS scan
WHERE $1::uuid IS NULL
   OR (scan.created_at, scan.id) < (
       SELECT cursor_scan.created_at, cursor_scan.id
       FROM emby_scan_runs AS cursor_scan
       WHERE cursor_scan.id = $1::uuid
   )
ORDER BY scan.created_at DESC, scan.id DESC
LIMIT $2
`

type ListEmbyScanRunsParams struct {
	Cursor   pgtype.UUID `db:"cursor" json:"cursor"`
	PageSize int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListEmbyScanRuns(ctx context.Context, arg ListEmbyScanRunsParams) ([]EmbyScanRun, error) {
	rows, err := q.db.Query(ctx, listEmbyScanRuns, arg.Cursor, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbyScanRun{}
	for rows.Next() {
		var i EmbyScanRun
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Status,
			&i.LibraryCount,
			&i.ItemCount,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMappingMaterializationCandidates = `-- name: ListMappingMaterializationCandidates :many
WITH source_subscription AS (
    SELECT entry.subscription_id
    FROM acquisitions AS source_acquisition
    JOIN rss_entries AS entry ON entry.id = source_acquisition.rss_entry_id
    JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
    WHERE source_acquisition.id = $1
      AND subscription.deleted_at IS NULL
)
SELECT download.id, download.status, download.version, download.failure_stage, download.error_code
FROM acquisitions AS acquisition
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
JOIN downloads AS download ON download.acquisition_id = acquisition.id
WHERE (
      acquisition.id = $1
      OR entry.subscription_id = (SELECT subscription_id FROM source_subscription)
  )
  AND acquisition.mapping_profile_id = $2
  AND acquisition.deletion_requested_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM episode_tasks AS task
      WHERE task.acquisition_id = acquisition.id
  )
  AND download.attempt = (
      SELECT max(candidate.attempt)
      FROM downloads AS candidate
      WHERE candidate.acquisition_id = acquisition.id
        AND EXISTS (
            SELECT 1
            FROM download_files AS candidate_file
            WHERE candidate_file.download_id = candidate.id
              AND candidate_file.selected
              AND candidate_file.media_kind = 'video'
        )
  )
  AND (
      download.status = 'completed'
      OR (
          download.status = 'failed'
          AND download.failure_stage = 'materialize'
          AND download.error_code IN (
              'mapping_profile_required',
              'episode_mapping_required',
              'mapping_source_invalid',
              'mapping_source_out_of_range',
              'mapping_context_incomplete',
              'mapping_target_out_of_range',
              'mapping_title_missing'
          )
      )
  )
  AND EXISTS (
      SELECT 1
      FROM download_files AS selected_video
      WHERE selected_video.download_id = download.id
        AND selected_video.selected
        AND selected_video.media_kind = 'video'
  )
  AND NOT EXISTS (
      SELECT 1
      FROM download_files AS selected_video
      LEFT JOIN episode_mappings AS mapping
        ON mapping.profile_id = $2
       AND mapping.source_season = selected_video.source_season
       AND mapping.source_episode = selected_video.source_episode
      WHERE selected_video.download_id = download.id
        AND selected_video.selected
        AND selected_video.media_kind = 'video'
        AND (mapping.id IS NULL OR mapping.mapping_status <> 'mapped')
  )
ORDER BY acquisition.created_at, acquisition.id, download.attempt
`

type ListMappingMaterializationCandidatesParams struct {
	AcquisitionID    pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
	MappingProfileID pgtype.UUID `db:"mapping_profile_id" json:"mapping_profile_id"`
}

type ListMappingMaterializationCandidatesRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Status       string      `db:"status" json:"status"`
	Version      int32       `db:"version" json:"version"`
	FailureStage *string     `db:"failure_stage" json:"failure_stage"`
	ErrorCode    *string     `db:"error_code" json:"error_code"`
}

func (q *Queries) ListMappingMaterializationCandidates(ctx context.Context, arg ListMappingMaterializationCandidatesParams) ([]ListMappingMaterializationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMappingMaterializationCandidates, arg.AcquisitionID, arg.MappingProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMappingMaterializationCandidatesRow{}
	for rows.Next() {
		var i ListMappingMaterializationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Version,
			&i.FailureStage,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMappingScopeSelectedVideos = `-- name: ListMappingScopeSelectedVideos :many
WITH source_subscription AS (
    SELECT entry.subscription_id
    FROM acquisitions AS source_acquisition
    JOIN rss_entries AS entry ON entry.id = source_acquisition.rss_entry_id
    JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
    WHERE source_acquisition.id = $1
      AND subscription.deleted_at IS NULL
)
SELECT file.id, file.relative_path, file.source_season, file.source_episode
FROM acquisitions AS acquisition
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
JOIN downloads AS download ON download.acquisition_id = acquisition.id
JOIN download_files AS file ON file.download_id = download.id
WHERE (
      acquisition.id = $1
      OR entry.subscription_id = (SELECT subscription_id FROM source_subscription)
  )
  AND acquisition.deletion_requested_at IS NULL
  AND NOT EXISTS (
      SELECT 1
      FROM episode_tasks AS task
      WHERE task.acquisition_id = acquisition.id
  )
  AND download.attempt = (
      SELECT max(candidate.attempt)
      FROM downloads AS candidate
      WHERE candidate.acquisition_id = acquisition.id
        AND EXISTS (
            SELECT 1
            FROM download_files AS candidate_file
            WHERE candidate_file.download_id = candidate.id
              AND candidate_file.selected
              AND candidate_file.media_kind = 'video'
        )
  )
  AND file.selected
  AND file.media_kind = 'video'
ORDER BY acquisition.created_at, acquisition.id, file.file_index
`

type ListMappingScopeSelectedVideosRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	RelativePath  string      `db:"relative_path" json:"relative_path"`
	SourceSeason  *int32      `db:"source_season" json:"source_season"`
	SourceEpisode *int32      `db:"source_episode" json:"source_episode"`
}

func (q *Queries) ListMappingScopeSelectedVideos(ctx context.Context, acquisitionID pgtype.UUID) ([]ListMappingScopeSelectedVideosRow, error) {
	rows, err := q.db.Query(ctx, listMappingScopeSelectedVideos, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMappingScopeSelectedVideosRow{}
	for rows.Next() {
		var i ListMappingScopeSelectedVideosRow
		if err := rows.Scan(
			&i.ID,
			&i.RelativePath,
			&i.SourceSeason,
			&i.SourceEpisode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaSeriesByIDs = `-- name: ListMediaSeriesByIDs :many
SELECT id, tmdb_series_id, title, original_title, media_type, metadata, legacy_id, created_at, updated_at, tmdb_movie_id, release_year
FROM media_series
WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListMediaSeriesByIDs(ctx context.Context, ids []pgtype.UUID) ([]MediaSeries, error) {
	rows, err := q.db.Query(ctx, listMediaSeriesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaSeries{}
	for rows.Next() {
		var i MediaSeries
		if err := rows.Scan(
			&i.ID,
			&i.TmdbSeriesID,
			&i.Title,
			&i.OriginalTitle,
			&i.MediaType,
			&i.Metadata,
			&i.LegacyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TmdbMovieID,
			&i.ReleaseYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonEpisodes = `-- name: ListSeasonEpisodes :many
SELECT id, season_id, tmdb_episode_id, episode_number, title, air_date, upstream_payload, created_at, updated_at
FROM media_episodes
WHERE season_id = $1
ORDER BY episode_number
`

func (q *Queries) ListSeasonEpisodes(ctx context.Context, seasonID pgtype.UUID) ([]MediaEpisode, error) {
	rows, err := q.db.Query(ctx, listSeasonEpisodes, seasonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaEpisode{}
	for rows.Next() {
		var i MediaEpisode
		if err := rows.Scan(
			&i.ID,
			&i.SeasonID,
			&i.TmdbEpisodeID,
			&i.EpisodeNumber,
			&i.Title,
			&i.AirDate,
			&i.UpstreamPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesMappingCatalog = `-- name: ListSeriesMappingCatalog :many
SELECT
    season.season_number,
    season.episode_count,
    episode.id AS episode_id,
    episode.episode_number,
    episode.title
FROM tmdb_seasons AS season
LEFT JOIN media_episodes AS episode ON episode.season_id = season.id
WHERE season.series_id = $1
ORDER BY season.season_number, episode.episode_number
`

type ListSeriesMappingCatalogRow struct {
	SeasonNumber  int32       `db:"season_number" json:"season_number"`
	EpisodeCount  int32       `db:"episode_count" json:"episode_count"`
	EpisodeID     pgtype.UUID `db:"episode_id" json:"episode_id"`
	EpisodeNumber *int32      `db:"episode_number" json:"episode_number"`
	Title         *string     `db:"title" json:"title"`
}

func (q *Queries) ListSeriesMappingCatalog(ctx context.Context, seriesID pgtype.UUID) ([]ListSeriesMappingCatalogRow, error) {
	rows, err := q.db.Query(ctx, listSeriesMappingCatalog, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesMappingCatalogRow{}
	for rows.Next() {
		var i ListSeriesMappingCatalogRow
		if err := rows.Scan(
			&i.SeasonNumber,
			&i.EpisodeCount,
			&i.EpisodeID,
			&i.EpisodeNumber,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesSeasons = `-- name: ListSeriesSeasons :many
SELECT id, series_id, tmdb_season_id, season_number, name, episode_count, fetched_at, upstream_payload, created_at, updated_at
FROM tmdb_seasons
WHERE series_id = $1
ORDER BY season_number
`

func (q *Queries) ListSeriesSeasons(ctx context.Context, seriesID pgtype.UUID) ([]TmdbSeason, error) {
	rows, err := q.db.Query(ctx, listSeriesSeasons, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TmdbSeason{}
	for rows.Next() {
		var i TmdbSeason
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.TmdbSeasonID,
			&i.SeasonNumber,
			&i.Name,
			&i.EpisodeCount,
			&i.FetchedAt,
			&i.UpstreamPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAcquisitionForMapping = `-- name: LockAcquisitionForMapping :one
SELECT acquisition.id, acquisition.series_id, acquisition.mapping_profile_id, acquisition.source_kind, acquisition.release_candidate_id, acquisition.rss_entry_id, acquisition.source_uri, acquisition.source_payload, acquisition.legacy_id, acquisition.created_by, acquisition.created_at, acquisition.updated_at, acquisition.deletion_requested_at, series.tmdb_series_id, entry.subscription_id AS rss_subscription_id
FROM acquisitions AS acquisition
JOIN media_series AS series ON series.id = acquisition.series_id
LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
WHERE acquisition.id = $1
FOR UPDATE OF acquisition
`

type LockAcquisitionForMappingRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SeriesID            pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID    pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	SourceKind          string             `db:"source_kind" json:"source_kind"`
	ReleaseCandidateID  pgtype.UUID        `db:"release_candidate_id" json:"release_candidate_id"`
	RssEntryID          pgtype.UUID        `db:"rss_entry_id" json:"rss_entry_id"`
	SourceUri           *string            `db:"source_uri" json:"source_uri"`
	SourcePayload       []byte             `db:"source_payload" json:"source_payload"`
	LegacyID            *string            `db:"legacy_id" json:"legacy_id"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletionRequestedAt pgtype.Timestamptz `db:"deletion_requested_at" json:"deletion_requested_at"`
	TmdbSeriesID        *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
	RssSubscriptionID   pgtype.UUID        `db:"rss_subscription_id" json:"rss_subscription_id"`
}

func (q *Queries) LockAcquisitionForMapping(ctx context.Context, id pgtype.UUID) (LockAcquisitionForMappingRow, error) {
	row := q.db.QueryRow(ctx, lockAcquisitionForMapping, id)
	var i LockAcquisitionForMappingRow
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.SourceKind,
		&i.ReleaseCandidateID,
		&i.RssEntryID,
		&i.SourceUri,
		&i.SourcePayload,
		&i.LegacyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
		&i.TmdbSeriesID,
		&i.RssSubscriptionID,
	)
	return i, err
}

const lockMediaSeries = `-- name: LockMediaSeries :one
SELECT id, tmdb_series_id, title, original_title, media_type, metadata, legacy_id, created_at, updated_at, tmdb_movie_id, release_year
FROM media_series
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockMediaSeries(ctx context.Context, id pgtype.UUID) (MediaSeries, error) {
	row := q.db.QueryRow(ctx, lockMediaSeries, id)
	var i MediaSeries
	err := row.Scan(
		&i.ID,
		&i.TmdbSeriesID,
		&i.Title,
		&i.OriginalTitle,
		&i.MediaType,
		&i.Metadata,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TmdbMovieID,
		&i.ReleaseYear,
	)
	return i, err
}

const markEmbyLibrariesAbsent = `-- name: MarkEmbyLibrariesAbsent :execrows
UPDATE emby_libraries
SET present = false,
    updated_at = now()
WHERE last_scan_run_id <> $1
  AND present
`

func (q *Queries) MarkEmbyLibrariesAbsent(ctx context.Context, scanRunID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmbyLibrariesAbsent, scanRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markEmbyLibraryItemsAbsent = `-- name: MarkEmbyLibraryItemsAbsent :execrows
UPDATE emby_library_items
SET present = false,
    updated_at = now()
WHERE last_scan_run_id <> $1
  AND present
`

func (q *Queries) MarkEmbyLibraryItemsAbsent(ctx context.Context, scanRunID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markEmbyLibraryItemsAbsent, scanRunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextMappingProfileVersion = `-- name: NextMappingProfileVersion :one
SELECT COALESCE(max(version), 0)::integer + 1
FROM episode_mapping_profiles
WHERE series_id = $1
  AND name = $2
`

type NextMappingProfileVersionParams struct {
	SeriesID pgtype.UUID `db:"series_id" json:"series_id"`
	Name     string      `db:"name" json:"name"`
}

func (q *Queries) NextMappingProfileVersion(ctx context.Context, arg NextMappingProfileVersionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextMappingProfileVersion, arg.SeriesID, arg.Name)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const requeueMappingMaterialization = `-- name: RequeueMappingMaterialization :one
UPDATE downloads
SET status = 'completed',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $2
  AND status = 'failed'
  AND failure_stage = 'materialize'
  AND error_code IN (
      'mapping_profile_required',
      'episode_mapping_required',
      'mapping_source_invalid',
      'mapping_source_out_of_range',
      'mapping_context_incomplete',
      'mapping_target_out_of_range',
      'mapping_title_missing'
  )
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type RequeueMappingMaterializationParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueMappingMaterialization(ctx context.Context, arg RequeueMappingMaterializationParams) (Download, error) {
	row := q.db.QueryRow(ctx, requeueMappingMaterialization, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const startEmbyScanRun = `-- name: StartEmbyScanRun :one
UPDATE emby_scan_runs
SET status = 'running',
    started_at = COALESCE(started_at, now()),
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE id = $1
  AND status IN ('queued', 'running')
RETURNING id, operation_id, status, library_count, item_count, error_code, error_message, started_at, completed_at, created_by, created_at, updated_at
`

func (q *Queries) StartEmbyScanRun(ctx context.Context, id pgtype.UUID) (EmbyScanRun, error) {
	row := q.db.QueryRow(ctx, startEmbyScanRun, id)
	var i EmbyScanRun
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Status,
		&i.LibraryCount,
		&i.ItemCount,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const syncMappingScopeSourceFacts = `-- name: SyncMappingScopeSourceFacts :execrows
WITH source_subscription AS (
    SELECT entry.subscription_id
    FROM acquisitions AS source_acquisition
    JOIN rss_entries AS entry ON entry.id = source_acquisition.rss_entry_id
    JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
    WHERE source_acquisition.id = $1
      AND subscription.deleted_at IS NULL
),
source_facts AS (
    SELECT
        acquisition.id AS acquisition_id,
        acquisition.rss_entry_id,
        min(file.source_season)::integer AS source_season,
        min(file.source_episode)::integer AS source_episode
    FROM acquisitions AS acquisition
    LEFT JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
    JOIN downloads AS download ON download.acquisition_id = acquisition.id
    JOIN download_files AS file
      ON file.download_id = download.id
     AND file.selected
     AND file.media_kind = 'video'
    WHERE (
          acquisition.id = $1
          OR entry.subscription_id = (SELECT subscription_id FROM source_subscription)
      )
      AND acquisition.deletion_requested_at IS NULL
      AND download.attempt = (
          SELECT max(candidate.attempt)
          FROM downloads AS candidate
          WHERE candidate.acquisition_id = acquisition.id
            AND EXISTS (
                SELECT 1
                FROM download_files AS candidate_file
                WHERE candidate_file.download_id = candidate.id
                  AND candidate_file.selected
                  AND candidate_file.media_kind = 'video'
            )
      )
    GROUP BY acquisition.id, acquisition.rss_entry_id
    HAVING count(*) = 1
       AND min(file.source_season) IS NOT NULL
       AND min(file.source_episode) IS NOT NULL
),
updated_acquisitions AS (
    UPDATE acquisitions AS acquisition
    SET source_payload = jsonb_set(
            jsonb_set(acquisition.source_payload, '{sourceSeason}', to_jsonb(source_facts.source_season), true),
            '{sourceEpisode}', to_jsonb(source_facts.source_episode), true
        ),
        updated_at = now()
    FROM source_facts
    WHERE acquisition.id = source_facts.acquisition_id
    RETURNING acquisition.rss_entry_id, source_facts.source_season, source_facts.source_episode
)
UPDATE rss_entries AS entry
SET source_season = updated_acquisitions.source_season,
    source_episode = updated_acquisitions.source_episode,
    updated_at = now()
FROM updated_acquisitions
WHERE entry.id = updated_acquisitions.rss_entry_id
`

func (q *Queries) SyncMappingScopeSourceFacts(ctx context.Context, acquisitionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, syncMappingScopeSourceFacts, acquisitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAcquisitionMappingProfile = `-- name: UpdateAcquisitionMappingProfile :one
UPDATE acquisitions
SET mapping_profile_id = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, series_id, mapping_profile_id, source_kind, release_candidate_id, rss_entry_id, source_uri, source_payload, legacy_id, created_by, created_at, updated_at, deletion_requested_at
`

type UpdateAcquisitionMappingProfileParams struct {
	MappingProfileID pgtype.UUID `db:"mapping_profile_id" json:"mapping_profile_id"`
	ID               pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateAcquisitionMappingProfile(ctx context.Context, arg UpdateAcquisitionMappingProfileParams) (Acquisition, error) {
	row := q.db.QueryRow(ctx, updateAcquisitionMappingProfile, arg.MappingProfileID, arg.ID)
	var i Acquisition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.SourceKind,
		&i.ReleaseCandidateID,
		&i.RssEntryID,
		&i.SourceUri,
		&i.SourcePayload,
		&i.LegacyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const updateSelectedFileCoordinateFamily = `-- name: UpdateSelectedFileCoordinateFamily :execrows
WITH source_file AS (
    SELECT selected_file.download_id, selected_file.source_season, selected_file.source_episode
    FROM download_files AS selected_file
    WHERE selected_file.id = $3
      AND selected_file.selected
      AND selected_file.media_kind = 'video'
)
UPDATE download_files AS related
SET source_season = $1,
    source_episode = $2
FROM source_file
WHERE related.download_id = source_file.download_id
  AND related.selected
  AND related.media_kind IN ('video', 'subtitle')
  AND related.source_season IS NOT DISTINCT FROM source_file.source_season
  AND related.source_episode IS NOT DISTINCT FROM source_file.source_episode
  AND (
      related.source_season IS DISTINCT FROM $1
      OR related.source_episode IS DISTINCT FROM $2
  )
`

type UpdateSelectedFileCoordinateFamilyParams struct {
	NewSourceSeason  *int32      `db:"new_source_season" json:"new_source_season"`
	NewSourceEpisode *int32      `db:"new_source_episode" json:"new_source_episode"`
	SourceFileID     pgtype.UUID `db:"source_file_id" json:"source_file_id"`
}

func (q *Queries) UpdateSelectedFileCoordinateFamily(ctx context.Context, arg UpdateSelectedFileCoordinateFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSelectedFileCoordinateFamily, arg.NewSourceSeason, arg.NewSourceEpisode, arg.SourceFileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertEmbyLibrary = `-- name: UpsertEmbyLibrary :one
INSERT INTO emby_libraries (
    id,
    emby_id,
    name,
    collection_type,
    locations,
    present,
    last_scan_run_id,
    last_seen_at,
    upstream_payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    true,
    $6,
    $7,
    $8
)
ON CONFLICT (emby_id) DO UPDATE
SET name = EXCLUDED.name,
    collection_type = EXCLUDED.collection_type,
    locations = EXCLUDED.locations,
    present = true,
    last_scan_run_id = EXCLUDED.last_scan_run_id,
    last_seen_at = EXCLUDED.last_seen_at,
    upstream_payload = EXCLUDED.upstream_payload,
    updated_at = now()
RETURNING id, emby_id, name, collection_type, locations, present, last_scan_run_id, last_seen_at, upstream_payload, created_at, updated_at
`

type UpsertEmbyLibraryParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	EmbyID          string             `db:"emby_id" json:"emby_id"`
	Name            string             `db:"name" json:"name"`
	CollectionType  *string            `db:"collection_type" json:"collection_type"`
	Locations       []string           `db:"locations" json:"locations"`
	LastScanRunID   pgtype.UUID        `db:"last_scan_run_id" json:"last_scan_run_id"`
	LastSeenAt      pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
}

func (q *Queries) UpsertEmbyLibrary(ctx context.Context, arg UpsertEmbyLibraryParams) (EmbyLibrary, error) {
	row := q.db.QueryRow(ctx, upsertEmbyLibrary,
		arg.ID,
		arg.EmbyID,
		arg.Name,
		arg.CollectionType,
		arg.Locations,
		arg.LastScanRunID,
		arg.LastSeenAt,
		arg.UpstreamPayload,
	)
	var i EmbyLibrary
	err := row.Scan(
		&i.ID,
		&i.EmbyID,
		&i.Name,
		&i.CollectionType,
		&i.Locations,
		&i.Present,
		&i.LastScanRunID,
		&i.LastSeenAt,
		&i.UpstreamPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEmbyLibraryItem = `-- name: UpsertEmbyLibraryItem :one
INSERT INTO emby_library_items (
    id,
    emby_id,
    library_id,
    parent_emby_id,
    item_type,
    name,
    file_path,
    provider_ids,
    season_number,
    episode_number,
    present,
    last_scan_run_id,
    last_seen_at,
    upstream_payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    true,
    $11,
    $12,
    $13
)
ON CONFLICT (emby_id) DO UPDATE
SET library_id = EXCLUDED.library_id,
    parent_emby_id = EXCLUDED.parent_emby_id,
    item_type = EXCLUDED.item_type,
    name = EXCLUDED.name,
    file_path = EXCLUDED.file_path,
    provider_ids = EXCLUDED.provider_ids,
    season_number = EXCLUDED.season_number,
    episode_number = EXCLUDED.episode_number,
    present = true,
    last_scan_run_id = EXCLUDED.last_scan_run_id,
    last_seen_at = EXCLUDED.last_seen_at,
    upstream_payload = EXCLUDED.upstream_payload,
    updated_at = now()
RETURNING id, emby_id, library_id, parent_emby_id, item_type, name, file_path, provider_ids, season_number, episode_number, present, last_scan_run_id, last_seen_at, upstream_payload, created_at, updated_at
`

type UpsertEmbyLibraryItemParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	EmbyID          string             `db:"emby_id" json:"emby_id"`
	LibraryID       pgtype.UUID        `db:"library_id" json:"library_id"`
	ParentEmbyID    *string            `db:"parent_emby_id" json:"parent_emby_id"`
	ItemType        string             `db:"item_type" json:"item_type"`
	Name            string             `db:"name" json:"name"`
	FilePath        *string            `db:"file_path" json:"file_path"`
	ProviderIds     []byte             `db:"provider_ids" json:"provider_ids"`
	SeasonNumber    *int32             `db:"season_number" json:"season_number"`
	EpisodeNumber   *int32             `db:"episode_number" json:"episode_number"`
	LastScanRunID   pgtype.UUID        `db:"last_scan_run_id" json:"last_scan_run_id"`
	LastSeenAt      pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
}

func (q *Queries) UpsertEmbyLibraryItem(ctx context.Context, arg UpsertEmbyLibraryItemParams) (EmbyLibraryItem, error) {
	row := q.db.QueryRow(ctx, upsertEmbyLibraryItem,
		arg.ID,
		arg.EmbyID,
		arg.LibraryID,
		arg.ParentEmbyID,
		arg.ItemType,
		arg.Name,
		arg.FilePath,
		arg.ProviderIds,
		arg.SeasonNumber,
		arg.EpisodeNumber,
		arg.LastScanRunID,
		arg.LastSeenAt,
		arg.UpstreamPayload,
	)
	var i EmbyLibraryItem
	err := row.Scan(
		&i.ID,
		&i.EmbyID,
		&i.LibraryID,
		&i.ParentEmbyID,
		&i.ItemType,
		&i.Name,
		&i.FilePath,
		&i.ProviderIds,
		&i.SeasonNumber,
		&i.EpisodeNumber,
		&i.Present,
		&i.LastScanRunID,
		&i.LastSeenAt,
		&i.UpstreamPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTMDbEpisode = `-- name: UpsertTMDbEpisode :one
INSERT INTO media_episodes (
    id,
    season_id,
    tmdb_episode_id,
    episode_number,
    title,
    air_date,
    upstream_payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
ON CONFLICT (season_id, episode_number) DO UPDATE
SET tmdb_episode_id = EXCLUDED.tmdb_episode_id,
    title = EXCLUDED.title,
    air_date = EXCLUDED.air_date,
    upstream_payload = EXCLUDED.upstream_payload,
    updated_at = now()
RETURNING id, season_id, tmdb_episode_id, episode_number, title, air_date, upstream_payload, created_at, updated_at
`

type UpsertTMDbEpisodeParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	SeasonID        pgtype.UUID `db:"season_id" json:"season_id"`
	TmdbEpisodeID   *int64      `db:"tmdb_episode_id" json:"tmdb_episode_id"`
	EpisodeNumber   int32       `db:"episode_number" json:"episode_number"`
	Title           string      `db:"title" json:"title"`
	AirDate         pgtype.Date `db:"air_date" json:"air_date"`
	UpstreamPayload []byte      `db:"upstream_payload" json:"upstream_payload"`
}

func (q *Queries) UpsertTMDbEpisode(ctx context.Context, arg UpsertTMDbEpisodeParams) (MediaEpisode, error) {
	row := q.db.QueryRow(ctx, upsertTMDbEpisode,
		arg.ID,
		arg.SeasonID,
		arg.TmdbEpisodeID,
		arg.EpisodeNumber,
		arg.Title,
		arg.AirDate,
		arg.UpstreamPayload,
	)
	var i MediaEpisode
	err := row.Scan(
		&i.ID,
		&i.SeasonID,
		&i.TmdbEpisodeID,
		&i.EpisodeNumber,
		&i.Title,
		&i.AirDate,
		&i.UpstreamPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTMDbSeason = `-- name: UpsertTMDbSeason :one
INSERT INTO tmdb_seasons (
    id,
    series_id,
    tmdb_season_id,
    season_number,
    name,
    episode_count,
    fetched_at,
    upstream_payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (series_id, season_number) DO UPDATE
SET tmdb_season_id = EXCLUDED.tmdb_season_id,
    name = EXCLUDED.name,
    episode_count = EXCLUDED.episode_count,
    fetched_at = EXCLUDED.fetched_at,
    upstream_payload = EXCLUDED.upstream_payload,
    updated_at = now()
RETURNING id, series_id, tmdb_season_id, season_number, name, episode_count, fetched_at, upstream_payload, created_at, updated_at
`

type UpsertTMDbSeasonParams struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SeriesID        pgtype.UUID        `db:"series_id" json:"series_id"`
	TmdbSeasonID    *int64             `db:"tmdb_season_id" json:"tmdb_season_id"`
	SeasonNumber    int32              `db:"season_number" json:"season_number"`
	Name            *string            `db:"name" json:"name"`
	EpisodeCount    int32              `db:"episode_count" json:"episode_count"`
	FetchedAt       pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
}

func (q *Queries) UpsertTMDbSeason(ctx context.Context, arg UpsertTMDbSeasonParams) (TmdbSeason, error) {
	row := q.db.QueryRow(ctx, upsertTMDbSeason,
		arg.ID,
		arg.SeriesID,
		arg.TmdbSeasonID,
		arg.SeasonNumber,
		arg.Name,
		arg.EpisodeCount,
		arg.FetchedAt,
		arg.UpstreamPayload,
	)
	var i TmdbSeason
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.TmdbSeasonID,
		&i.SeasonNumber,
		&i.Name,
		&i.EpisodeCount,
		&i.FetchedAt,
		&i.UpstreamPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTMDbSeries = `-- name: UpsertTMDbSeries :one
INSERT INTO media_series (
    id,
    tmdb_series_id,
    title,
    original_title,
    metadata,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    now()
)
ON CONFLICT (tmdb_series_id) DO UPDATE
SET title = EXCLUDED.title,
    original_title = EXCLUDED.original_title,
    metadata = EXCLUDED.metadata,
    updated_at = now()
RETURNING id, tmdb_series_id, title, original_title, media_type, metadata, legacy_id, created_at, updated_at, tmdb_movie_id, release_year
`

type UpsertTMDbSeriesParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	TmdbSeriesID  *int64      `db:"tmdb_series_id" json:"tmdb_series_id"`
	Title         string      `db:"title" json:"title"`
	OriginalTitle *string     `db:"original_title" json:"original_title"`
	Metadata      []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertTMDbSeries(ctx context.Context, arg UpsertTMDbSeriesParams) (MediaSeries, error) {
	row := q.db.QueryRow(ctx, upsertTMDbSeries,
		arg.ID,
		arg.TmdbSeriesID,
		arg.Title,
		arg.OriginalTitle,
		arg.Metadata,
	)
	var i MediaSeries
	err := row.Scan(
		&i.ID,
		&i.TmdbSeriesID,
		&i.Title,
		&i.OriginalTitle,
		&i.MediaType,
		&i.Metadata,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TmdbMovieID,
		&i.ReleaseYear,
	)
	return i, err
}
