// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAppSecret = `-- name: DeleteAppSecret :execrows
DELETE FROM app_secrets
WHERE name = $1
`

func (q *Queries) DeleteAppSecret(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppSecret, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAppSecret = `-- name: GetAppSecret :one
SELECT name, ciphertext, nonce, masked_hint, version, updated_by, created_at, updated_at
FROM app_secrets
WHERE name = $1
`

func (q *Queries) GetAppSecret(ctx context.Context, name string) (AppSecret, error) {
	row := q.db.QueryRow(ctx, getAppSecret, name)
	var i AppSecret
	err := row.Scan(
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.MaskedHint,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppSetting = `-- name: GetAppSetting :one
SELECT name, value, version, updated_by, created_at, updated_at
FROM app_settings
WHERE name = $1
`

func (q *Queries) GetAppSetting(ctx context.Context, name string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getAppSetting, name)
	var i AppSetting
	err := row.Scan(
		&i.Name,
		&i.Value,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppSecrets = `-- name: ListAppSecrets :many
SELECT name, ciphertext, nonce, masked_hint, version, updated_by, created_at, updated_at
FROM app_secrets
ORDER BY name
`

func (q *Queries) ListAppSecrets(ctx context.Context) ([]AppSecret, error) {
	rows, err := q.db.Query(ctx, listAppSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppSecret{}
	for rows.Next() {
		var i AppSecret
		if err := rows.Scan(
			&i.Name,
			&i.Ciphertext,
			&i.Nonce,
			&i.MaskedHint,
			&i.Version,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnectivityTestResults = `-- name: ListConnectivityTestResults :many
SELECT target, success, code, message, tested_at
FROM connectivity_test_results
ORDER BY target
`

func (q *Queries) ListConnectivityTestResults(ctx context.Context) ([]ConnectivityTestResult, error) {
	rows, err := q.db.Query(ctx, listConnectivityTestResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConnectivityTestResult{}
	for rows.Next() {
		var i ConnectivityTestResult
		if err := rows.Scan(
			&i.Target,
			&i.Success,
			&i.Code,
			&i.Message,
			&i.TestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceDefaultTranscodeProfile = `-- name: ReplaceDefaultTranscodeProfile :one
WITH deactivated AS (
    UPDATE transcode_profiles
    SET active = false,
        is_default = false
    WHERE active
    RETURNING id
), next_version AS (
    SELECT COALESCE(max(version), 0) + 1 AS version
    FROM transcode_profiles
    WHERE name = $2
)
INSERT INTO transcode_profiles (
    id,
    name,
    version,
    active,
    is_default,
    video_codec,
    encoder,
    container,
    file_extension,
    quality_mode,
    quality_value,
    audio_policy,
    audio_codec,
    preset,
    pixel_format,
    thread_count,
    max_concurrency,
    created_by
)
SELECT
    $1,
    $2,
    next_version.version,
    true,
    true,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::bigint::numeric / 1000,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
FROM next_version
CROSS JOIN (SELECT count(*) FROM deactivated) AS applied
RETURNING id, name, version, active, is_default, video_codec, encoder, container, file_extension, quality_mode, quality_value, audio_policy, audio_codec, preset, pixel_format, thread_count, max_concurrency, created_at, created_by
`

type ReplaceDefaultTranscodeProfileParams struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	Name              string      `db:"name" json:"name"`
	VideoCodec        string      `db:"video_codec" json:"video_codec"`
	Encoder           string      `db:"encoder" json:"encoder"`
	Container         string      `db:"container" json:"container"`
	FileExtension     string      `db:"file_extension" json:"file_extension"`
	QualityMode       string      `db:"quality_mode" json:"quality_mode"`
	QualityValueMilli int64       `db:"quality_value_milli" json:"quality_value_milli"`
	AudioPolicy       string      `db:"audio_policy" json:"audio_policy"`
	AudioCodec        *string     `db:"audio_codec" json:"audio_codec"`
	Preset            string      `db:"preset" json:"preset"`
	PixelFormat       string      `db:"pixel_format" json:"pixel_format"`
	ThreadCount       int32       `db:"thread_count" json:"thread_count"`
	MaxConcurrency    int32       `db:"max_concurrency" json:"max_concurrency"`
	CreatedBy         pgtype.UUID `db:"created_by" json:"created_by"`
}

func (q *Queries) ReplaceDefaultTranscodeProfile(ctx context.Context, arg ReplaceDefaultTranscodeProfileParams) (TranscodeProfile, error) {
	row := q.db.QueryRow(ctx, replaceDefaultTranscodeProfile,
		arg.ID,
		arg.Name,
		arg.VideoCodec,
		arg.Encoder,
		arg.Container,
		arg.FileExtension,
		arg.QualityMode,
		arg.QualityValueMilli,
		arg.AudioPolicy,
		arg.AudioCodec,
		arg.Preset,
		arg.PixelFormat,
		arg.ThreadCount,
		arg.MaxConcurrency,
		arg.CreatedBy,
	)
	var i TranscodeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Active,
		&i.IsDefault,
		&i.VideoCodec,
		&i.Encoder,
		&i.Container,
		&i.FileExtension,
		&i.QualityMode,
		&i.QualityValue,
		&i.AudioPolicy,
		&i.AudioCodec,
		&i.Preset,
		&i.PixelFormat,
		&i.ThreadCount,
		&i.MaxConcurrency,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const saveAppSetting = `-- name: SaveAppSetting :one
WITH updated AS (
    UPDATE app_settings AS current_setting
    SET value = $1,
        version = current_setting.version + 1,
        updated_by = $2,
        updated_at = now()
    WHERE current_setting.name = $3
      AND current_setting.version = $4
      AND $4::integer > 0
    RETURNING current_setting.name, current_setting.value, current_setting.version, current_setting.updated_by, current_setting.created_at, current_setting.updated_at
), inserted AS (
    INSERT INTO app_settings (
        name,
        value,
        version,
        updated_by
    )
    SELECT
        $3,
        $1,
        1,
        $2
    WHERE $4::integer = 0
      AND NOT EXISTS (
          SELECT 1
          FROM app_settings AS current_setting
          WHERE current_setting.name = $3
      )
    ON CONFLICT (name) DO NOTHING
    RETURNING name, value, version, updated_by, created_at, updated_at
)
SELECT name, value, version, updated_by, created_at, updated_at FROM updated
UNION ALL
SELECT name, value, version, updated_by, created_at, updated_at FROM inserted
LIMIT 1
`

type SaveAppSettingParams struct {
	Value           []byte      `db:"value" json:"value"`
	UpdatedBy       pgtype.UUID `db:"updated_by" json:"updated_by"`
	Name            string      `db:"name" json:"name"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

type SaveAppSettingRow struct {
	Name      string             `db:"name" json:"name"`
	Value     []byte             `db:"value" json:"value"`
	Version   int32              `db:"version" json:"version"`
	UpdatedBy pgtype.UUID        `db:"updated_by" json:"updated_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SaveAppSetting(ctx context.Context, arg SaveAppSettingParams) (SaveAppSettingRow, error) {
	row := q.db.QueryRow(ctx, saveAppSetting,
		arg.Value,
		arg.UpdatedBy,
		arg.Name,
		arg.ExpectedVersion,
	)
	var i SaveAppSettingRow
	err := row.Scan(
		&i.Name,
		&i.Value,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppSecret = `-- name: UpsertAppSecret :one
INSERT INTO app_secrets (
    name,
    ciphertext,
    nonce,
    masked_hint,
    updated_by
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (name) DO UPDATE
SET ciphertext = EXCLUDED.ciphertext,
    nonce = EXCLUDED.nonce,
    masked_hint = EXCLUDED.masked_hint,
    version = app_secrets.version + 1,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING name, ciphertext, nonce, masked_hint, version, updated_by, created_at, updated_at
`

type UpsertAppSecretParams struct {
	Name       string      `db:"name" json:"name"`
	Ciphertext []byte      `db:"ciphertext" json:"ciphertext"`
	Nonce      []byte      `db:"nonce" json:"nonce"`
	MaskedHint string      `db:"masked_hint" json:"masked_hint"`
	UpdatedBy  pgtype.UUID `db:"updated_by" json:"updated_by"`
}

func (q *Queries) UpsertAppSecret(ctx context.Context, arg UpsertAppSecretParams) (AppSecret, error) {
	row := q.db.QueryRow(ctx, upsertAppSecret,
		arg.Name,
		arg.Ciphertext,
		arg.Nonce,
		arg.MaskedHint,
		arg.UpdatedBy,
	)
	var i AppSecret
	err := row.Scan(
		&i.Name,
		&i.Ciphertext,
		&i.Nonce,
		&i.MaskedHint,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConnectivityTestResult = `-- name: UpsertConnectivityTestResult :one
INSERT INTO connectivity_test_results (
    target,
    success,
    code,
    message,
    tested_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (target) DO UPDATE
SET success = EXCLUDED.success,
    code = EXCLUDED.code,
    message = EXCLUDED.message,
    tested_at = EXCLUDED.tested_at
RETURNING target, success, code, message, tested_at
`

type UpsertConnectivityTestResultParams struct {
	Target   string             `db:"target" json:"target"`
	Success  bool               `db:"success" json:"success"`
	Code     string             `db:"code" json:"code"`
	Message  string             `db:"message" json:"message"`
	TestedAt pgtype.Timestamptz `db:"tested_at" json:"tested_at"`
}

func (q *Queries) UpsertConnectivityTestResult(ctx context.Context, arg UpsertConnectivityTestResultParams) (ConnectivityTestResult, error) {
	row := q.db.QueryRow(ctx, upsertConnectivityTestResult,
		arg.Target,
		arg.Success,
		arg.Code,
		arg.Message,
		arg.TestedAt,
	)
	var i ConnectivityTestResult
	err := row.Scan(
		&i.Target,
		&i.Success,
		&i.Code,
		&i.Message,
		&i.TestedAt,
	)
	return i, err
}
