// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deletions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAcquisitionDownloadsForDeletion = `-- name: CancelAcquisitionDownloadsForDeletion :execrows
UPDATE downloads
SET status = 'cancelled',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE acquisition_id = $1
  AND deleted_at IS NULL
  AND status IN ('enqueue_pending', 'downloading', 'completed', 'selecting_files')
`

func (q *Queries) CancelAcquisitionDownloadsForDeletion(ctx context.Context, acquisitionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelAcquisitionDownloadsForDeletion, acquisitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cancelAcquisitionTasksForDeletion = `-- name: CancelAcquisitionTasksForDeletion :execrows
UPDATE episode_tasks
SET state = 'cancelled',
    video_state = CASE WHEN video_state = 'video_ready' THEN video_state ELSE 'cancelled' END,
    subtitle_state = CASE WHEN subtitle_state = 'ass_ready' THEN subtitle_state ELSE 'cancelled' END,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE acquisition_id = $1
  AND state NOT IN ('imported', 'cancelled')
`

func (q *Queries) CancelAcquisitionTasksForDeletion(ctx context.Context, acquisitionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelAcquisitionTasksForDeletion, acquisitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countAcquisitionDeletionActiveOperations = `-- name: CountAcquisitionDeletionActiveOperations :one
SELECT count(*)::bigint
FROM operations AS operation
WHERE operation.id <> $1
  AND (
      operation.status = 'running'
      OR (operation.status = 'queued' AND operation.cancel_requested_at IS NULL)
  )
  AND (
      (operation.resource_type = 'acquisition' AND operation.resource_id = $2)
      OR (
          operation.resource_type = 'episode_task'
          AND operation.resource_id IN (
              SELECT task.id
              FROM episode_tasks AS task
              WHERE task.acquisition_id = $2
          )
      )
      OR (
          operation.resource_type = 'download'
          AND operation.resource_id IN (
              SELECT download.id
              FROM downloads AS download
              WHERE download.acquisition_id = $2
          )
      )
  )
`

type CountAcquisitionDeletionActiveOperationsParams struct {
	OperationID   pgtype.UUID `db:"operation_id" json:"operation_id"`
	AcquisitionID pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
}

func (q *Queries) CountAcquisitionDeletionActiveOperations(ctx context.Context, arg CountAcquisitionDeletionActiveOperationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAcquisitionDeletionActiveOperations, arg.OperationID, arg.AcquisitionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSubscriptionDeletionActiveOperations = `-- name: CountSubscriptionDeletionActiveOperations :one
SELECT count(*)::bigint
FROM operations AS operation
WHERE operation.id <> $1
  AND operation.resource_type = 'rss_subscription'
  AND operation.resource_id = $2
  AND (
      operation.status = 'running'
      OR (operation.status = 'queued' AND operation.cancel_requested_at IS NULL)
  )
`

type CountSubscriptionDeletionActiveOperationsParams struct {
	OperationID    pgtype.UUID `db:"operation_id" json:"operation_id"`
	SubscriptionID pgtype.UUID `db:"subscription_id" json:"subscription_id"`
}

func (q *Queries) CountSubscriptionDeletionActiveOperations(ctx context.Context, arg CountSubscriptionDeletionActiveOperationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptionDeletionActiveOperations, arg.OperationID, arg.SubscriptionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAcquisitionWorkflow = `-- name: DeleteAcquisitionWorkflow :execrows
DELETE FROM acquisitions
WHERE id = $1
  AND deletion_requested_at IS NOT NULL
`

func (q *Queries) DeleteAcquisitionWorkflow(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAcquisitionWorkflow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteArchivedRSSSubscription = `-- name: DeleteArchivedRSSSubscription :execrows
DELETE FROM rss_subscriptions AS subscription
WHERE subscription.id = $1
  AND subscription.deleted_at IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM acquisitions AS acquisition
      JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
      WHERE entry.subscription_id = subscription.id
  )
`

func (q *Queries) DeleteArchivedRSSSubscription(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArchivedRSSSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteArtifactSetsForAcquisition = `-- name: DeleteArtifactSetsForAcquisition :execrows
DELETE FROM artifact_sets
WHERE task_id IN (
    SELECT id
    FROM episode_tasks
    WHERE acquisition_id = $1
)
`

func (q *Queries) DeleteArtifactSetsForAcquisition(ctx context.Context, acquisitionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteArtifactSetsForAcquisition, acquisitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEpisodeTasksForAcquisition = `-- name: DeleteEpisodeTasksForAcquisition :execrows
DELETE FROM episode_tasks
WHERE acquisition_id = $1
`

func (q *Queries) DeleteEpisodeTasksForAcquisition(ctx context.Context, acquisitionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEpisodeTasksForAcquisition, acquisitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMediaArtifactsForAcquisition = `-- name: DeleteMediaArtifactsForAcquisition :execrows
DELETE FROM media_artifacts
WHERE task_id IN (
    SELECT id
    FROM episode_tasks
    WHERE acquisition_id = $1
)
`

func (q *Queries) DeleteMediaArtifactsForAcquisition(ctx context.Context, acquisitionID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMediaArtifactsForAcquisition, acquisitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDownloadAcquisitionDeletionTarget = `-- name: GetDownloadAcquisitionDeletionTarget :one
SELECT acquisition_id
FROM downloads
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDownloadAcquisitionDeletionTarget(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDownloadAcquisitionDeletionTarget, id)
	var acquisition_id pgtype.UUID
	err := row.Scan(&acquisition_id)
	return acquisition_id, err
}

const listAcquisitionDeletionArtifactPaths = `-- name: ListAcquisitionDeletionArtifactPaths :many
SELECT artifact.file_path
FROM media_artifacts AS artifact
JOIN episode_tasks AS task ON task.id = artifact.task_id
WHERE task.acquisition_id = $1
ORDER BY artifact.id
`

func (q *Queries) ListAcquisitionDeletionArtifactPaths(ctx context.Context, acquisitionID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAcquisitionDeletionArtifactPaths, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcquisitionDeletionDownloads = `-- name: ListAcquisitionDeletionDownloads :many
SELECT
    download.id,
    download.torrent_hash,
    download.save_path,
    EXISTS (
        SELECT 1
        FROM downloads AS other
        JOIN acquisitions AS other_acquisition ON other_acquisition.id = other.acquisition_id
        WHERE other.acquisition_id <> download.acquisition_id
          AND other.deleted_at IS NULL
          AND other_acquisition.deletion_requested_at IS NULL
          AND (
              other_acquisition.source_kind <> 'rss'
              OR EXISTS (
                  SELECT 1
                  FROM rss_entries AS other_entry
                  JOIN rss_subscriptions AS other_subscription ON other_subscription.id = other_entry.subscription_id
                  WHERE other_entry.id = other_acquisition.rss_entry_id
                    AND other_subscription.deleted_at IS NULL
              )
          )
          AND download.torrent_hash IS NOT NULL
          AND lower(other.torrent_hash) = lower(download.torrent_hash)
    ) AS preserve_torrent,
    EXISTS (
        SELECT 1
        FROM downloads AS other
        JOIN acquisitions AS other_acquisition ON other_acquisition.id = other.acquisition_id
        WHERE other.acquisition_id <> download.acquisition_id
          AND other.deleted_at IS NULL
          AND other_acquisition.deletion_requested_at IS NULL
          AND (
              other_acquisition.source_kind <> 'rss'
              OR EXISTS (
                  SELECT 1
                  FROM rss_entries AS other_entry
                  JOIN rss_subscriptions AS other_subscription ON other_subscription.id = other_entry.subscription_id
                  WHERE other_entry.id = other_acquisition.rss_entry_id
                    AND other_subscription.deleted_at IS NULL
              )
          )
          AND download.save_path IS NOT NULL
          AND lower(btrim(other.save_path)) = lower(btrim(download.save_path))
    ) AS preserve_path
FROM downloads AS download
WHERE download.acquisition_id = $1
ORDER BY download.attempt, download.id
`

type ListAcquisitionDeletionDownloadsRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	TorrentHash     *string     `db:"torrent_hash" json:"torrent_hash"`
	SavePath        *string     `db:"save_path" json:"save_path"`
	PreserveTorrent bool        `db:"preserve_torrent" json:"preserve_torrent"`
	PreservePath    bool        `db:"preserve_path" json:"preserve_path"`
}

func (q *Queries) ListAcquisitionDeletionDownloads(ctx context.Context, acquisitionID pgtype.UUID) ([]ListAcquisitionDeletionDownloadsRow, error) {
	rows, err := q.db.Query(ctx, listAcquisitionDeletionDownloads, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcquisitionDeletionDownloadsRow{}
	for rows.Next() {
		var i ListAcquisitionDeletionDownloadsRow
		if err := rows.Scan(
			&i.ID,
			&i.TorrentHash,
			&i.SavePath,
			&i.PreserveTorrent,
			&i.PreservePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcquisitionDeletionLibraryFiles = `-- name: ListAcquisitionDeletionLibraryFiles :many
WITH deletion_imports AS (
    SELECT imported.id, imported.destination_video_path AS file_path
    FROM imports AS imported
    JOIN episode_tasks AS task ON task.id = imported.task_id
    WHERE task.acquisition_id = $1
      AND imported.status = 'succeeded'
      AND imported.destination_video_path IS NOT NULL
    UNION ALL
    SELECT imported.id, imported.destination_subtitle_path AS file_path
    FROM imports AS imported
    JOIN episode_tasks AS task ON task.id = imported.task_id
    WHERE task.acquisition_id = $1
      AND imported.status = 'succeeded'
      AND imported.destination_subtitle_path IS NOT NULL
)
SELECT
    deletion_import.file_path::text AS file_path,
    EXISTS (
        SELECT 1
        FROM imports AS other_import
        JOIN episode_tasks AS other_task ON other_task.id = other_import.task_id
        JOIN acquisitions AS other_acquisition ON other_acquisition.id = other_task.acquisition_id
        WHERE other_acquisition.id <> $1
          AND other_acquisition.deletion_requested_at IS NULL
          AND other_import.status = 'succeeded'
          AND (
              other_import.destination_video_path = deletion_import.file_path
              OR other_import.destination_subtitle_path = deletion_import.file_path
          )
    ) AS preserve
FROM deletion_imports AS deletion_import
ORDER BY deletion_import.file_path, deletion_import.id
`

type ListAcquisitionDeletionLibraryFilesRow struct {
	FilePath string `db:"file_path" json:"file_path"`
	Preserve bool   `db:"preserve" json:"preserve"`
}

func (q *Queries) ListAcquisitionDeletionLibraryFiles(ctx context.Context, acquisitionID pgtype.UUID) ([]ListAcquisitionDeletionLibraryFilesRow, error) {
	rows, err := q.db.Query(ctx, listAcquisitionDeletionLibraryFiles, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcquisitionDeletionLibraryFilesRow{}
	for rows.Next() {
		var i ListAcquisitionDeletionLibraryFilesRow
		if err := rows.Scan(&i.FilePath, &i.Preserve); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcquisitionDeletionTaskIDs = `-- name: ListAcquisitionDeletionTaskIDs :many
SELECT id
FROM episode_tasks
WHERE acquisition_id = $1
ORDER BY id
`

func (q *Queries) ListAcquisitionDeletionTaskIDs(ctx context.Context, acquisitionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listAcquisitionDeletionTaskIDs, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionDeletionAcquisitionIDs = `-- name: ListSubscriptionDeletionAcquisitionIDs :many
SELECT acquisition.id
FROM acquisitions AS acquisition
JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
WHERE entry.subscription_id = $1
ORDER BY acquisition.id
`

func (q *Queries) ListSubscriptionDeletionAcquisitionIDs(ctx context.Context, subscriptionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSubscriptionDeletionAcquisitionIDs, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAcquisitionForDeletion = `-- name: LockAcquisitionForDeletion :one
SELECT id, deletion_requested_at
FROM acquisitions
WHERE id = $1
FOR UPDATE
`

type LockAcquisitionForDeletionRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	DeletionRequestedAt pgtype.Timestamptz `db:"deletion_requested_at" json:"deletion_requested_at"`
}

func (q *Queries) LockAcquisitionForDeletion(ctx context.Context, id pgtype.UUID) (LockAcquisitionForDeletionRow, error) {
	row := q.db.QueryRow(ctx, lockAcquisitionForDeletion, id)
	var i LockAcquisitionForDeletionRow
	err := row.Scan(&i.ID, &i.DeletionRequestedAt)
	return i, err
}

const lockDownloadAcquisitionDeletionTarget = `-- name: LockDownloadAcquisitionDeletionTarget :one
SELECT id, acquisition_id, version
FROM downloads
WHERE id = $1
  AND acquisition_id = $2
  AND deleted_at IS NULL
FOR UPDATE
`

type LockDownloadAcquisitionDeletionTargetParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	AcquisitionID pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
}

type LockDownloadAcquisitionDeletionTargetRow struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	AcquisitionID pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
	Version       int32       `db:"version" json:"version"`
}

func (q *Queries) LockDownloadAcquisitionDeletionTarget(ctx context.Context, arg LockDownloadAcquisitionDeletionTargetParams) (LockDownloadAcquisitionDeletionTargetRow, error) {
	row := q.db.QueryRow(ctx, lockDownloadAcquisitionDeletionTarget, arg.ID, arg.AcquisitionID)
	var i LockDownloadAcquisitionDeletionTargetRow
	err := row.Scan(&i.ID, &i.AcquisitionID, &i.Version)
	return i, err
}

const markAcquisitionDeletionRequested = `-- name: MarkAcquisitionDeletionRequested :one
UPDATE acquisitions
SET deletion_requested_at = COALESCE(deletion_requested_at, now()),
    updated_at = now()
WHERE id = $1
  AND deletion_requested_at IS NULL
RETURNING id, series_id, mapping_profile_id, source_kind, release_candidate_id, rss_entry_id, source_uri, source_payload, legacy_id, created_by, created_at, updated_at, deletion_requested_at
`

func (q *Queries) MarkAcquisitionDeletionRequested(ctx context.Context, id pgtype.UUID) (Acquisition, error) {
	row := q.db.QueryRow(ctx, markAcquisitionDeletionRequested, id)
	var i Acquisition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.SourceKind,
		&i.ReleaseCandidateID,
		&i.RssEntryID,
		&i.SourceUri,
		&i.SourcePayload,
		&i.LegacyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const requestAcquisitionOperationCancellations = `-- name: RequestAcquisitionOperationCancellations :execrows
UPDATE operations AS operation
SET cancel_requested_at = COALESCE(operation.cancel_requested_at, now()),
    updated_at = now()
WHERE operation.status IN ('queued', 'running')
  AND operation.kind <> 'acquisition.delete'
  AND operation.id <> $1
  AND (
      (operation.resource_type = 'acquisition' AND operation.resource_id = $2)
      OR (
          operation.resource_type = 'episode_task'
          AND operation.resource_id IN (
              SELECT task.id
              FROM episode_tasks AS task
              WHERE task.acquisition_id = $2
          )
      )
      OR (
          operation.resource_type = 'download'
          AND operation.resource_id IN (
              SELECT download.id
              FROM downloads AS download
              WHERE download.acquisition_id = $2
          )
      )
  )
`

type RequestAcquisitionOperationCancellationsParams struct {
	ExcludedOperationID pgtype.UUID `db:"excluded_operation_id" json:"excluded_operation_id"`
	AcquisitionID       pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
}

func (q *Queries) RequestAcquisitionOperationCancellations(ctx context.Context, arg RequestAcquisitionOperationCancellationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, requestAcquisitionOperationCancellations, arg.ExcludedOperationID, arg.AcquisitionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
