// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelDownloadIfActive = `-- name: CancelDownloadIfActive :one
UPDATE downloads
SET status = 'cancelled',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status IN ('enqueue_pending', 'file_resolution_pending', 'downloading', 'completed', 'selecting_files')
  AND version = $2
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type CancelDownloadIfActiveParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) CancelDownloadIfActive(ctx context.Context, arg CancelDownloadIfActiveParams) (Download, error) {
	row := q.db.QueryRow(ctx, cancelDownloadIfActive, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const countBlockingTasksForDownload = `-- name: CountBlockingTasksForDownload :one
SELECT count(*)::bigint
FROM episode_tasks AS task
JOIN download_files AS source_file ON source_file.id = task.source_video_file_id
WHERE source_file.download_id = $1
  AND task.state NOT IN ('failed', 'cancelled', 'rejected', 'imported')
`

func (q *Queries) CountBlockingTasksForDownload(ctx context.Context, downloadID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBlockingTasksForDownload, downloadID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createDownloadFile = `-- name: CreateDownloadFile :one
INSERT INTO download_files (
    id,
    download_id,
    file_index,
    relative_path,
    size_bytes,
    media_kind,
    selected,
    source_season,
    source_episode,
    source_episode_fraction_hundredths,
    language
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING id, download_id, file_index, relative_path, size_bytes, media_kind, selected, source_season, source_episode, language, created_at, updated_at, source_episode_fraction_hundredths
`

type CreateDownloadFileParams struct {
	ID                              pgtype.UUID `db:"id" json:"id"`
	DownloadID                      pgtype.UUID `db:"download_id" json:"download_id"`
	FileIndex                       int32       `db:"file_index" json:"file_index"`
	RelativePath                    string      `db:"relative_path" json:"relative_path"`
	SizeBytes                       int64       `db:"size_bytes" json:"size_bytes"`
	MediaKind                       string      `db:"media_kind" json:"media_kind"`
	Selected                        bool        `db:"selected" json:"selected"`
	SourceSeason                    *int32      `db:"source_season" json:"source_season"`
	SourceEpisode                   *int32      `db:"source_episode" json:"source_episode"`
	SourceEpisodeFractionHundredths int32       `db:"source_episode_fraction_hundredths" json:"source_episode_fraction_hundredths"`
	Language                        *string     `db:"language" json:"language"`
}

func (q *Queries) CreateDownloadFile(ctx context.Context, arg CreateDownloadFileParams) (DownloadFile, error) {
	row := q.db.QueryRow(ctx, createDownloadFile,
		arg.ID,
		arg.DownloadID,
		arg.FileIndex,
		arg.RelativePath,
		arg.SizeBytes,
		arg.MediaKind,
		arg.Selected,
		arg.SourceSeason,
		arg.SourceEpisode,
		arg.SourceEpisodeFractionHundredths,
		arg.Language,
	)
	var i DownloadFile
	err := row.Scan(
		&i.ID,
		&i.DownloadID,
		&i.FileIndex,
		&i.RelativePath,
		&i.SizeBytes,
		&i.MediaKind,
		&i.Selected,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceEpisodeFractionHundredths,
	)
	return i, err
}

const deleteDownloadFilesByDownloadID = `-- name: DeleteDownloadFilesByDownloadID :exec
DELETE FROM download_files
WHERE download_id = $1
`

func (q *Queries) DeleteDownloadFilesByDownloadID(ctx context.Context, downloadID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDownloadFilesByDownloadID, downloadID)
	return err
}

const getDownloadEnqueueCommand = `-- name: GetDownloadEnqueueCommand :one
SELECT
    d.id,
    d.acquisition_id,
    d.status,
    d.torrent_hash,
    d.file_resolution_source,
    COALESCE(
        CASE a.source_kind
            WHEN 'search' THEN candidate.download_uri
            WHEN 'rss' THEN entry.download_uri
            WHEN 'manual' THEN a.source_uri
        END,
        ''
    )::text AS source_uri
FROM downloads AS d
JOIN acquisitions AS a ON a.id = d.acquisition_id
LEFT JOIN release_candidates AS candidate ON candidate.id = a.release_candidate_id
LEFT JOIN rss_entries AS entry ON entry.id = a.rss_entry_id
WHERE d.id = $1
`

type GetDownloadEnqueueCommandRow struct {
	ID                   pgtype.UUID `db:"id" json:"id"`
	AcquisitionID        pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
	Status               string      `db:"status" json:"status"`
	TorrentHash          *string     `db:"torrent_hash" json:"torrent_hash"`
	FileResolutionSource *string     `db:"file_resolution_source" json:"file_resolution_source"`
	SourceUri            string      `db:"source_uri" json:"source_uri"`
}

func (q *Queries) GetDownloadEnqueueCommand(ctx context.Context, id pgtype.UUID) (GetDownloadEnqueueCommandRow, error) {
	row := q.db.QueryRow(ctx, getDownloadEnqueueCommand, id)
	var i GetDownloadEnqueueCommandRow
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Status,
		&i.TorrentHash,
		&i.FileResolutionSource,
		&i.SourceUri,
	)
	return i, err
}

const getDownloadSyncCommand = `-- name: GetDownloadSyncCommand :one
SELECT id, status, torrent_hash, client_state, last_synced_at
FROM downloads
WHERE id = $1
`

type GetDownloadSyncCommandRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Status       string             `db:"status" json:"status"`
	TorrentHash  *string            `db:"torrent_hash" json:"torrent_hash"`
	ClientState  *string            `db:"client_state" json:"client_state"`
	LastSyncedAt pgtype.Timestamptz `db:"last_synced_at" json:"last_synced_at"`
}

func (q *Queries) GetDownloadSyncCommand(ctx context.Context, id pgtype.UUID) (GetDownloadSyncCommandRow, error) {
	row := q.db.QueryRow(ctx, getDownloadSyncCommand, id)
	var i GetDownloadSyncCommandRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TorrentHash,
		&i.ClientState,
		&i.LastSyncedAt,
	)
	return i, err
}

const listDownloadSyncSelectedFiles = `-- name: ListDownloadSyncSelectedFiles :many
SELECT file_index, size_bytes
FROM download_files
WHERE download_id = $1
  AND selected = true
ORDER BY file_index
`

type ListDownloadSyncSelectedFilesRow struct {
	FileIndex int32 `db:"file_index" json:"file_index"`
	SizeBytes int64 `db:"size_bytes" json:"size_bytes"`
}

func (q *Queries) ListDownloadSyncSelectedFiles(ctx context.Context, downloadID pgtype.UUID) ([]ListDownloadSyncSelectedFilesRow, error) {
	rows, err := q.db.Query(ctx, listDownloadSyncSelectedFiles, downloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDownloadSyncSelectedFilesRow{}
	for rows.Next() {
		var i ListDownloadSyncSelectedFilesRow
		if err := rows.Scan(&i.FileIndex, &i.SizeBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDownloadForEnqueue = `-- name: LockDownloadForEnqueue :one
SELECT id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
FROM downloads
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockDownloadForEnqueue(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, lockDownloadForEnqueue, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadCompleted = `-- name: MarkDownloadCompleted :one
UPDATE downloads
SET status = 'completed',
    progress = 1,
    client_state = $1,
    last_synced_at = now(),
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    completed_at = COALESCE(completed_at, now()),
    updated_at = now()
WHERE id = $2
  AND status = 'downloading'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type MarkDownloadCompletedParams struct {
	ClientState *string     `db:"client_state" json:"client_state"`
	ID          pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkDownloadCompleted(ctx context.Context, arg MarkDownloadCompletedParams) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadCompleted, arg.ClientState, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadFileResolutionTerminalFailure = `-- name: MarkDownloadFileResolutionTerminalFailure :one
UPDATE downloads
SET status = 'failed',
    failure_stage = 'file_resolution',
    error_code = $1,
    error_message = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND status = 'file_resolution_pending'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type MarkDownloadFileResolutionTerminalFailureParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkDownloadFileResolutionTerminalFailure(ctx context.Context, arg MarkDownloadFileResolutionTerminalFailureParams) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadFileResolutionTerminalFailure, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadLegacyEnqueued = `-- name: MarkDownloadLegacyEnqueued :one
UPDATE downloads
SET torrent_hash = $1,
    status = 'downloading',
    save_path = $2,
    progress = 0,
    client_state = 'downloading',
    last_synced_at = now(),
    file_resolution_source = 'deterministic',
    agent_resolution_id = NULL,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    started_at = COALESCE(started_at, now()),
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND status = 'enqueue_pending'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type MarkDownloadLegacyEnqueuedParams struct {
	TorrentHash *string     `db:"torrent_hash" json:"torrent_hash"`
	SavePath    *string     `db:"save_path" json:"save_path"`
	ID          pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkDownloadLegacyEnqueued(ctx context.Context, arg MarkDownloadLegacyEnqueuedParams) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadLegacyEnqueued, arg.TorrentHash, arg.SavePath, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadManifestPending = `-- name: MarkDownloadManifestPending :one
UPDATE downloads
SET torrent_hash = $1,
    status = 'file_resolution_pending',
    save_path = $2,
    progress = 0,
    client_state = 'metadata_ready',
    last_synced_at = now(),
    file_resolution_source = $3,
    agent_resolution_id = NULL,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    started_at = COALESCE(started_at, now()),
    version = version + 1,
    updated_at = now()
WHERE id = $4
  AND status = 'enqueue_pending'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type MarkDownloadManifestPendingParams struct {
	TorrentHash          *string     `db:"torrent_hash" json:"torrent_hash"`
	SavePath             *string     `db:"save_path" json:"save_path"`
	FileResolutionSource *string     `db:"file_resolution_source" json:"file_resolution_source"`
	ID                   pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkDownloadManifestPending(ctx context.Context, arg MarkDownloadManifestPendingParams) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadManifestPending,
		arg.TorrentHash,
		arg.SavePath,
		arg.FileResolutionSource,
		arg.ID,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadMaterializeTerminalFailure = `-- name: MarkDownloadMaterializeTerminalFailure :one
UPDATE downloads
SET status = 'failed',
    failure_stage = 'materialize',
    error_code = $1,
    error_message = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND status IN ('completed', 'selecting_files')
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type MarkDownloadMaterializeTerminalFailureParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkDownloadMaterializeTerminalFailure(ctx context.Context, arg MarkDownloadMaterializeTerminalFailureParams) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadMaterializeTerminalFailure, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadRSSEntryEnqueued = `-- name: MarkDownloadRSSEntryEnqueued :execrows
UPDATE rss_entries AS entry
SET status = 'enqueued',
    enqueued_at = COALESCE(enqueued_at, now()),
    last_error_code = NULL,
    last_error_message = NULL,
    last_error_retryable = false,
    updated_at = now()
FROM acquisitions AS acquisition
JOIN downloads AS download ON download.acquisition_id = acquisition.id
WHERE download.id = $1
  AND entry.id = acquisition.rss_entry_id
  AND entry.status IN ('enqueueing', 'enqueue_failed')
`

func (q *Queries) MarkDownloadRSSEntryEnqueued(ctx context.Context, downloadID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markDownloadRSSEntryEnqueued, downloadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDownloadRemovalRequested = `-- name: MarkDownloadRemovalRequested :one
UPDATE downloads
SET deletion_requested_at = COALESCE(deletion_requested_at, now()),
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
  AND deletion_requested_at IS NULL
  AND status IN ('completed', 'materialized', 'failed', 'cancelled')
  AND version = $2
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type MarkDownloadRemovalRequestedParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) MarkDownloadRemovalRequested(ctx context.Context, arg MarkDownloadRemovalRequestedParams) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadRemovalRequested, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadRemoved = `-- name: MarkDownloadRemoved :one
UPDATE downloads
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deletion_requested_at IS NOT NULL
  AND deleted_at IS NULL
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

func (q *Queries) MarkDownloadRemoved(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadRemoved, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadSelectionApplied = `-- name: MarkDownloadSelectionApplied :one
UPDATE downloads
SET status = 'downloading',
    client_state = 'added',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'file_resolution_pending'
  AND torrent_hash IS NOT NULL
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

func (q *Queries) MarkDownloadSelectionApplied(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadSelectionApplied, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadSyncTerminalFailure = `-- name: MarkDownloadSyncTerminalFailure :one
UPDATE downloads
SET status = 'failed',
    failure_stage = 'sync',
    error_code = $1,
    error_message = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND status = 'downloading'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type MarkDownloadSyncTerminalFailureParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkDownloadSyncTerminalFailure(ctx context.Context, arg MarkDownloadSyncTerminalFailureParams) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadSyncTerminalFailure, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const requeueDownloadEnqueueStage = `-- name: RequeueDownloadEnqueueStage :one
UPDATE downloads
SET status = 'enqueue_pending',
    progress = 0,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'failed'
  AND failure_stage = 'enqueue'
  AND version = $2
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type RequeueDownloadEnqueueStageParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueDownloadEnqueueStage(ctx context.Context, arg RequeueDownloadEnqueueStageParams) (Download, error) {
	row := q.db.QueryRow(ctx, requeueDownloadEnqueueStage, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const requeueDownloadFileResolutionStage = `-- name: RequeueDownloadFileResolutionStage :one
UPDATE downloads
SET status = 'file_resolution_pending',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'failed'
  AND failure_stage = 'file_resolution'
  AND torrent_hash IS NOT NULL
  AND version = $2
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type RequeueDownloadFileResolutionStageParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueDownloadFileResolutionStage(ctx context.Context, arg RequeueDownloadFileResolutionStageParams) (Download, error) {
	row := q.db.QueryRow(ctx, requeueDownloadFileResolutionStage, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const requeueDownloadMaterializeStage = `-- name: RequeueDownloadMaterializeStage :one
UPDATE downloads
SET status = 'completed',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'failed'
  AND failure_stage = 'materialize'
  AND torrent_hash IS NOT NULL
  AND version = $2
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type RequeueDownloadMaterializeStageParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueDownloadMaterializeStage(ctx context.Context, arg RequeueDownloadMaterializeStageParams) (Download, error) {
	row := q.db.QueryRow(ctx, requeueDownloadMaterializeStage, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const requeueDownloadNoMainVideoFromFileResolution = `-- name: RequeueDownloadNoMainVideoFromFileResolution :one
UPDATE downloads
SET status = 'enqueue_pending',
    torrent_hash = NULL,
    save_path = NULL,
    progress = 0,
    client_state = NULL,
    last_synced_at = NULL,
    file_resolution_source = NULL,
    agent_resolution_id = NULL,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'failed'
  AND failure_stage = 'file_resolution'
  AND error_code = 'download_no_main_video'
  AND torrent_hash IS NOT NULL
  AND version = $2
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type RequeueDownloadNoMainVideoFromFileResolutionParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueDownloadNoMainVideoFromFileResolution(ctx context.Context, arg RequeueDownloadNoMainVideoFromFileResolutionParams) (Download, error) {
	row := q.db.QueryRow(ctx, requeueDownloadNoMainVideoFromFileResolution, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const requeueDownloadSyncStage = `-- name: RequeueDownloadSyncStage :one
UPDATE downloads
SET status = 'downloading',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'failed'
  AND failure_stage = 'sync'
  AND torrent_hash IS NOT NULL
  AND version = $2
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type RequeueDownloadSyncStageParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueDownloadSyncStage(ctx context.Context, arg RequeueDownloadSyncStageParams) (Download, error) {
	row := q.db.QueryRow(ctx, requeueDownloadSyncStage, arg.ID, arg.ExpectedVersion)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const setDownloadFileResolution = `-- name: SetDownloadFileResolution :one
UPDATE download_files
SET selected = $1,
    source_season = $2,
    source_episode = $3,
    source_episode_fraction_hundredths = $4,
    updated_at = now()
WHERE id = $5
  AND download_id = $6
RETURNING id, download_id, file_index, relative_path, size_bytes, media_kind, selected, source_season, source_episode, language, created_at, updated_at, source_episode_fraction_hundredths
`

type SetDownloadFileResolutionParams struct {
	Selected                        bool        `db:"selected" json:"selected"`
	SourceSeason                    *int32      `db:"source_season" json:"source_season"`
	SourceEpisode                   *int32      `db:"source_episode" json:"source_episode"`
	SourceEpisodeFractionHundredths int32       `db:"source_episode_fraction_hundredths" json:"source_episode_fraction_hundredths"`
	ID                              pgtype.UUID `db:"id" json:"id"`
	DownloadID                      pgtype.UUID `db:"download_id" json:"download_id"`
}

func (q *Queries) SetDownloadFileResolution(ctx context.Context, arg SetDownloadFileResolutionParams) (DownloadFile, error) {
	row := q.db.QueryRow(ctx, setDownloadFileResolution,
		arg.Selected,
		arg.SourceSeason,
		arg.SourceEpisode,
		arg.SourceEpisodeFractionHundredths,
		arg.ID,
		arg.DownloadID,
	)
	var i DownloadFile
	err := row.Scan(
		&i.ID,
		&i.DownloadID,
		&i.FileIndex,
		&i.RelativePath,
		&i.SizeBytes,
		&i.MediaKind,
		&i.Selected,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceEpisodeFractionHundredths,
	)
	return i, err
}

const setDownloadFileSelection = `-- name: SetDownloadFileSelection :one
UPDATE download_files
SET selected = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, download_id, file_index, relative_path, size_bytes, media_kind, selected, source_season, source_episode, language, created_at, updated_at, source_episode_fraction_hundredths
`

type SetDownloadFileSelectionParams struct {
	Selected bool        `db:"selected" json:"selected"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SetDownloadFileSelection(ctx context.Context, arg SetDownloadFileSelectionParams) (DownloadFile, error) {
	row := q.db.QueryRow(ctx, setDownloadFileSelection, arg.Selected, arg.ID)
	var i DownloadFile
	err := row.Scan(
		&i.ID,
		&i.DownloadID,
		&i.FileIndex,
		&i.RelativePath,
		&i.SizeBytes,
		&i.MediaKind,
		&i.Selected,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceEpisodeFractionHundredths,
	)
	return i, err
}

const setDownloadResolutionSource = `-- name: SetDownloadResolutionSource :one
UPDATE downloads
SET status = 'file_resolution_pending',
    file_resolution_source = $1,
    agent_resolution_id = $2,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND version = $4
  AND (
      status = 'file_resolution_pending'
      OR (status = 'failed' AND failure_stage = 'file_resolution')
  )
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type SetDownloadResolutionSourceParams struct {
	FileResolutionSource *string     `db:"file_resolution_source" json:"file_resolution_source"`
	AgentResolutionID    pgtype.UUID `db:"agent_resolution_id" json:"agent_resolution_id"`
	ID                   pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion      int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) SetDownloadResolutionSource(ctx context.Context, arg SetDownloadResolutionSourceParams) (Download, error) {
	row := q.db.QueryRow(ctx, setDownloadResolutionSource,
		arg.FileResolutionSource,
		arg.AgentResolutionID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const torrentUsedByOtherDownload = `-- name: TorrentUsedByOtherDownload :one
SELECT EXISTS (
    SELECT 1
    FROM downloads AS target
    JOIN downloads AS other
      ON lower(other.torrent_hash) = lower(target.torrent_hash)
     AND other.id <> target.id
    WHERE target.id = $1
      AND target.torrent_hash IS NOT NULL
      AND other.deleted_at IS NULL
      AND other.status <> 'cancelled'
)::boolean
`

func (q *Queries) TorrentUsedByOtherDownload(ctx context.Context, downloadID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, torrentUsedByOtherDownload, downloadID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateDownloadProgress = `-- name: UpdateDownloadProgress :one
UPDATE downloads
SET progress = GREATEST(
        progress,
        LEAST(1, GREATEST(0, $1::bigint::numeric / 100000))
    ),
    client_state = $2,
    last_synced_at = now(),
    updated_at = now()
WHERE id = $3
  AND status = 'downloading'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

type UpdateDownloadProgressParams struct {
	ProgressScaled int64       `db:"progress_scaled" json:"progress_scaled"`
	ClientState    *string     `db:"client_state" json:"client_state"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) (Download, error) {
	row := q.db.QueryRow(ctx, updateDownloadProgress, arg.ProgressScaled, arg.ClientState, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}
