// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO events (
    id,
    topic,
    resource_type,
    resource_id,
    operation_id,
    actor_user_id,
    data
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, event_sequence, topic, resource_type, resource_id, operation_id, actor_user_id, data, occurred_at
`

type AppendEventParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	Topic        string      `db:"topic" json:"topic"`
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	OperationID  pgtype.UUID `db:"operation_id" json:"operation_id"`
	ActorUserID  pgtype.UUID `db:"actor_user_id" json:"actor_user_id"`
	Data         []byte      `db:"data" json:"data"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ID,
		arg.Topic,
		arg.ResourceType,
		arg.ResourceID,
		arg.OperationID,
		arg.ActorUserID,
		arg.Data,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventSequence,
		&i.Topic,
		&i.ResourceType,
		&i.ResourceID,
		&i.OperationID,
		&i.ActorUserID,
		&i.Data,
		&i.OccurredAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, event_sequence, topic, resource_type, resource_id, operation_id, actor_user_id, data, occurred_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.EventSequence,
		&i.Topic,
		&i.ResourceType,
		&i.ResourceID,
		&i.OperationID,
		&i.ActorUserID,
		&i.Data,
		&i.OccurredAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, event_sequence, topic, resource_type, resource_id, operation_id, actor_user_id, data, occurred_at
FROM events
ORDER BY event_sequence
LIMIT $1
`

func (q *Queries) ListEvents(ctx context.Context, pageSize int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, pageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventSequence,
			&i.Topic,
			&i.ResourceType,
			&i.ResourceID,
			&i.OperationID,
			&i.ActorUserID,
			&i.Data,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsAfter = `-- name: ListEventsAfter :many
SELECT event.id, event.event_sequence, event.topic, event.resource_type, event.resource_id, event.operation_id, event.actor_user_id, event.data, event.occurred_at
FROM events AS event
JOIN events AS cursor_event ON cursor_event.id = $1
WHERE event.event_sequence > cursor_event.event_sequence
ORDER BY event.event_sequence
LIMIT $2
`

type ListEventsAfterParams struct {
	CursorID pgtype.UUID `db:"cursor_id" json:"cursor_id"`
	PageSize int32       `db:"page_size" json:"page_size"`
}

func (q *Queries) ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAfter, arg.CursorID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventSequence,
			&i.Topic,
			&i.ResourceType,
			&i.ResourceID,
			&i.OperationID,
			&i.ActorUserID,
			&i.Data,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
