// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEpisodeTaskIfActive = `-- name: CancelEpisodeTaskIfActive :one
UPDATE episode_tasks
SET state = 'cancelled',
    video_state = CASE WHEN video_state IN ('transcode_queued', 'transcoding') THEN 'cancelled' ELSE video_state END,
    subtitle_state = CASE WHEN subtitle_state IN ('subtitle_queued', 'extracting_or_converting') THEN 'cancelled' ELSE subtitle_state END,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state NOT IN ('imported', 'failed', 'cancelled', 'rejected')
  AND version = $2
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

type CancelEpisodeTaskIfActiveParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) CancelEpisodeTaskIfActive(ctx context.Context, arg CancelEpisodeTaskIfActiveParams) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, cancelEpisodeTaskIfActive, arg.ID, arg.ExpectedVersion)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const createArtifactSet = `-- name: CreateArtifactSet :one
INSERT INTO artifact_sets (
    id,
    task_id,
    transcode_profile_id,
    basename,
    video_artifact_id,
    subtitle_artifact_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (task_id) DO UPDATE
SET transcode_profile_id = EXCLUDED.transcode_profile_id,
    basename = EXCLUDED.basename,
    video_artifact_id = EXCLUDED.video_artifact_id,
    subtitle_artifact_id = EXCLUDED.subtitle_artifact_id
RETURNING id, task_id, transcode_profile_id, basename, video_artifact_id, subtitle_artifact_id, created_at
`

type CreateArtifactSetParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	TaskID             pgtype.UUID `db:"task_id" json:"task_id"`
	TranscodeProfileID pgtype.UUID `db:"transcode_profile_id" json:"transcode_profile_id"`
	Basename           string      `db:"basename" json:"basename"`
	VideoArtifactID    pgtype.UUID `db:"video_artifact_id" json:"video_artifact_id"`
	SubtitleArtifactID pgtype.UUID `db:"subtitle_artifact_id" json:"subtitle_artifact_id"`
}

func (q *Queries) CreateArtifactSet(ctx context.Context, arg CreateArtifactSetParams) (ArtifactSet, error) {
	row := q.db.QueryRow(ctx, createArtifactSet,
		arg.ID,
		arg.TaskID,
		arg.TranscodeProfileID,
		arg.Basename,
		arg.VideoArtifactID,
		arg.SubtitleArtifactID,
	)
	var i ArtifactSet
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TranscodeProfileID,
		&i.Basename,
		&i.VideoArtifactID,
		&i.SubtitleArtifactID,
		&i.CreatedAt,
	)
	return i, err
}

const createEpisodeTask = `-- name: CreateEpisodeTask :one
INSERT INTO episode_tasks (
    id,
    acquisition_id,
    source_video_file_id,
    mapping_id,
    transcode_profile_id,
    media_type
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (acquisition_id, source_video_file_id) DO NOTHING
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

type CreateEpisodeTaskParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	AcquisitionID      pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
	SourceVideoFileID  pgtype.UUID `db:"source_video_file_id" json:"source_video_file_id"`
	MappingID          pgtype.UUID `db:"mapping_id" json:"mapping_id"`
	TranscodeProfileID pgtype.UUID `db:"transcode_profile_id" json:"transcode_profile_id"`
	MediaType          string      `db:"media_type" json:"media_type"`
}

func (q *Queries) CreateEpisodeTask(ctx context.Context, arg CreateEpisodeTaskParams) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, createEpisodeTask,
		arg.ID,
		arg.AcquisitionID,
		arg.SourceVideoFileID,
		arg.MappingID,
		arg.TranscodeProfileID,
		arg.MediaType,
	)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, task_id, source_file_id, transcode_profile_id, kind, basename, file_path, format, size_bytes, checksum_sha256, metadata, created_at
FROM media_artifacts
WHERE id = $1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id pgtype.UUID) (MediaArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, id)
	var i MediaArtifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SourceFileID,
		&i.TranscodeProfileID,
		&i.Kind,
		&i.Basename,
		&i.FilePath,
		&i.Format,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultTranscodeProfile = `-- name: GetDefaultTranscodeProfile :one
SELECT id, name, version, active, is_default, video_codec, encoder, container, file_extension, quality_mode, quality_value, audio_policy, audio_codec, preset, pixel_format, thread_count, max_concurrency, created_at, created_by
FROM transcode_profiles
WHERE active
  AND is_default
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetDefaultTranscodeProfile(ctx context.Context) (TranscodeProfile, error) {
	row := q.db.QueryRow(ctx, getDefaultTranscodeProfile)
	var i TranscodeProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Active,
		&i.IsDefault,
		&i.VideoCodec,
		&i.Encoder,
		&i.Container,
		&i.FileExtension,
		&i.QualityMode,
		&i.QualityValue,
		&i.AudioPolicy,
		&i.AudioCodec,
		&i.Preset,
		&i.PixelFormat,
		&i.ThreadCount,
		&i.MaxConcurrency,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getEpisodeTaskBySource = `-- name: GetEpisodeTaskBySource :one
SELECT id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
FROM episode_tasks
WHERE acquisition_id = $1
  AND source_video_file_id = $2
`

type GetEpisodeTaskBySourceParams struct {
	AcquisitionID     pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
	SourceVideoFileID pgtype.UUID `db:"source_video_file_id" json:"source_video_file_id"`
}

func (q *Queries) GetEpisodeTaskBySource(ctx context.Context, arg GetEpisodeTaskBySourceParams) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, getEpisodeTaskBySource, arg.AcquisitionID, arg.SourceVideoFileID)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const getTaskArtifact = `-- name: GetTaskArtifact :one
SELECT id, task_id, source_file_id, transcode_profile_id, kind, basename, file_path, format, size_bytes, checksum_sha256, metadata, created_at
FROM media_artifacts
WHERE task_id = $1
  AND kind = $2
`

type GetTaskArtifactParams struct {
	TaskID pgtype.UUID `db:"task_id" json:"task_id"`
	Kind   string      `db:"kind" json:"kind"`
}

func (q *Queries) GetTaskArtifact(ctx context.Context, arg GetTaskArtifactParams) (MediaArtifact, error) {
	row := q.db.QueryRow(ctx, getTaskArtifact, arg.TaskID, arg.Kind)
	var i MediaArtifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SourceFileID,
		&i.TranscodeProfileID,
		&i.Kind,
		&i.Basename,
		&i.FilePath,
		&i.Format,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskFinalizeCommand = `-- name: GetTaskFinalizeCommand :one
SELECT
    task.id AS task_id,
    task.state,
    task.transcode_profile_id,
    video.id AS video_artifact_id,
    video.basename AS video_basename,
    video.file_path AS video_file_path,
    video.size_bytes AS video_size_bytes,
    video.checksum_sha256 AS video_checksum_sha256,
    subtitle.id AS subtitle_artifact_id,
    subtitle.basename AS subtitle_basename,
    subtitle.file_path AS subtitle_file_path,
    subtitle.size_bytes AS subtitle_size_bytes,
    subtitle.checksum_sha256 AS subtitle_checksum_sha256
FROM episode_tasks AS task
JOIN media_artifacts AS video ON video.task_id = task.id AND video.kind = 'video'
JOIN media_artifacts AS subtitle ON subtitle.task_id = task.id AND subtitle.kind = 'subtitle'
WHERE task.id = $1
`

type GetTaskFinalizeCommandRow struct {
	TaskID                 pgtype.UUID `db:"task_id" json:"task_id"`
	State                  string      `db:"state" json:"state"`
	TranscodeProfileID     pgtype.UUID `db:"transcode_profile_id" json:"transcode_profile_id"`
	VideoArtifactID        pgtype.UUID `db:"video_artifact_id" json:"video_artifact_id"`
	VideoBasename          string      `db:"video_basename" json:"video_basename"`
	VideoFilePath          string      `db:"video_file_path" json:"video_file_path"`
	VideoSizeBytes         int64       `db:"video_size_bytes" json:"video_size_bytes"`
	VideoChecksumSha256    []byte      `db:"video_checksum_sha256" json:"video_checksum_sha256"`
	SubtitleArtifactID     pgtype.UUID `db:"subtitle_artifact_id" json:"subtitle_artifact_id"`
	SubtitleBasename       string      `db:"subtitle_basename" json:"subtitle_basename"`
	SubtitleFilePath       string      `db:"subtitle_file_path" json:"subtitle_file_path"`
	SubtitleSizeBytes      int64       `db:"subtitle_size_bytes" json:"subtitle_size_bytes"`
	SubtitleChecksumSha256 []byte      `db:"subtitle_checksum_sha256" json:"subtitle_checksum_sha256"`
}

func (q *Queries) GetTaskFinalizeCommand(ctx context.Context, id pgtype.UUID) (GetTaskFinalizeCommandRow, error) {
	row := q.db.QueryRow(ctx, getTaskFinalizeCommand, id)
	var i GetTaskFinalizeCommandRow
	err := row.Scan(
		&i.TaskID,
		&i.State,
		&i.TranscodeProfileID,
		&i.VideoArtifactID,
		&i.VideoBasename,
		&i.VideoFilePath,
		&i.VideoSizeBytes,
		&i.VideoChecksumSha256,
		&i.SubtitleArtifactID,
		&i.SubtitleBasename,
		&i.SubtitleFilePath,
		&i.SubtitleSizeBytes,
		&i.SubtitleChecksumSha256,
	)
	return i, err
}

const getTaskMediaCommand = `-- name: GetTaskMediaCommand :one
SELECT
    task.id AS task_id,
    task.state,
    task.video_state,
    task.subtitle_state,
    task.transcode_profile_id,
    task.media_type,
    video.id AS source_video_file_id,
    video.relative_path AS source_video_relative_path,
    video.source_season,
    video.source_episode,
    download.id AS download_id,
    download.save_path,
    mapping.id AS mapping_id,
    episode.episode_number AS target_episode_number,
    episode.title AS target_episode_title,
    season.season_number AS target_season_number,
    series.title AS series_title,
    series.release_year,
    series.tmdb_movie_id,
    profile.name AS profile_name,
    profile.video_codec,
    profile.encoder,
    profile.container,
    profile.file_extension,
    profile.quality_mode,
    profile.quality_value,
    profile.audio_policy,
    profile.audio_codec,
    profile.preset,
    profile.pixel_format,
    profile.thread_count,
    profile.max_concurrency
FROM episode_tasks AS task
JOIN download_files AS video ON video.id = task.source_video_file_id
JOIN downloads AS download ON download.id = video.download_id
JOIN acquisitions AS acquisition ON acquisition.id = task.acquisition_id
JOIN media_series AS series ON series.id = acquisition.series_id
LEFT JOIN episode_mappings AS mapping ON mapping.id = task.mapping_id AND mapping.mapping_status = 'mapped'
LEFT JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
LEFT JOIN tmdb_seasons AS season ON season.id = episode.season_id
JOIN transcode_profiles AS profile ON profile.id = task.transcode_profile_id
WHERE task.id = $1
`

type GetTaskMediaCommandRow struct {
	TaskID                  pgtype.UUID    `db:"task_id" json:"task_id"`
	State                   string         `db:"state" json:"state"`
	VideoState              string         `db:"video_state" json:"video_state"`
	SubtitleState           string         `db:"subtitle_state" json:"subtitle_state"`
	TranscodeProfileID      pgtype.UUID    `db:"transcode_profile_id" json:"transcode_profile_id"`
	MediaType               string         `db:"media_type" json:"media_type"`
	SourceVideoFileID       pgtype.UUID    `db:"source_video_file_id" json:"source_video_file_id"`
	SourceVideoRelativePath string         `db:"source_video_relative_path" json:"source_video_relative_path"`
	SourceSeason            *int32         `db:"source_season" json:"source_season"`
	SourceEpisode           *int32         `db:"source_episode" json:"source_episode"`
	DownloadID              pgtype.UUID    `db:"download_id" json:"download_id"`
	SavePath                *string        `db:"save_path" json:"save_path"`
	MappingID               pgtype.UUID    `db:"mapping_id" json:"mapping_id"`
	TargetEpisodeNumber     *int32         `db:"target_episode_number" json:"target_episode_number"`
	TargetEpisodeTitle      *string        `db:"target_episode_title" json:"target_episode_title"`
	TargetSeasonNumber      *int32         `db:"target_season_number" json:"target_season_number"`
	SeriesTitle             string         `db:"series_title" json:"series_title"`
	ReleaseYear             *int32         `db:"release_year" json:"release_year"`
	TmdbMovieID             *int64         `db:"tmdb_movie_id" json:"tmdb_movie_id"`
	ProfileName             string         `db:"profile_name" json:"profile_name"`
	VideoCodec              string         `db:"video_codec" json:"video_codec"`
	Encoder                 string         `db:"encoder" json:"encoder"`
	Container               string         `db:"container" json:"container"`
	FileExtension           string         `db:"file_extension" json:"file_extension"`
	QualityMode             string         `db:"quality_mode" json:"quality_mode"`
	QualityValue            pgtype.Numeric `db:"quality_value" json:"quality_value"`
	AudioPolicy             string         `db:"audio_policy" json:"audio_policy"`
	AudioCodec              *string        `db:"audio_codec" json:"audio_codec"`
	Preset                  string         `db:"preset" json:"preset"`
	PixelFormat             string         `db:"pixel_format" json:"pixel_format"`
	ThreadCount             int32          `db:"thread_count" json:"thread_count"`
	MaxConcurrency          int32          `db:"max_concurrency" json:"max_concurrency"`
}

func (q *Queries) GetTaskMediaCommand(ctx context.Context, id pgtype.UUID) (GetTaskMediaCommandRow, error) {
	row := q.db.QueryRow(ctx, getTaskMediaCommand, id)
	var i GetTaskMediaCommandRow
	err := row.Scan(
		&i.TaskID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.TranscodeProfileID,
		&i.MediaType,
		&i.SourceVideoFileID,
		&i.SourceVideoRelativePath,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.DownloadID,
		&i.SavePath,
		&i.MappingID,
		&i.TargetEpisodeNumber,
		&i.TargetEpisodeTitle,
		&i.TargetSeasonNumber,
		&i.SeriesTitle,
		&i.ReleaseYear,
		&i.TmdbMovieID,
		&i.ProfileName,
		&i.VideoCodec,
		&i.Encoder,
		&i.Container,
		&i.FileExtension,
		&i.QualityMode,
		&i.QualityValue,
		&i.AudioPolicy,
		&i.AudioCodec,
		&i.Preset,
		&i.PixelFormat,
		&i.ThreadCount,
		&i.MaxConcurrency,
	)
	return i, err
}

const getTaskRSSAutoReview = `-- name: GetTaskRSSAutoReview :one
SELECT
    subscription.id AS subscription_id,
    subscription.auto_review
FROM episode_tasks AS task
JOIN acquisitions AS acquisition ON acquisition.id = task.acquisition_id
JOIN rss_entries AS entry ON entry.id = acquisition.rss_entry_id
JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
WHERE task.id = $1
  AND subscription.deleted_at IS NULL
`

type GetTaskRSSAutoReviewRow struct {
	SubscriptionID pgtype.UUID `db:"subscription_id" json:"subscription_id"`
	AutoReview     bool        `db:"auto_review" json:"auto_review"`
}

func (q *Queries) GetTaskRSSAutoReview(ctx context.Context, id pgtype.UUID) (GetTaskRSSAutoReviewRow, error) {
	row := q.db.QueryRow(ctx, getTaskRSSAutoReview, id)
	var i GetTaskRSSAutoReviewRow
	err := row.Scan(&i.SubscriptionID, &i.AutoReview)
	return i, err
}

const listMaterializeVideos = `-- name: ListMaterializeVideos :many
SELECT
    file.id AS file_id,
    file.relative_path,
    file.size_bytes,
    file.source_season,
    file.source_episode,
    mapping.id AS mapping_id,
    mapping.mapping_status,
    mapping.error_code AS mapping_error_code,
    episode.id AS target_episode_id,
    episode.episode_number AS target_episode_number,
    episode.title AS target_episode_title,
    season.season_number AS target_season_number,
    series.title AS series_title,
    series.media_type,
    series.release_year,
    series.tmdb_movie_id
FROM download_files AS file
JOIN downloads AS download ON download.id = file.download_id
JOIN acquisitions AS acquisition ON acquisition.id = download.acquisition_id
JOIN media_series AS series ON series.id = acquisition.series_id
LEFT JOIN episode_mappings AS mapping
    ON mapping.profile_id = acquisition.mapping_profile_id
   AND mapping.source_season = file.source_season
   AND mapping.source_episode = file.source_episode
LEFT JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
LEFT JOIN tmdb_seasons AS season ON season.id = episode.season_id
WHERE file.download_id = $1
  AND file.selected
  AND file.media_kind = 'video'
ORDER BY file.source_season, file.source_episode, file.file_index
`

type ListMaterializeVideosRow struct {
	FileID              pgtype.UUID `db:"file_id" json:"file_id"`
	RelativePath        string      `db:"relative_path" json:"relative_path"`
	SizeBytes           int64       `db:"size_bytes" json:"size_bytes"`
	SourceSeason        *int32      `db:"source_season" json:"source_season"`
	SourceEpisode       *int32      `db:"source_episode" json:"source_episode"`
	MappingID           pgtype.UUID `db:"mapping_id" json:"mapping_id"`
	MappingStatus       *string     `db:"mapping_status" json:"mapping_status"`
	MappingErrorCode    *string     `db:"mapping_error_code" json:"mapping_error_code"`
	TargetEpisodeID     pgtype.UUID `db:"target_episode_id" json:"target_episode_id"`
	TargetEpisodeNumber *int32      `db:"target_episode_number" json:"target_episode_number"`
	TargetEpisodeTitle  *string     `db:"target_episode_title" json:"target_episode_title"`
	TargetSeasonNumber  *int32      `db:"target_season_number" json:"target_season_number"`
	SeriesTitle         string      `db:"series_title" json:"series_title"`
	MediaType           string      `db:"media_type" json:"media_type"`
	ReleaseYear         *int32      `db:"release_year" json:"release_year"`
	TmdbMovieID         *int64      `db:"tmdb_movie_id" json:"tmdb_movie_id"`
}

func (q *Queries) ListMaterializeVideos(ctx context.Context, downloadID pgtype.UUID) ([]ListMaterializeVideosRow, error) {
	rows, err := q.db.Query(ctx, listMaterializeVideos, downloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaterializeVideosRow{}
	for rows.Next() {
		var i ListMaterializeVideosRow
		if err := rows.Scan(
			&i.FileID,
			&i.RelativePath,
			&i.SizeBytes,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.MappingID,
			&i.MappingStatus,
			&i.MappingErrorCode,
			&i.TargetEpisodeID,
			&i.TargetEpisodeNumber,
			&i.TargetEpisodeTitle,
			&i.TargetSeasonNumber,
			&i.SeriesTitle,
			&i.MediaType,
			&i.ReleaseYear,
			&i.TmdbMovieID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskExternalSubtitles = `-- name: ListTaskExternalSubtitles :many
SELECT
    subtitle.id,
    subtitle.relative_path,
    subtitle.language
FROM episode_tasks AS task
JOIN download_files AS video ON video.id = task.source_video_file_id
JOIN download_files AS subtitle
    ON subtitle.download_id = video.download_id
   AND subtitle.source_season = video.source_season
   AND subtitle.source_episode = video.source_episode
WHERE task.id = $1
  AND subtitle.selected
  AND subtitle.media_kind = 'subtitle'
ORDER BY subtitle.file_index
`

type ListTaskExternalSubtitlesRow struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	RelativePath string      `db:"relative_path" json:"relative_path"`
	Language     *string     `db:"language" json:"language"`
}

func (q *Queries) ListTaskExternalSubtitles(ctx context.Context, taskID pgtype.UUID) ([]ListTaskExternalSubtitlesRow, error) {
	rows, err := q.db.Query(ctx, listTaskExternalSubtitles, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskExternalSubtitlesRow{}
	for rows.Next() {
		var i ListTaskExternalSubtitlesRow
		if err := rows.Scan(&i.ID, &i.RelativePath, &i.Language); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDownloadForMaterialize = `-- name: LockDownloadForMaterialize :one
SELECT
    download.id, download.acquisition_id, download.attempt, download.client_name, download.torrent_hash, download.status, download.progress, download.save_path, download.error_code, download.error_message, download.started_at, download.completed_at, download.created_at, download.updated_at, download.version, download.failure_stage, download.client_state, download.last_synced_at, download.deletion_requested_at, download.deleted_at, download.file_resolution_source, download.agent_resolution_id,
    acquisition.id AS workflow_acquisition_id,
    acquisition.mapping_profile_id,
    media.id AS media_id,
    media.media_type,
    media.title AS media_title,
    media.release_year,
    media.tmdb_movie_id
FROM downloads AS download
JOIN acquisitions AS acquisition ON acquisition.id = download.acquisition_id
JOIN media_series AS media ON media.id = acquisition.series_id
WHERE download.id = $1
FOR UPDATE OF download
`

type LockDownloadForMaterializeRow struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	AcquisitionID         pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	Attempt               int32              `db:"attempt" json:"attempt"`
	ClientName            string             `db:"client_name" json:"client_name"`
	TorrentHash           *string            `db:"torrent_hash" json:"torrent_hash"`
	Status                string             `db:"status" json:"status"`
	Progress              pgtype.Numeric     `db:"progress" json:"progress"`
	SavePath              *string            `db:"save_path" json:"save_path"`
	ErrorCode             *string            `db:"error_code" json:"error_code"`
	ErrorMessage          *string            `db:"error_message" json:"error_message"`
	StartedAt             pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt           pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version               int32              `db:"version" json:"version"`
	FailureStage          *string            `db:"failure_stage" json:"failure_stage"`
	ClientState           *string            `db:"client_state" json:"client_state"`
	LastSyncedAt          pgtype.Timestamptz `db:"last_synced_at" json:"last_synced_at"`
	DeletionRequestedAt   pgtype.Timestamptz `db:"deletion_requested_at" json:"deletion_requested_at"`
	DeletedAt             pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	FileResolutionSource  *string            `db:"file_resolution_source" json:"file_resolution_source"`
	AgentResolutionID     pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
	WorkflowAcquisitionID pgtype.UUID        `db:"workflow_acquisition_id" json:"workflow_acquisition_id"`
	MappingProfileID      pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	MediaID               pgtype.UUID        `db:"media_id" json:"media_id"`
	MediaType             string             `db:"media_type" json:"media_type"`
	MediaTitle            string             `db:"media_title" json:"media_title"`
	ReleaseYear           *int32             `db:"release_year" json:"release_year"`
	TmdbMovieID           *int64             `db:"tmdb_movie_id" json:"tmdb_movie_id"`
}

func (q *Queries) LockDownloadForMaterialize(ctx context.Context, id pgtype.UUID) (LockDownloadForMaterializeRow, error) {
	row := q.db.QueryRow(ctx, lockDownloadForMaterialize, id)
	var i LockDownloadForMaterializeRow
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
		&i.WorkflowAcquisitionID,
		&i.MappingProfileID,
		&i.MediaID,
		&i.MediaType,
		&i.MediaTitle,
		&i.ReleaseYear,
		&i.TmdbMovieID,
	)
	return i, err
}

const lockEpisodeTask = `-- name: LockEpisodeTask :one
SELECT id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
FROM episode_tasks
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockEpisodeTask(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, lockEpisodeTask, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markDownloadMaterialized = `-- name: MarkDownloadMaterialized :one
UPDATE downloads
SET status = 'materialized',
    updated_at = now()
WHERE id = $1
  AND status = 'selecting_files'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

func (q *Queries) MarkDownloadMaterialized(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadMaterialized, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markDownloadSelectingFiles = `-- name: MarkDownloadSelectingFiles :one
UPDATE downloads
SET status = 'selecting_files',
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND status = 'completed'
RETURNING id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
`

func (q *Queries) MarkDownloadSelectingFiles(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, markDownloadSelectingFiles, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const markTaskAwaitingReview = `-- name: MarkTaskAwaitingReview :one
UPDATE episode_tasks
SET state = 'awaiting_review',
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state = 'finalizing'
  AND video_state = 'video_ready'
  AND subtitle_state = 'ass_ready'
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) MarkTaskAwaitingReview(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskAwaitingReview, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskFinalizeCancelled = `-- name: MarkTaskFinalizeCancelled :one
UPDATE episode_tasks
SET state = 'cancelled',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state = 'finalizing'
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) MarkTaskFinalizeCancelled(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskFinalizeCancelled, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskFinalizeTerminalFailure = `-- name: MarkTaskFinalizeTerminalFailure :one
UPDATE episode_tasks
SET state = 'failed',
    failure_stage = 'finalize',
    error_code = $1,
    error_message = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND state = 'finalizing'
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

type MarkTaskFinalizeTerminalFailureParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkTaskFinalizeTerminalFailure(ctx context.Context, arg MarkTaskFinalizeTerminalFailureParams) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskFinalizeTerminalFailure, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskFinalizingIfReady = `-- name: MarkTaskFinalizingIfReady :one
UPDATE episode_tasks
SET state = 'finalizing',
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state = 'processing'
  AND video_state = 'video_ready'
  AND subtitle_state = 'ass_ready'
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) MarkTaskFinalizingIfReady(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskFinalizingIfReady, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskSubtitleCancelled = `-- name: MarkTaskSubtitleCancelled :one
UPDATE episode_tasks
SET state = 'cancelled',
    subtitle_state = 'cancelled',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND subtitle_state IN ('subtitle_queued', 'extracting_or_converting')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) MarkTaskSubtitleCancelled(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskSubtitleCancelled, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskSubtitleReady = `-- name: MarkTaskSubtitleReady :one
UPDATE episode_tasks
SET subtitle_state = 'ass_ready',
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND subtitle_state IN ('subtitle_queued', 'extracting_or_converting')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) MarkTaskSubtitleReady(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskSubtitleReady, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskSubtitleTerminalFailure = `-- name: MarkTaskSubtitleTerminalFailure :one
UPDATE episode_tasks
SET state = 'failed',
    subtitle_state = 'failed',
    failure_stage = 'subtitle',
    error_code = $1,
    error_message = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND subtitle_state IN ('subtitle_queued', 'extracting_or_converting')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

type MarkTaskSubtitleTerminalFailureParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkTaskSubtitleTerminalFailure(ctx context.Context, arg MarkTaskSubtitleTerminalFailureParams) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskSubtitleTerminalFailure, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskVideoCancelled = `-- name: MarkTaskVideoCancelled :one
UPDATE episode_tasks
SET state = 'cancelled',
    video_state = 'cancelled',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND video_state IN ('transcode_queued', 'transcoding')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) MarkTaskVideoCancelled(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskVideoCancelled, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskVideoReady = `-- name: MarkTaskVideoReady :one
UPDATE episode_tasks
SET video_state = 'video_ready',
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND video_state IN ('transcode_queued', 'transcoding')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) MarkTaskVideoReady(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskVideoReady, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const markTaskVideoTerminalFailure = `-- name: MarkTaskVideoTerminalFailure :one
UPDATE episode_tasks
SET state = 'failed',
    video_state = 'failed',
    failure_stage = 'video',
    error_code = $1,
    error_message = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND video_state IN ('transcode_queued', 'transcoding')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

type MarkTaskVideoTerminalFailureParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) MarkTaskVideoTerminalFailure(ctx context.Context, arg MarkTaskVideoTerminalFailureParams) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, markTaskVideoTerminalFailure, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const requeueTaskFailedMediaBranches = `-- name: RequeueTaskFailedMediaBranches :one
UPDATE episode_tasks
SET state = CASE WHEN state = 'failed' THEN 'processing' ELSE state END,
    video_state = CASE WHEN video_state = 'failed' THEN 'transcode_queued' ELSE video_state END,
    subtitle_state = CASE WHEN subtitle_state = 'failed' THEN 'subtitle_queued' ELSE subtitle_state END,
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND version = $2
  AND (
      (state = 'failed' AND (video_state = 'failed' OR subtitle_state = 'failed'))
      OR (state = 'processing' AND (video_state = 'failed' OR subtitle_state = 'failed'))
  )
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

type RequeueTaskFailedMediaBranchesParams struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	ExpectedVersion int32       `db:"expected_version" json:"expected_version"`
}

func (q *Queries) RequeueTaskFailedMediaBranches(ctx context.Context, arg RequeueTaskFailedMediaBranchesParams) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, requeueTaskFailedMediaBranches, arg.ID, arg.ExpectedVersion)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const requeueTaskFinalizeBranch = `-- name: RequeueTaskFinalizeBranch :one
UPDATE episode_tasks
SET state = 'finalizing',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state = 'failed'
  AND video_state = 'video_ready'
  AND subtitle_state = 'ass_ready'
  AND failure_stage = 'finalize'
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) RequeueTaskFinalizeBranch(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, requeueTaskFinalizeBranch, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const requeueTaskImportBranch = `-- name: RequeueTaskImportBranch :one
UPDATE episode_tasks
SET state = 'import_queued',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE episode_tasks.id = $1
  AND episode_tasks.state = 'failed'
  AND episode_tasks.failure_stage = 'import'
  AND EXISTS (
      SELECT 1 FROM imports
      WHERE imports.task_id = episode_tasks.id
        AND imports.status = 'failed'
  )
RETURNING episode_tasks.id, episode_tasks.acquisition_id, episode_tasks.source_video_file_id, episode_tasks.mapping_id, episode_tasks.transcode_profile_id, episode_tasks.state, episode_tasks.video_state, episode_tasks.subtitle_state, episode_tasks.version, episode_tasks.error_code, episode_tasks.error_message, episode_tasks.legacy_id, episode_tasks.created_at, episode_tasks.updated_at, episode_tasks.failure_stage, episode_tasks.media_type
`

func (q *Queries) RequeueTaskImportBranch(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, requeueTaskImportBranch, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const requeueTaskSubtitleBranch = `-- name: RequeueTaskSubtitleBranch :one
UPDATE episode_tasks
SET state = 'processing',
    subtitle_state = 'subtitle_queued',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state = 'failed'
  AND subtitle_state = 'failed'
  AND failure_stage = 'subtitle'
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) RequeueTaskSubtitleBranch(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, requeueTaskSubtitleBranch, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const requeueTaskVideoBranch = `-- name: RequeueTaskVideoBranch :one
UPDATE episode_tasks
SET state = 'processing',
    video_state = 'transcode_queued',
    failure_stage = NULL,
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state = 'failed'
  AND video_state = 'failed'
  AND failure_stage = 'video'
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) RequeueTaskVideoBranch(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, requeueTaskVideoBranch, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const startTaskSubtitle = `-- name: StartTaskSubtitle :one
UPDATE episode_tasks
SET state = CASE WHEN state = 'media_queued' THEN 'processing' ELSE state END,
    subtitle_state = 'extracting_or_converting',
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state IN ('media_queued', 'processing', 'failed')
  AND subtitle_state IN ('subtitle_queued', 'extracting_or_converting')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) StartTaskSubtitle(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, startTaskSubtitle, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const startTaskVideo = `-- name: StartTaskVideo :one
UPDATE episode_tasks
SET state = CASE WHEN state = 'media_queued' THEN 'processing' ELSE state END,
    video_state = 'transcoding',
    error_code = NULL,
    error_message = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
  AND state IN ('media_queued', 'processing', 'failed')
  AND video_state IN ('transcode_queued', 'transcoding')
RETURNING id, acquisition_id, source_video_file_id, mapping_id, transcode_profile_id, state, video_state, subtitle_state, version, error_code, error_message, legacy_id, created_at, updated_at, failure_stage, media_type
`

func (q *Queries) StartTaskVideo(ctx context.Context, id pgtype.UUID) (EpisodeTask, error) {
	row := q.db.QueryRow(ctx, startTaskVideo, id)
	var i EpisodeTask
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.SourceVideoFileID,
		&i.MappingID,
		&i.TranscodeProfileID,
		&i.State,
		&i.VideoState,
		&i.SubtitleState,
		&i.Version,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.LegacyID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FailureStage,
		&i.MediaType,
	)
	return i, err
}

const upsertMediaArtifact = `-- name: UpsertMediaArtifact :one
INSERT INTO media_artifacts (
    id,
    task_id,
    source_file_id,
    transcode_profile_id,
    kind,
    basename,
    file_path,
    format,
    size_bytes,
    checksum_sha256,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
ON CONFLICT (task_id, kind) DO UPDATE
SET source_file_id = EXCLUDED.source_file_id,
    transcode_profile_id = EXCLUDED.transcode_profile_id,
    basename = EXCLUDED.basename,
    file_path = EXCLUDED.file_path,
    format = EXCLUDED.format,
    size_bytes = EXCLUDED.size_bytes,
    checksum_sha256 = EXCLUDED.checksum_sha256,
    metadata = EXCLUDED.metadata
RETURNING id, task_id, source_file_id, transcode_profile_id, kind, basename, file_path, format, size_bytes, checksum_sha256, metadata, created_at
`

type UpsertMediaArtifactParams struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	TaskID             pgtype.UUID `db:"task_id" json:"task_id"`
	SourceFileID       pgtype.UUID `db:"source_file_id" json:"source_file_id"`
	TranscodeProfileID pgtype.UUID `db:"transcode_profile_id" json:"transcode_profile_id"`
	Kind               string      `db:"kind" json:"kind"`
	Basename           string      `db:"basename" json:"basename"`
	FilePath           string      `db:"file_path" json:"file_path"`
	Format             string      `db:"format" json:"format"`
	SizeBytes          int64       `db:"size_bytes" json:"size_bytes"`
	ChecksumSha256     []byte      `db:"checksum_sha256" json:"checksum_sha256"`
	Metadata           []byte      `db:"metadata" json:"metadata"`
}

func (q *Queries) UpsertMediaArtifact(ctx context.Context, arg UpsertMediaArtifactParams) (MediaArtifact, error) {
	row := q.db.QueryRow(ctx, upsertMediaArtifact,
		arg.ID,
		arg.TaskID,
		arg.SourceFileID,
		arg.TranscodeProfileID,
		arg.Kind,
		arg.Basename,
		arg.FilePath,
		arg.Format,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.Metadata,
	)
	var i MediaArtifact
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.SourceFileID,
		&i.TranscodeProfileID,
		&i.Kind,
		&i.Basename,
		&i.FilePath,
		&i.Format,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
