// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Acquisition struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SeriesID            pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID    pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	SourceKind          string             `db:"source_kind" json:"source_kind"`
	ReleaseCandidateID  pgtype.UUID        `db:"release_candidate_id" json:"release_candidate_id"`
	RssEntryID          pgtype.UUID        `db:"rss_entry_id" json:"rss_entry_id"`
	SourceUri           *string            `db:"source_uri" json:"source_uri"`
	SourcePayload       []byte             `db:"source_payload" json:"source_payload"`
	LegacyID            *string            `db:"legacy_id" json:"legacy_id"`
	CreatedBy           pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletionRequestedAt pgtype.Timestamptz `db:"deletion_requested_at" json:"deletion_requested_at"`
}

type AdminUser struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Username     string             `db:"username" json:"username"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	Disabled     bool               `db:"disabled" json:"disabled"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AgentResolution struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	OperationID          pgtype.UUID        `db:"operation_id" json:"operation_id"`
	Version              int32              `db:"version" json:"version"`
	Capability           string             `db:"capability" json:"capability"`
	ResourceType         string             `db:"resource_type" json:"resource_type"`
	ResourceID           pgtype.UUID        `db:"resource_id" json:"resource_id"`
	ResourceVersion      *int32             `db:"resource_version" json:"resource_version"`
	Trigger              string             `db:"trigger" json:"trigger"`
	Status               string             `db:"status" json:"status"`
	InputFingerprint     []byte             `db:"input_fingerprint" json:"input_fingerprint"`
	ConfigurationVersion int32              `db:"configuration_version" json:"configuration_version"`
	Protocol             string             `db:"protocol" json:"protocol"`
	ProviderOrigin       string             `db:"provider_origin" json:"provider_origin"`
	Model                string             `db:"model" json:"model"`
	PromptVersion        string             `db:"prompt_version" json:"prompt_version"`
	ToolsetVersion       string             `db:"toolset_version" json:"toolset_version"`
	Proposal             []byte             `db:"proposal" json:"proposal"`
	Validation           []byte             `db:"validation" json:"validation"`
	ErrorCode            *string            `db:"error_code" json:"error_code"`
	ErrorMessage         *string            `db:"error_message" json:"error_message"`
	InputTokens          *int64             `db:"input_tokens" json:"input_tokens"`
	OutputTokens         *int64             `db:"output_tokens" json:"output_tokens"`
	ToolCallCount        int32              `db:"tool_call_count" json:"tool_call_count"`
	LatencyMilliseconds  *int64             `db:"latency_milliseconds" json:"latency_milliseconds"`
	CreatedBy            pgtype.UUID        `db:"created_by" json:"created_by"`
	ReviewedBy           pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewDecision       *string            `db:"review_decision" json:"review_decision"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt            pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	ReviewedAt           pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	AppliedAt            pgtype.Timestamptz `db:"applied_at" json:"applied_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AgentResolutionStep struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	ResolutionID         pgtype.UUID        `db:"resolution_id" json:"resolution_id"`
	Sequence             int32              `db:"sequence" json:"sequence"`
	ToolName             string             `db:"tool_name" json:"tool_name"`
	Status               string             `db:"status" json:"status"`
	ArgumentsDigest      []byte             `db:"arguments_digest" json:"arguments_digest"`
	ResultDigest         []byte             `db:"result_digest" json:"result_digest"`
	DurationMilliseconds *int64             `db:"duration_milliseconds" json:"duration_milliseconds"`
	ErrorCode            *string            `db:"error_code" json:"error_code"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AppSecret struct {
	Name       string             `db:"name" json:"name"`
	Ciphertext []byte             `db:"ciphertext" json:"ciphertext"`
	Nonce      []byte             `db:"nonce" json:"nonce"`
	MaskedHint string             `db:"masked_hint" json:"masked_hint"`
	Version    int32              `db:"version" json:"version"`
	UpdatedBy  pgtype.UUID        `db:"updated_by" json:"updated_by"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AppSetting struct {
	Name      string             `db:"name" json:"name"`
	Value     []byte             `db:"value" json:"value"`
	Version   int32              `db:"version" json:"version"`
	UpdatedBy pgtype.UUID        `db:"updated_by" json:"updated_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ArtifactSet struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	TaskID             pgtype.UUID        `db:"task_id" json:"task_id"`
	TranscodeProfileID pgtype.UUID        `db:"transcode_profile_id" json:"transcode_profile_id"`
	Basename           string             `db:"basename" json:"basename"`
	VideoArtifactID    pgtype.UUID        `db:"video_artifact_id" json:"video_artifact_id"`
	SubtitleArtifactID pgtype.UUID        `db:"subtitle_artifact_id" json:"subtitle_artifact_id"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CleanupRun struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	TaskID             pgtype.UUID        `db:"task_id" json:"task_id"`
	DownloadID         pgtype.UUID        `db:"download_id" json:"download_id"`
	Attempt            int32              `db:"attempt" json:"attempt"`
	Status             string             `db:"status" json:"status"`
	TorrentRemoved     bool               `db:"torrent_removed" json:"torrent_removed"`
	StagedFilesRemoved bool               `db:"staged_files_removed" json:"staged_files_removed"`
	ErrorCode          *string            `db:"error_code" json:"error_code"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	StartedAt          pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt        pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ConnectivityTestResult struct {
	Target   string             `db:"target" json:"target"`
	Success  bool               `db:"success" json:"success"`
	Code     string             `db:"code" json:"code"`
	Message  string             `db:"message" json:"message"`
	TestedAt pgtype.Timestamptz `db:"tested_at" json:"tested_at"`
}

type Download struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	AcquisitionID        pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	Attempt              int32              `db:"attempt" json:"attempt"`
	ClientName           string             `db:"client_name" json:"client_name"`
	TorrentHash          *string            `db:"torrent_hash" json:"torrent_hash"`
	Status               string             `db:"status" json:"status"`
	Progress             pgtype.Numeric     `db:"progress" json:"progress"`
	SavePath             *string            `db:"save_path" json:"save_path"`
	ErrorCode            *string            `db:"error_code" json:"error_code"`
	ErrorMessage         *string            `db:"error_message" json:"error_message"`
	StartedAt            pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Version              int32              `db:"version" json:"version"`
	FailureStage         *string            `db:"failure_stage" json:"failure_stage"`
	ClientState          *string            `db:"client_state" json:"client_state"`
	LastSyncedAt         pgtype.Timestamptz `db:"last_synced_at" json:"last_synced_at"`
	DeletionRequestedAt  pgtype.Timestamptz `db:"deletion_requested_at" json:"deletion_requested_at"`
	DeletedAt            pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	FileResolutionSource *string            `db:"file_resolution_source" json:"file_resolution_source"`
	AgentResolutionID    pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
}

type DownloadFile struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	DownloadID    pgtype.UUID        `db:"download_id" json:"download_id"`
	FileIndex     int32              `db:"file_index" json:"file_index"`
	RelativePath  string             `db:"relative_path" json:"relative_path"`
	SizeBytes     int64              `db:"size_bytes" json:"size_bytes"`
	MediaKind     string             `db:"media_kind" json:"media_kind"`
	Selected      bool               `db:"selected" json:"selected"`
	SourceSeason  *int32             `db:"source_season" json:"source_season"`
	SourceEpisode *int32             `db:"source_episode" json:"source_episode"`
	Language      *string            `db:"language" json:"language"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmbyLibrary struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	EmbyID          string             `db:"emby_id" json:"emby_id"`
	Name            string             `db:"name" json:"name"`
	CollectionType  *string            `db:"collection_type" json:"collection_type"`
	Locations       []string           `db:"locations" json:"locations"`
	Present         bool               `db:"present" json:"present"`
	LastScanRunID   pgtype.UUID        `db:"last_scan_run_id" json:"last_scan_run_id"`
	LastSeenAt      pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmbyLibraryItem struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	EmbyID          string             `db:"emby_id" json:"emby_id"`
	LibraryID       pgtype.UUID        `db:"library_id" json:"library_id"`
	ParentEmbyID    *string            `db:"parent_emby_id" json:"parent_emby_id"`
	ItemType        string             `db:"item_type" json:"item_type"`
	Name            string             `db:"name" json:"name"`
	FilePath        *string            `db:"file_path" json:"file_path"`
	ProviderIds     []byte             `db:"provider_ids" json:"provider_ids"`
	SeasonNumber    *int32             `db:"season_number" json:"season_number"`
	EpisodeNumber   *int32             `db:"episode_number" json:"episode_number"`
	Present         bool               `db:"present" json:"present"`
	LastScanRunID   pgtype.UUID        `db:"last_scan_run_id" json:"last_scan_run_id"`
	LastSeenAt      pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EmbyScanRun struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	OperationID  pgtype.UUID        `db:"operation_id" json:"operation_id"`
	Status       string             `db:"status" json:"status"`
	LibraryCount int32              `db:"library_count" json:"library_count"`
	ItemCount    int32              `db:"item_count" json:"item_count"`
	ErrorCode    *string            `db:"error_code" json:"error_code"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedBy    pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EpisodeMapping struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	ProfileID       pgtype.UUID        `db:"profile_id" json:"profile_id"`
	SourceSeason    int32              `db:"source_season" json:"source_season"`
	SourceEpisode   int32              `db:"source_episode" json:"source_episode"`
	AbsoluteEpisode *int32             `db:"absolute_episode" json:"absolute_episode"`
	TargetEpisodeID pgtype.UUID        `db:"target_episode_id" json:"target_episode_id"`
	MappingStatus   string             `db:"mapping_status" json:"mapping_status"`
	MatchSource     string             `db:"match_source" json:"match_source"`
	ErrorCode       *string            `db:"error_code" json:"error_code"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type EpisodeMappingProfile struct {
	ID                    pgtype.UUID        `db:"id" json:"id"`
	SeriesID              pgtype.UUID        `db:"series_id" json:"series_id"`
	Name                  string             `db:"name" json:"name"`
	Version               int32              `db:"version" json:"version"`
	SourceSeasonLengths   []int32            `db:"source_season_lengths" json:"source_season_lengths"`
	Active                bool               `db:"active" json:"active"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy             pgtype.UUID        `db:"created_by" json:"created_by"`
	AnchorSourceSeason    *int32             `db:"anchor_source_season" json:"anchor_source_season"`
	AnchorSourceEpisode   *int32             `db:"anchor_source_episode" json:"anchor_source_episode"`
	AnchorTargetEpisodeID pgtype.UUID        `db:"anchor_target_episode_id" json:"anchor_target_episode_id"`
	TargetEpisodeOffset   *int32             `db:"target_episode_offset" json:"target_episode_offset"`
	DecisionSource        string             `db:"decision_source" json:"decision_source"`
	AgentResolutionID     pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
}

type EpisodeMappingSafe struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	AcquisitionID      pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	ProfileID          pgtype.UUID        `db:"profile_id" json:"profile_id"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	RequestFingerprint []byte             `db:"request_fingerprint" json:"request_fingerprint"`
	ResultPayload      []byte             `db:"result_payload" json:"result_payload"`
	CreatedBy          pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	DecisionSource     string             `db:"decision_source" json:"decision_source"`
	AgentResolutionID  pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
}

type EpisodeTask struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	AcquisitionID      pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	SourceVideoFileID  pgtype.UUID        `db:"source_video_file_id" json:"source_video_file_id"`
	MappingID          pgtype.UUID        `db:"mapping_id" json:"mapping_id"`
	TranscodeProfileID pgtype.UUID        `db:"transcode_profile_id" json:"transcode_profile_id"`
	State              string             `db:"state" json:"state"`
	VideoState         string             `db:"video_state" json:"video_state"`
	SubtitleState      string             `db:"subtitle_state" json:"subtitle_state"`
	Version            int32              `db:"version" json:"version"`
	ErrorCode          *string            `db:"error_code" json:"error_code"`
	ErrorMessage       *string            `db:"error_message" json:"error_message"`
	LegacyID           *string            `db:"legacy_id" json:"legacy_id"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	FailureStage       *string            `db:"failure_stage" json:"failure_stage"`
	MediaType          string             `db:"media_type" json:"media_type"`
}

type Event struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	EventSequence *int64             `db:"event_sequence" json:"event_sequence"`
	Topic         string             `db:"topic" json:"topic"`
	ResourceType  *string            `db:"resource_type" json:"resource_type"`
	ResourceID    pgtype.UUID        `db:"resource_id" json:"resource_id"`
	OperationID   pgtype.UUID        `db:"operation_id" json:"operation_id"`
	ActorUserID   pgtype.UUID        `db:"actor_user_id" json:"actor_user_id"`
	Data          []byte             `db:"data" json:"data"`
	OccurredAt    pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

type Import struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	TaskID                  pgtype.UUID        `db:"task_id" json:"task_id"`
	Attempt                 int32              `db:"attempt" json:"attempt"`
	Status                  string             `db:"status" json:"status"`
	DestinationVideoPath    *string            `db:"destination_video_path" json:"destination_video_path"`
	DestinationSubtitlePath *string            `db:"destination_subtitle_path" json:"destination_subtitle_path"`
	ErrorCode               *string            `db:"error_code" json:"error_code"`
	ErrorMessage            *string            `db:"error_message" json:"error_message"`
	StartedAt               pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt             pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type InstallationState struct {
	ID          bool               `db:"id" json:"id"`
	CompletedBy pgtype.UUID        `db:"completed_by" json:"completed_by"`
	CompletedAt pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type LegacyMigrationItem struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	SourceKind     string             `db:"source_kind" json:"source_kind"`
	LegacyID       string             `db:"legacy_id" json:"legacy_id"`
	Fingerprint    []byte             `db:"fingerprint" json:"fingerprint"`
	MigrationRunID pgtype.UUID        `db:"migration_run_id" json:"migration_run_id"`
	Status         string             `db:"status" json:"status"`
	ResourceType   *string            `db:"resource_type" json:"resource_type"`
	ResourceID     pgtype.UUID        `db:"resource_id" json:"resource_id"`
	ErrorCode      *string            `db:"error_code" json:"error_code"`
	ErrorMessage   *string            `db:"error_message" json:"error_message"`
	LegacyPayload  []byte             `db:"legacy_payload" json:"legacy_payload"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type LegacyMigrationRun struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	SourceKind        string             `db:"source_kind" json:"source_kind"`
	SourceFingerprint []byte             `db:"source_fingerprint" json:"source_fingerprint"`
	Status            string             `db:"status" json:"status"`
	Counts            []byte             `db:"counts" json:"counts"`
	ErrorCode         *string            `db:"error_code" json:"error_code"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt       pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

type MediaArtifact struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	TaskID             pgtype.UUID        `db:"task_id" json:"task_id"`
	SourceFileID       pgtype.UUID        `db:"source_file_id" json:"source_file_id"`
	TranscodeProfileID pgtype.UUID        `db:"transcode_profile_id" json:"transcode_profile_id"`
	Kind               string             `db:"kind" json:"kind"`
	Basename           string             `db:"basename" json:"basename"`
	FilePath           string             `db:"file_path" json:"file_path"`
	Format             string             `db:"format" json:"format"`
	SizeBytes          int64              `db:"size_bytes" json:"size_bytes"`
	ChecksumSha256     []byte             `db:"checksum_sha256" json:"checksum_sha256"`
	Metadata           []byte             `db:"metadata" json:"metadata"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MediaEpisode struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SeasonID        pgtype.UUID        `db:"season_id" json:"season_id"`
	TmdbEpisodeID   *int64             `db:"tmdb_episode_id" json:"tmdb_episode_id"`
	EpisodeNumber   int32              `db:"episode_number" json:"episode_number"`
	Title           string             `db:"title" json:"title"`
	AirDate         pgtype.Date        `db:"air_date" json:"air_date"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MediaSeries struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	TmdbSeriesID  *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
	Title         string             `db:"title" json:"title"`
	OriginalTitle *string            `db:"original_title" json:"original_title"`
	MediaType     string             `db:"media_type" json:"media_type"`
	Metadata      []byte             `db:"metadata" json:"metadata"`
	LegacyID      *string            `db:"legacy_id" json:"legacy_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	TmdbMovieID   *int64             `db:"tmdb_movie_id" json:"tmdb_movie_id"`
	ReleaseYear   *int32             `db:"release_year" json:"release_year"`
}

type Operation struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Kind              string             `db:"kind" json:"kind"`
	ResourceType      *string            `db:"resource_type" json:"resource_type"`
	ResourceID        pgtype.UUID        `db:"resource_id" json:"resource_id"`
	IdempotencyKey    string             `db:"idempotency_key" json:"idempotency_key"`
	Status            string             `db:"status" json:"status"`
	RiverJobID        *int64             `db:"river_job_id" json:"river_job_id"`
	MaxAttempts       int32              `db:"max_attempts" json:"max_attempts"`
	AttemptCount      int32              `db:"attempt_count" json:"attempt_count"`
	TimeoutSeconds    int32              `db:"timeout_seconds" json:"timeout_seconds"`
	CancelRequestedAt pgtype.Timestamptz `db:"cancel_requested_at" json:"cancel_requested_at"`
	HeartbeatAt       pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	ErrorCode         *string            `db:"error_code" json:"error_code"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	Payload           []byte             `db:"payload" json:"payload"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StartedAt         pgtype.Timestamptz `db:"started_at" json:"started_at"`
	FinishedAt        pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OperationAttempt struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	OperationID  pgtype.UUID        `db:"operation_id" json:"operation_id"`
	Attempt      int32              `db:"attempt" json:"attempt"`
	Status       string             `db:"status" json:"status"`
	WorkerID     *string            `db:"worker_id" json:"worker_id"`
	ErrorCode    *string            `db:"error_code" json:"error_code"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	HeartbeatAt  pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	FinishedAt   pgtype.Timestamptz `db:"finished_at" json:"finished_at"`
}

type ReleaseCandidate struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SearchRunID     pgtype.UUID        `db:"search_run_id" json:"search_run_id"`
	Provider        string             `db:"provider" json:"provider"`
	IdentityKey     string             `db:"identity_key" json:"identity_key"`
	Title           string             `db:"title" json:"title"`
	DownloadUri     *string            `db:"download_uri" json:"download_uri"`
	PublishedAt     pgtype.Timestamptz `db:"published_at" json:"published_at"`
	SizeBytes       *int64             `db:"size_bytes" json:"size_bytes"`
	Seeders         *int32             `db:"seeders" json:"seeders"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Review struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	TaskID              pgtype.UUID        `db:"task_id" json:"task_id"`
	Decision            string             `db:"decision" json:"decision"`
	Notes               string             `db:"notes" json:"notes"`
	ReviewedBy          pgtype.UUID        `db:"reviewed_by" json:"reviewed_by"`
	ReviewedAt          pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	IdempotencyKey      string             `db:"idempotency_key" json:"idempotency_key"`
	ExpectedTaskVersion int32              `db:"expected_task_version" json:"expected_task_version"`
}

type RssAcquisitionProvenance struct {
	AcquisitionID               pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	RssEntryID                  pgtype.UUID        `db:"rss_entry_id" json:"rss_entry_id"`
	DownloadID                  pgtype.UUID        `db:"download_id" json:"download_id"`
	DownloadAttempt             *int32             `db:"download_attempt" json:"download_attempt"`
	TaskID                      pgtype.UUID        `db:"task_id" json:"task_id"`
	AcquisitionCreatedAt        pgtype.Timestamptz `db:"acquisition_created_at" json:"acquisition_created_at"`
	TaskCreatedAt               pgtype.Timestamptz `db:"task_created_at" json:"task_created_at"`
	VideoReadyAt                pgtype.Timestamptz `db:"video_ready_at" json:"video_ready_at"`
	SubtitleReadyAt             pgtype.Timestamptz `db:"subtitle_ready_at" json:"subtitle_ready_at"`
	ArtifactReadyAt             pgtype.Timestamptz `db:"artifact_ready_at" json:"artifact_ready_at"`
	ReviewedAt                  pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ImportedAt                  pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	ArchivedAt                  pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	PendingDownloadID           pgtype.UUID        `db:"pending_download_id" json:"pending_download_id"`
	PendingDownloadAttempt      *int32             `db:"pending_download_attempt" json:"pending_download_attempt"`
	PendingEnqueueAt            pgtype.Timestamptz `db:"pending_enqueue_at" json:"pending_enqueue_at"`
	PendingEnqueueEventSequence *int64             `db:"pending_enqueue_event_sequence" json:"pending_enqueue_event_sequence"`
	PendingTaskID               pgtype.UUID        `db:"pending_task_id" json:"pending_task_id"`
	PendingTaskCreatedAt        pgtype.Timestamptz `db:"pending_task_created_at" json:"pending_task_created_at"`
	PendingVideoReadyAt         pgtype.Timestamptz `db:"pending_video_ready_at" json:"pending_video_ready_at"`
	PendingSubtitleReadyAt      pgtype.Timestamptz `db:"pending_subtitle_ready_at" json:"pending_subtitle_ready_at"`
	PendingArtifactReadyAt      pgtype.Timestamptz `db:"pending_artifact_ready_at" json:"pending_artifact_ready_at"`
	PendingReviewedAt           pgtype.Timestamptz `db:"pending_reviewed_at" json:"pending_reviewed_at"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RssAdjudicationBatch struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	Status         string             `db:"status" json:"status"`
	EntryCount     int32              `db:"entry_count" json:"entry_count"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RssEntry struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID     pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	ReleaseCandidateID pgtype.UUID        `db:"release_candidate_id" json:"release_candidate_id"`
	IdentityKey        string             `db:"identity_key" json:"identity_key"`
	Guid               *string            `db:"guid" json:"guid"`
	Btih               *string            `db:"btih" json:"btih"`
	CanonicalUrl       *string            `db:"canonical_url" json:"canonical_url"`
	Title              string             `db:"title" json:"title"`
	PublishedAt        pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Status             string             `db:"status" json:"status"`
	EnqueueAttempts    int32              `db:"enqueue_attempts" json:"enqueue_attempts"`
	LastErrorCode      *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage   *string            `db:"last_error_message" json:"last_error_message"`
	UpstreamPayload    []byte             `db:"upstream_payload" json:"upstream_payload"`
	DiscoveredAt       pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
	EnqueuedAt         pgtype.Timestamptz `db:"enqueued_at" json:"enqueued_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DownloadUri        *string            `db:"download_uri" json:"download_uri"`
	Downloadable       bool               `db:"downloadable" json:"downloadable"`
	RejectionReasons   []string           `db:"rejection_reasons" json:"rejection_reasons"`
	SourceSeason       *int32             `db:"source_season" json:"source_season"`
	SourceEpisode      *int32             `db:"source_episode" json:"source_episode"`
	DuplicateCount     int32              `db:"duplicate_count" json:"duplicate_count"`
	LastErrorRetryable bool               `db:"last_error_retryable" json:"last_error_retryable"`
	ImportedAt         pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	CoordinateSource   *string            `db:"coordinate_source" json:"coordinate_source"`
	AgentResolutionID  pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
	FulfillmentSource  *string            `db:"fulfillment_source" json:"fulfillment_source"`
}

type RssEntryAdjudication struct {
	EntryID        pgtype.UUID        `db:"entry_id" json:"entry_id"`
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	BatchID        pgtype.UUID        `db:"batch_id" json:"batch_id"`
	State          string             `db:"state" json:"state"`
	Source         *string            `db:"source" json:"source"`
	ResolutionID   pgtype.UUID        `db:"resolution_id" json:"resolution_id"`
	RelatedEntryID pgtype.UUID        `db:"related_entry_id" json:"related_entry_id"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RssFeedCatalogLookup struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	FeedTitle        string             `db:"feed_title" json:"feed_title"`
	SuggestedQueries []string           `db:"suggested_queries" json:"suggested_queries"`
	SampleTitles     []string           `db:"sample_titles" json:"sample_titles"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type RssPreacquisitionMappingScope struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID      pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	SubscriptionVersion int32              `db:"subscription_version" json:"subscription_version"`
	SourceFingerprint   []byte             `db:"source_fingerprint" json:"source_fingerprint"`
	Status              string             `db:"status" json:"status"`
	AppliedProfileID    pgtype.UUID        `db:"applied_profile_id" json:"applied_profile_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RssPreacquisitionMappingSource struct {
	ScopeID       pgtype.UUID        `db:"scope_id" json:"scope_id"`
	EntryID       pgtype.UUID        `db:"entry_id" json:"entry_id"`
	SourceSeason  int32              `db:"source_season" json:"source_season"`
	SourceEpisode int32              `db:"source_episode" json:"source_episode"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type RssSubscription struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	SeriesID                  pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID          pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	Name                      string             `db:"name" json:"name"`
	FeedUrl                   string             `db:"feed_url" json:"feed_url"`
	Enabled                   bool               `db:"enabled" json:"enabled"`
	PollIntervalSeconds       int32              `db:"poll_interval_seconds" json:"poll_interval_seconds"`
	LastPolledAt              pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	NextPollAt                pgtype.Timestamptz `db:"next_poll_at" json:"next_poll_at"`
	Version                   int32              `db:"version" json:"version"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SourceSeason              int32              `db:"source_season" json:"source_season"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	AutoReview                bool               `db:"auto_review" json:"auto_review"`
	CleanupSourceOnCompletion bool               `db:"cleanup_source_on_completion" json:"cleanup_source_on_completion"`
	CompletedAt               pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	IncludeKeywords           []string           `db:"include_keywords" json:"include_keywords"`
	ExcludeKeywords           []string           `db:"exclude_keywords" json:"exclude_keywords"`
	AutoEpisodeMapping        bool               `db:"auto_episode_mapping" json:"auto_episode_mapping"`
}

type RssSubscriptionProgress struct {
	SubscriptionID       pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	OverallProgress      float64            `db:"overall_progress" json:"overall_progress"`
	TaskCount            int32              `db:"task_count" json:"task_count"`
	CompletedTaskCount   int32              `db:"completed_task_count" json:"completed_task_count"`
	AttentionTaskCount   int32              `db:"attention_task_count" json:"attention_task_count"`
	SourceRevision       int64              `db:"source_revision" json:"source_revision"`
	CalculatedRevision   int64              `db:"calculated_revision" json:"calculated_revision"`
	ModelVersion         int32              `db:"model_version" json:"model_version"`
	Dirty                bool               `db:"dirty" json:"dirty"`
	DirtiedTransactionID int64              `db:"dirtied_transaction_id" json:"dirtied_transaction_id"`
	DirtiedAt            pgtype.Timestamptz `db:"dirtied_at" json:"dirtied_at"`
	CalculatedAt         pgtype.Timestamptz `db:"calculated_at" json:"calculated_at"`
}

type RssTargetFulfillment struct {
	RssEntryID      pgtype.UUID        `db:"rss_entry_id" json:"rss_entry_id"`
	TargetEpisodeID pgtype.UUID        `db:"target_episode_id" json:"target_episode_id"`
	Source          string             `db:"source" json:"source"`
	TaskID          pgtype.UUID        `db:"task_id" json:"task_id"`
	VerifiedAt      pgtype.Timestamptz `db:"verified_at" json:"verified_at"`
	InvalidatedAt   pgtype.Timestamptz `db:"invalidated_at" json:"invalidated_at"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RssTargetRealtimeCheck struct {
	TargetEpisodeID pgtype.UUID        `db:"target_episode_id" json:"target_episode_id"`
	CheckID         pgtype.UUID        `db:"check_id" json:"check_id"`
	Present         bool               `db:"present" json:"present"`
	MatchSource     string             `db:"match_source" json:"match_source"`
	CheckedAt       pgtype.Timestamptz `db:"checked_at" json:"checked_at"`
}

type SearchRun struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Query        string             `db:"query" json:"query"`
	Status       string             `db:"status" json:"status"`
	RequestedBy  pgtype.UUID        `db:"requested_by" json:"requested_by"`
	ErrorCode    *string            `db:"error_code" json:"error_code"`
	ErrorMessage *string            `db:"error_message" json:"error_message"`
	StartedAt    pgtype.Timestamptz `db:"started_at" json:"started_at"`
	CompletedAt  pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	AdminUserID pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	TokenHash   []byte             `db:"token_hash" json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastSeenAt  pgtype.Timestamptz `db:"last_seen_at" json:"last_seen_at"`
	RevokedAt   pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SubtitleVideoMatchCandidate struct {
	ScopeID     pgtype.UUID        `db:"scope_id" json:"scope_id"`
	CandidateID string             `db:"candidate_id" json:"candidate_id"`
	Source      string             `db:"source" json:"source"`
	StreamIndex *int32             `db:"stream_index" json:"stream_index"`
	Format      *string            `db:"format" json:"format"`
	Language    *string            `db:"language" json:"language"`
	Title       *string            `db:"title" json:"title"`
	Path        *string            `db:"path" json:"path"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type SubtitleVideoMatchScope struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	TaskID              pgtype.UUID        `db:"task_id" json:"task_id"`
	Status              string             `db:"status" json:"status"`
	SelectedCandidateID *string            `db:"selected_candidate_id" json:"selected_candidate_id"`
	AgentResolutionID   pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TmdbSeason struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SeriesID        pgtype.UUID        `db:"series_id" json:"series_id"`
	TmdbSeasonID    *int64             `db:"tmdb_season_id" json:"tmdb_season_id"`
	SeasonNumber    int32              `db:"season_number" json:"season_number"`
	Name            *string            `db:"name" json:"name"`
	EpisodeCount    int32              `db:"episode_count" json:"episode_count"`
	FetchedAt       pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
	UpstreamPayload []byte             `db:"upstream_payload" json:"upstream_payload"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type TranscodeProfile struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	Version        int32              `db:"version" json:"version"`
	Active         bool               `db:"active" json:"active"`
	IsDefault      bool               `db:"is_default" json:"is_default"`
	VideoCodec     string             `db:"video_codec" json:"video_codec"`
	Encoder        string             `db:"encoder" json:"encoder"`
	Container      string             `db:"container" json:"container"`
	FileExtension  string             `db:"file_extension" json:"file_extension"`
	QualityMode    string             `db:"quality_mode" json:"quality_mode"`
	QualityValue   pgtype.Numeric     `db:"quality_value" json:"quality_value"`
	AudioPolicy    string             `db:"audio_policy" json:"audio_policy"`
	AudioCodec     *string            `db:"audio_codec" json:"audio_codec"`
	Preset         string             `db:"preset" json:"preset"`
	PixelFormat    string             `db:"pixel_format" json:"pixel_format"`
	ThreadCount    int32              `db:"thread_count" json:"thread_count"`
	MaxConcurrency int32              `db:"max_concurrency" json:"max_concurrency"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy      pgtype.UUID        `db:"created_by" json:"created_by"`
}
