// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const abandonRunningOperationAttempts = `-- name: AbandonRunningOperationAttempts :execrows
UPDATE operation_attempts
SET status = 'failed',
    error_code = 'worker_interrupted',
    error_message = 'the previous worker stopped before finishing the attempt',
    heartbeat_at = now(),
    finished_at = now()
WHERE operation_id = $1
  AND status = 'running'
`

func (q *Queries) AbandonRunningOperationAttempts(ctx context.Context, operationID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, abandonRunningOperationAttempts, operationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const attachRiverJob = `-- name: AttachRiverJob :one
UPDATE operations
SET river_job_id = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'queued'
  AND river_job_id IS NULL
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

type AttachRiverJobParams struct {
	RiverJobID *int64      `db:"river_job_id" json:"river_job_id"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) AttachRiverJob(ctx context.Context, arg AttachRiverJobParams) (Operation, error) {
	row := q.db.QueryRow(ctx, attachRiverJob, arg.RiverJobID, arg.ID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelOperation = `-- name: CancelOperation :one
UPDATE operations
SET status = 'cancelled',
    cancel_requested_at = COALESCE(cancel_requested_at, now()),
    heartbeat_at = CASE WHEN status = 'running' THEN now() ELSE heartbeat_at END,
    finished_at = now(),
    updated_at = now()
WHERE id = $1
  AND status IN ('queued', 'running')
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

func (q *Queries) CancelOperation(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, cancelOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeOperation = `-- name: CompleteOperation :one
UPDATE operations
SET status = 'succeeded',
    heartbeat_at = now(),
    finished_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND cancel_requested_at IS NULL
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

func (q *Queries) CompleteOperation(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, completeOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOtherActiveResourceOperations = `-- name: CountOtherActiveResourceOperations :one
SELECT count(*)::bigint
FROM operations
WHERE resource_type = $1
  AND resource_id = $2
  AND id <> $3
  AND status IN ('queued', 'running')
`

type CountOtherActiveResourceOperationsParams struct {
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	OperationID  pgtype.UUID `db:"operation_id" json:"operation_id"`
}

func (q *Queries) CountOtherActiveResourceOperations(ctx context.Context, arg CountOtherActiveResourceOperationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherActiveResourceOperations, arg.ResourceType, arg.ResourceID, arg.OperationID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createOperation = `-- name: CreateOperation :execrows
INSERT INTO operations (
    id,
    kind,
    resource_type,
    resource_id,
    idempotency_key,
    max_attempts,
    timeout_seconds,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (idempotency_key) DO NOTHING
`

type CreateOperationParams struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	Kind           string      `db:"kind" json:"kind"`
	ResourceType   *string     `db:"resource_type" json:"resource_type"`
	ResourceID     pgtype.UUID `db:"resource_id" json:"resource_id"`
	IdempotencyKey string      `db:"idempotency_key" json:"idempotency_key"`
	MaxAttempts    int32       `db:"max_attempts" json:"max_attempts"`
	TimeoutSeconds int32       `db:"timeout_seconds" json:"timeout_seconds"`
	Payload        []byte      `db:"payload" json:"payload"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (int64, error) {
	result, err := q.db.Exec(ctx, createOperation,
		arg.ID,
		arg.Kind,
		arg.ResourceType,
		arg.ResourceID,
		arg.IdempotencyKey,
		arg.MaxAttempts,
		arg.TimeoutSeconds,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createOperationAttempt = `-- name: CreateOperationAttempt :one
INSERT INTO operation_attempts (
    id,
    operation_id,
    attempt,
    status,
    worker_id
) VALUES (
    $1,
    $2,
    $3,
    'running',
    $4
)
RETURNING id, operation_id, attempt, status, worker_id, error_code, error_message, started_at, heartbeat_at, finished_at
`

type CreateOperationAttemptParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	OperationID pgtype.UUID `db:"operation_id" json:"operation_id"`
	Attempt     int32       `db:"attempt" json:"attempt"`
	WorkerID    *string     `db:"worker_id" json:"worker_id"`
}

func (q *Queries) CreateOperationAttempt(ctx context.Context, arg CreateOperationAttemptParams) (OperationAttempt, error) {
	row := q.db.QueryRow(ctx, createOperationAttempt,
		arg.ID,
		arg.OperationID,
		arg.Attempt,
		arg.WorkerID,
	)
	var i OperationAttempt
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Attempt,
		&i.Status,
		&i.WorkerID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.FinishedAt,
	)
	return i, err
}

const deleteSnoozedOperationAttempt = `-- name: DeleteSnoozedOperationAttempt :execrows
DELETE FROM operation_attempts
WHERE operation_id = $1
  AND attempt = $2
  AND status = 'running'
`

type DeleteSnoozedOperationAttemptParams struct {
	OperationID pgtype.UUID `db:"operation_id" json:"operation_id"`
	Attempt     int32       `db:"attempt" json:"attempt"`
}

func (q *Queries) DeleteSnoozedOperationAttempt(ctx context.Context, arg DeleteSnoozedOperationAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnoozedOperationAttempt, arg.OperationID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failOperation = `-- name: FailOperation :one
UPDATE operations
SET status = 'failed',
    error_code = $1,
    error_message = $2,
    heartbeat_at = now(),
    finished_at = now(),
    updated_at = now()
WHERE id = $3
  AND status IN ('queued', 'running')
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

type FailOperationParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) FailOperation(ctx context.Context, arg FailOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, failOperation, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finishOperationAttempt = `-- name: FinishOperationAttempt :one
UPDATE operation_attempts
SET status = $1,
    error_code = $2,
    error_message = $3,
    heartbeat_at = now(),
    finished_at = now()
WHERE operation_id = $4
  AND attempt = $5
  AND status = 'running'
RETURNING id, operation_id, attempt, status, worker_id, error_code, error_message, started_at, heartbeat_at, finished_at
`

type FinishOperationAttemptParams struct {
	Status       string      `db:"status" json:"status"`
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	OperationID  pgtype.UUID `db:"operation_id" json:"operation_id"`
	Attempt      int32       `db:"attempt" json:"attempt"`
}

func (q *Queries) FinishOperationAttempt(ctx context.Context, arg FinishOperationAttemptParams) (OperationAttempt, error) {
	row := q.db.QueryRow(ctx, finishOperationAttempt,
		arg.Status,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OperationID,
		arg.Attempt,
	)
	var i OperationAttempt
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.Attempt,
		&i.Status,
		&i.WorkerID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.HeartbeatAt,
		&i.FinishedAt,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
FROM operations
WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationByIdempotencyKey = `-- name: GetOperationByIdempotencyKey :one
SELECT id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
FROM operations
WHERE idempotency_key = $1
`

func (q *Queries) GetOperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByIdempotencyKey, idempotencyKey)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const heartbeatOperation = `-- name: HeartbeatOperation :execrows
UPDATE operations
SET heartbeat_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND cancel_requested_at IS NULL
`

func (q *Queries) HeartbeatOperation(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatOperation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const heartbeatOperationAttempt = `-- name: HeartbeatOperationAttempt :execrows
UPDATE operation_attempts
SET heartbeat_at = now()
WHERE operation_id = $1
  AND attempt = $2
  AND status = 'running'
`

type HeartbeatOperationAttemptParams struct {
	OperationID pgtype.UUID `db:"operation_id" json:"operation_id"`
	Attempt     int32       `db:"attempt" json:"attempt"`
}

func (q *Queries) HeartbeatOperationAttempt(ctx context.Context, arg HeartbeatOperationAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatOperationAttempt, arg.OperationID, arg.Attempt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCancellableResourceOperations = `-- name: ListCancellableResourceOperations :many
SELECT id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
FROM operations
WHERE resource_type = $1
  AND resource_id = $2
  AND status IN ('queued', 'running')
ORDER BY created_at, id
FOR UPDATE
`

type ListCancellableResourceOperationsParams struct {
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
}

func (q *Queries) ListCancellableResourceOperations(ctx context.Context, arg ListCancellableResourceOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listCancellableResourceOperations, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ResourceType,
			&i.ResourceID,
			&i.IdempotencyKey,
			&i.Status,
			&i.RiverJobID,
			&i.MaxAttempts,
			&i.AttemptCount,
			&i.TimeoutSeconds,
			&i.CancelRequestedAt,
			&i.HeartbeatAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOperation = `-- name: LockOperation :one
SELECT id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
FROM operations
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockOperation(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, lockOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const requestOperationCancellation = `-- name: RequestOperationCancellation :one
UPDATE operations
SET cancel_requested_at = COALESCE(cancel_requested_at, now()),
    updated_at = now()
WHERE id = $1
  AND status IN ('queued', 'running')
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

func (q *Queries) RequestOperationCancellation(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, requestOperationCancellation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const retryOperation = `-- name: RetryOperation :one
UPDATE operations
SET status = 'queued',
    error_code = $1,
    error_message = $2,
    heartbeat_at = now(),
    updated_at = now()
WHERE id = $3
  AND status = 'running'
  AND cancel_requested_at IS NULL
  AND attempt_count < max_attempts
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

type RetryOperationParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) RetryOperation(ctx context.Context, arg RetryOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, retryOperation, arg.ErrorCode, arg.ErrorMessage, arg.ID)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const snoozeOperation = `-- name: SnoozeOperation :one
UPDATE operations
SET status = 'queued',
    attempt_count = attempt_count - 1,
    heartbeat_at = now(),
    updated_at = now()
WHERE id = $1
  AND status = 'running'
  AND cancel_requested_at IS NULL
  AND attempt_count > 0
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

func (q *Queries) SnoozeOperation(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, snoozeOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startOperationAttempt = `-- name: StartOperationAttempt :one
UPDATE operations
SET status = 'running',
    attempt_count = attempt_count + 1,
    started_at = COALESCE(started_at, now()),
    heartbeat_at = now(),
    error_code = NULL,
    error_message = NULL,
    updated_at = now()
WHERE id = $1
  AND status IN ('queued', 'running')
  AND cancel_requested_at IS NULL
  AND attempt_count < max_attempts
RETURNING id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
`

func (q *Queries) StartOperationAttempt(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, startOperationAttempt, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
