// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_models.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardCleanupFailedCount = `-- name: DashboardCleanupFailedCount :one
SELECT count(*)::bigint
FROM cleanup_runs
WHERE status = 'failed'
`

func (q *Queries) DashboardCleanupFailedCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardCleanupFailedCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardDownloadCounts = `-- name: DashboardDownloadCounts :one
SELECT
    count(*) FILTER (WHERE status IN ('enqueue_pending', 'file_resolution_pending', 'downloading'))::bigint AS downloading,
    count(*) FILTER (
        WHERE status = 'failed'
          AND NOT COALESCE(
              failure_stage = 'materialize'
              AND error_code IN (
                  'mapping_profile_required',
                  'episode_mapping_required',
                  'mapping_source_invalid',
                  'mapping_source_out_of_range',
                  'mapping_context_incomplete',
                  'mapping_target_out_of_range',
                  'mapping_title_missing'
              ),
              false
          )
    )::bigint AS failed
FROM downloads
WHERE deleted_at IS NULL
`

type DashboardDownloadCountsRow struct {
	Downloading int64 `db:"downloading" json:"downloading"`
	Failed      int64 `db:"failed" json:"failed"`
}

func (q *Queries) DashboardDownloadCounts(ctx context.Context) (DashboardDownloadCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardDownloadCounts)
	var i DashboardDownloadCountsRow
	err := row.Scan(&i.Downloading, &i.Failed)
	return i, err
}

const dashboardMappingPendingCount = `-- name: DashboardMappingPendingCount :one
SELECT count(*)::bigint
FROM acquisitions AS acquisition
JOIN media_series AS media ON media.id = acquisition.series_id AND media.media_type = 'tv'
WHERE EXISTS (
    SELECT 1
    FROM downloads AS download
    WHERE download.id = (
          SELECT candidate.id
          FROM downloads AS candidate
          WHERE candidate.acquisition_id = acquisition.id
            AND candidate.deleted_at IS NULL
          ORDER BY (candidate.status = 'cancelled'), candidate.attempt DESC
          LIMIT 1
      )
      AND (
          download.status IN ('completed', 'selecting_files', 'materialized')
          OR (
              download.status = 'failed'
              AND download.failure_stage = 'materialize'
              AND download.error_code IN (
                  'mapping_profile_required',
                  'episode_mapping_required',
                  'mapping_source_invalid',
                  'mapping_source_out_of_range',
                  'mapping_context_incomplete',
                  'mapping_target_out_of_range',
                  'mapping_title_missing'
              )
          )
      )
      AND (
          NOT EXISTS (
              SELECT 1 FROM download_files AS file
              WHERE file.download_id = download.id AND file.selected AND file.media_kind = 'video'
          )
          OR EXISTS (
              SELECT 1
              FROM download_files AS file
              WHERE file.download_id = download.id
                AND file.selected
                AND file.media_kind = 'video'
                AND NOT EXISTS (
                    SELECT 1
                    FROM episode_mappings AS mapping
                    WHERE mapping.profile_id = acquisition.mapping_profile_id
                      AND mapping.source_season = file.source_season
                      AND mapping.source_episode = file.source_episode
                      AND mapping.mapping_status = 'mapped'
                      AND mapping.target_episode_id IS NOT NULL
                )
          )
      )
)
`

func (q *Queries) DashboardMappingPendingCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, dashboardMappingPendingCount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const dashboardRecentImports = `-- name: DashboardRecentImports :many
SELECT
    task.id AS task_id,
    acquisition.id AS acquisition_id,
    task.media_type,
    series.title AS series_title,
    series.release_year,
    season.season_number,
    episode.episode_number,
    latest_import.destination_video_path,
    latest_import.completed_at
FROM imports AS latest_import
JOIN episode_tasks AS task ON task.id = latest_import.task_id
JOIN acquisitions AS acquisition ON acquisition.id = task.acquisition_id
JOIN media_series AS series ON series.id = acquisition.series_id
LEFT JOIN episode_mappings AS mapping ON mapping.id = task.mapping_id
LEFT JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
LEFT JOIN tmdb_seasons AS season ON season.id = episode.season_id
WHERE latest_import.status = 'succeeded'
ORDER BY latest_import.completed_at DESC, latest_import.id DESC
LIMIT $1
`

type DashboardRecentImportsRow struct {
	TaskID               pgtype.UUID        `db:"task_id" json:"task_id"`
	AcquisitionID        pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	MediaType            string             `db:"media_type" json:"media_type"`
	SeriesTitle          string             `db:"series_title" json:"series_title"`
	ReleaseYear          *int32             `db:"release_year" json:"release_year"`
	SeasonNumber         *int32             `db:"season_number" json:"season_number"`
	EpisodeNumber        *int32             `db:"episode_number" json:"episode_number"`
	DestinationVideoPath *string            `db:"destination_video_path" json:"destination_video_path"`
	CompletedAt          pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) DashboardRecentImports(ctx context.Context, rowLimit int32) ([]DashboardRecentImportsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentImports, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardRecentImportsRow{}
	for rows.Next() {
		var i DashboardRecentImportsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.AcquisitionID,
			&i.MediaType,
			&i.SeriesTitle,
			&i.ReleaseYear,
			&i.SeasonNumber,
			&i.EpisodeNumber,
			&i.DestinationVideoPath,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentOperations = `-- name: DashboardRecentOperations :many
SELECT id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
FROM operations
ORDER BY updated_at DESC, id DESC
LIMIT $1
`

func (q *Queries) DashboardRecentOperations(ctx context.Context, rowLimit int32) ([]Operation, error) {
	rows, err := q.db.Query(ctx, dashboardRecentOperations, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ResourceType,
			&i.ResourceID,
			&i.IdempotencyKey,
			&i.Status,
			&i.RiverJobID,
			&i.MaxAttempts,
			&i.AttemptCount,
			&i.TimeoutSeconds,
			&i.CancelRequestedAt,
			&i.HeartbeatAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRecentScans = `-- name: DashboardRecentScans :many
SELECT id, operation_id, status, library_count, item_count, error_code, error_message, started_at, completed_at, created_by, created_at, updated_at
FROM emby_scan_runs
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) DashboardRecentScans(ctx context.Context, rowLimit int32) ([]EmbyScanRun, error) {
	rows, err := q.db.Query(ctx, dashboardRecentScans, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmbyScanRun{}
	for rows.Next() {
		var i EmbyScanRun
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Status,
			&i.LibraryCount,
			&i.ItemCount,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTaskCounts = `-- name: DashboardTaskCounts :one
SELECT
    count(*) FILTER (WHERE state IN ('media_queued', 'processing', 'finalizing'))::bigint AS processing,
    count(*) FILTER (WHERE state = 'awaiting_review')::bigint AS awaiting_review,
    count(*) FILTER (WHERE state IN ('import_queued', 'importing'))::bigint AS importing,
    count(*) FILTER (WHERE state = 'failed')::bigint AS failed
FROM episode_tasks AS task
JOIN download_files AS source_file ON source_file.id = task.source_video_file_id
JOIN downloads AS source_download ON source_download.id = source_file.download_id
WHERE source_download.deleted_at IS NULL
`

type DashboardTaskCountsRow struct {
	Processing     int64 `db:"processing" json:"processing"`
	AwaitingReview int64 `db:"awaiting_review" json:"awaiting_review"`
	Importing      int64 `db:"importing" json:"importing"`
	Failed         int64 `db:"failed" json:"failed"`
}

func (q *Queries) DashboardTaskCounts(ctx context.Context) (DashboardTaskCountsRow, error) {
	row := q.db.QueryRow(ctx, dashboardTaskCounts)
	var i DashboardTaskCountsRow
	err := row.Scan(
		&i.Processing,
		&i.AwaitingReview,
		&i.Importing,
		&i.Failed,
	)
	return i, err
}

const getAcquisitionByID = `-- name: GetAcquisitionByID :one
SELECT id, series_id, mapping_profile_id, source_kind, release_candidate_id, rss_entry_id, source_uri, source_payload, legacy_id, created_by, created_at, updated_at, deletion_requested_at
FROM acquisitions
WHERE acquisitions.id = $1
  AND (
      NOT EXISTS (SELECT 1 FROM downloads WHERE downloads.acquisition_id = acquisitions.id)
      OR EXISTS (SELECT 1 FROM downloads WHERE downloads.acquisition_id = acquisitions.id AND downloads.deleted_at IS NULL)
  )
`

func (q *Queries) GetAcquisitionByID(ctx context.Context, id pgtype.UUID) (Acquisition, error) {
	row := q.db.QueryRow(ctx, getAcquisitionByID, id)
	var i Acquisition
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.MappingProfileID,
		&i.SourceKind,
		&i.ReleaseCandidateID,
		&i.RssEntryID,
		&i.SourceUri,
		&i.SourcePayload,
		&i.LegacyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletionRequestedAt,
	)
	return i, err
}

const getAcquisitionMappingCompleteness = `-- name: GetAcquisitionMappingCompleteness :one
SELECT
    count(file.id)::bigint AS selected_video_count,
    CASE WHEN media.media_type = 'movie' THEN count(file.id)::bigint ELSE
        count(mapping.id) FILTER (
            WHERE mapping.mapping_status = 'mapped' AND mapping.target_episode_id IS NOT NULL
        )::bigint
    END AS mapped_video_count
FROM acquisitions AS acquisition
JOIN media_series AS media ON media.id = acquisition.series_id
LEFT JOIN downloads AS download
    ON download.id = (
        SELECT candidate.id
        FROM downloads AS candidate
        WHERE candidate.acquisition_id = acquisition.id
          AND candidate.deleted_at IS NULL
        ORDER BY (candidate.status = 'cancelled'), candidate.attempt DESC
        LIMIT 1
    )
LEFT JOIN download_files AS file
    ON file.download_id = download.id
   AND file.selected
   AND file.media_kind = 'video'
LEFT JOIN episode_mappings AS mapping
    ON mapping.profile_id = acquisition.mapping_profile_id
   AND mapping.source_season = file.source_season
   AND mapping.source_episode = file.source_episode
WHERE acquisition.id = $1
GROUP BY media.media_type
`

type GetAcquisitionMappingCompletenessRow struct {
	SelectedVideoCount int64 `db:"selected_video_count" json:"selected_video_count"`
	MappedVideoCount   int64 `db:"mapped_video_count" json:"mapped_video_count"`
}

func (q *Queries) GetAcquisitionMappingCompleteness(ctx context.Context, acquisitionID pgtype.UUID) (GetAcquisitionMappingCompletenessRow, error) {
	row := q.db.QueryRow(ctx, getAcquisitionMappingCompleteness, acquisitionID)
	var i GetAcquisitionMappingCompletenessRow
	err := row.Scan(&i.SelectedVideoCount, &i.MappedVideoCount)
	return i, err
}

const getAcquisitionMappingCompletenessByAcquisitionIDs = `-- name: GetAcquisitionMappingCompletenessByAcquisitionIDs :many
SELECT
    acquisition.id,
    count(file.id)::bigint AS selected_video_count,
    CASE WHEN media.media_type = 'movie' THEN count(file.id)::bigint ELSE
        count(mapping.id) FILTER (
            WHERE mapping.mapping_status = 'mapped' AND mapping.target_episode_id IS NOT NULL
        )::bigint
    END AS mapped_video_count
FROM acquisitions AS acquisition
JOIN media_series AS media ON media.id = acquisition.series_id
LEFT JOIN downloads AS download
    ON download.id = (
        SELECT candidate.id
        FROM downloads AS candidate
        WHERE candidate.acquisition_id = acquisition.id
          AND candidate.deleted_at IS NULL
        ORDER BY (candidate.status = 'cancelled'), candidate.attempt DESC
        LIMIT 1
    )
LEFT JOIN download_files AS file
    ON file.download_id = download.id
   AND file.selected
   AND file.media_kind = 'video'
LEFT JOIN episode_mappings AS mapping
    ON mapping.profile_id = acquisition.mapping_profile_id
   AND mapping.source_season = file.source_season
   AND mapping.source_episode = file.source_episode
WHERE acquisition.id = ANY($1::uuid[])
GROUP BY acquisition.id, media.media_type
`

type GetAcquisitionMappingCompletenessByAcquisitionIDsRow struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	SelectedVideoCount int64       `db:"selected_video_count" json:"selected_video_count"`
	MappedVideoCount   int64       `db:"mapped_video_count" json:"mapped_video_count"`
}

func (q *Queries) GetAcquisitionMappingCompletenessByAcquisitionIDs(ctx context.Context, acquisitionIds []pgtype.UUID) ([]GetAcquisitionMappingCompletenessByAcquisitionIDsRow, error) {
	rows, err := q.db.Query(ctx, getAcquisitionMappingCompletenessByAcquisitionIDs, acquisitionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAcquisitionMappingCompletenessByAcquisitionIDsRow{}
	for rows.Next() {
		var i GetAcquisitionMappingCompletenessByAcquisitionIDsRow
		if err := rows.Scan(&i.ID, &i.SelectedVideoCount, &i.MappedVideoCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedRSSAcquisitionByID = `-- name: GetArchivedRSSAcquisitionByID :one
WITH successful_history AS (
    SELECT DISTINCT ON (enqueue.resource_id)
        enqueue.resource_id AS entry_id,
        (enqueue.data->>'acquisitionId')::uuid AS acquisition_id,
        (enqueue.data->>'downloadId')::uuid AS download_id,
        enqueue.occurred_at AS acquisition_created_at,
        created.resource_id AS task_id,
        created.occurred_at AS task_created_at,
        imported.occurred_at AS imported_at
    FROM events AS enqueue
    JOIN rss_entries AS entry
      ON entry.id = enqueue.resource_id
     AND entry.imported_at IS NOT NULL
    JOIN events AS created
      ON created.resource_type = 'episode_task'
     AND created.topic = 'task.created'
     AND created.data->>'downloadId' = enqueue.data->>'downloadId'
    JOIN events AS imported
      ON imported.resource_type = 'episode_task'
     AND imported.resource_id = created.resource_id
     AND imported.topic = 'task.imported'
    WHERE enqueue.resource_type = 'rss_entry'
      AND enqueue.topic = 'rss.entry.enqueueing'
      AND enqueue.data ? 'acquisitionId'
      AND enqueue.data ? 'downloadId'
      AND (enqueue.data->>'acquisitionId')::uuid = $1::uuid
    ORDER BY enqueue.resource_id, imported.occurred_at DESC, enqueue.occurred_at DESC
), task_milestones AS (
    SELECT
        event.resource_id AS task_id,
        max(event.occurred_at) FILTER (WHERE event.topic = 'task.video_ready')::timestamptz AS video_ready_at,
        max(event.occurred_at) FILTER (WHERE event.topic = 'task.subtitle_ready')::timestamptz AS subtitle_ready_at,
        max(event.occurred_at) FILTER (WHERE event.topic = 'task.awaiting_review')::timestamptz AS artifact_ready_at,
        max(event.occurred_at) FILTER (WHERE event.topic = 'task.reviewed')::timestamptz AS reviewed_at
    FROM events AS event
    WHERE event.resource_type = 'episode_task'
      AND event.topic IN ('task.video_ready', 'task.subtitle_ready', 'task.awaiting_review', 'task.reviewed')
    GROUP BY event.resource_id
), acquisition_milestones AS (
    SELECT
        event.resource_id AS acquisition_id,
        max(event.occurred_at)::timestamptz AS archived_at
    FROM events AS event
    WHERE event.resource_type = 'acquisition'
      AND event.topic = 'acquisition.delete_completed'
    GROUP BY event.resource_id
)
SELECT
    history.acquisition_id,
    history.entry_id,
    entry.subscription_id,
    subscription.series_id,
    series.tmdb_series_id,
    series.title AS series_title,
    subscription.mapping_profile_id,
    history.task_id,
    history.download_id,
    entry.source_season,
    entry.source_episode,
    target_season.season_number AS target_season,
    target_episode.episode_number AS target_episode,
    target_episode.title AS target_episode_title,
    history.acquisition_created_at,
    history.task_created_at,
    milestones.video_ready_at,
    milestones.subtitle_ready_at,
    milestones.artifact_ready_at,
    milestones.reviewed_at,
    history.imported_at,
    COALESCE(subscription.completed_at, acquisition_milestones.archived_at, history.imported_at)::timestamptz AS archived_at
FROM successful_history AS history
JOIN rss_entries AS entry ON entry.id = history.entry_id
JOIN rss_subscriptions AS subscription ON subscription.id = entry.subscription_id
JOIN media_series AS series ON series.id = subscription.series_id
LEFT JOIN episode_mappings AS mapping
  ON mapping.profile_id = subscription.mapping_profile_id
 AND mapping.source_season = entry.source_season
 AND mapping.source_episode = entry.source_episode
 AND mapping.mapping_status = 'mapped'
LEFT JOIN media_episodes AS target_episode ON target_episode.id = mapping.target_episode_id
LEFT JOIN tmdb_seasons AS target_season ON target_season.id = target_episode.season_id
LEFT JOIN task_milestones AS milestones ON milestones.task_id = history.task_id
LEFT JOIN acquisition_milestones ON acquisition_milestones.acquisition_id = history.acquisition_id
LIMIT 1
`

type GetArchivedRSSAcquisitionByIDRow struct {
	AcquisitionID        pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	EntryID              pgtype.UUID        `db:"entry_id" json:"entry_id"`
	SubscriptionID       pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	SeriesID             pgtype.UUID        `db:"series_id" json:"series_id"`
	TmdbSeriesID         *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
	SeriesTitle          string             `db:"series_title" json:"series_title"`
	MappingProfileID     pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	TaskID               pgtype.UUID        `db:"task_id" json:"task_id"`
	DownloadID           pgtype.UUID        `db:"download_id" json:"download_id"`
	SourceSeason         *int32             `db:"source_season" json:"source_season"`
	SourceEpisode        *int32             `db:"source_episode" json:"source_episode"`
	TargetSeason         *int32             `db:"target_season" json:"target_season"`
	TargetEpisode        *int32             `db:"target_episode" json:"target_episode"`
	TargetEpisodeTitle   *string            `db:"target_episode_title" json:"target_episode_title"`
	AcquisitionCreatedAt pgtype.Timestamptz `db:"acquisition_created_at" json:"acquisition_created_at"`
	TaskCreatedAt        pgtype.Timestamptz `db:"task_created_at" json:"task_created_at"`
	VideoReadyAt         pgtype.Timestamptz `db:"video_ready_at" json:"video_ready_at"`
	SubtitleReadyAt      pgtype.Timestamptz `db:"subtitle_ready_at" json:"subtitle_ready_at"`
	ArtifactReadyAt      pgtype.Timestamptz `db:"artifact_ready_at" json:"artifact_ready_at"`
	ReviewedAt           pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ImportedAt           pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	ArchivedAt           pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
}

func (q *Queries) GetArchivedRSSAcquisitionByID(ctx context.Context, id pgtype.UUID) (GetArchivedRSSAcquisitionByIDRow, error) {
	row := q.db.QueryRow(ctx, getArchivedRSSAcquisitionByID, id)
	var i GetArchivedRSSAcquisitionByIDRow
	err := row.Scan(
		&i.AcquisitionID,
		&i.EntryID,
		&i.SubscriptionID,
		&i.SeriesID,
		&i.TmdbSeriesID,
		&i.SeriesTitle,
		&i.MappingProfileID,
		&i.TaskID,
		&i.DownloadID,
		&i.SourceSeason,
		&i.SourceEpisode,
		&i.TargetSeason,
		&i.TargetEpisode,
		&i.TargetEpisodeTitle,
		&i.AcquisitionCreatedAt,
		&i.TaskCreatedAt,
		&i.VideoReadyAt,
		&i.SubtitleReadyAt,
		&i.ArtifactReadyAt,
		&i.ReviewedAt,
		&i.ImportedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getDownloadByID = `-- name: GetDownloadByID :one
SELECT id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
FROM downloads
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetDownloadByID(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getDownloadByID, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const getDownloadByIDIncludingDeleted = `-- name: GetDownloadByIDIncludingDeleted :one
SELECT id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
FROM downloads
WHERE id = $1
`

func (q *Queries) GetDownloadByIDIncludingDeleted(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getDownloadByIDIncludingDeleted, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const getLatestDownloadByAcquisition = `-- name: GetLatestDownloadByAcquisition :one
SELECT id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
FROM downloads
WHERE acquisition_id = $1
  AND deleted_at IS NULL
ORDER BY (status = 'cancelled'), attempt DESC
LIMIT 1
`

func (q *Queries) GetLatestDownloadByAcquisition(ctx context.Context, acquisitionID pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getLatestDownloadByAcquisition, acquisitionID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}

const getOperationByID = `-- name: GetOperationByID :one
SELECT id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
FROM operations
WHERE id = $1
`

func (q *Queries) GetOperationByID(ctx context.Context, id pgtype.UUID) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByID, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ResourceType,
		&i.ResourceID,
		&i.IdempotencyKey,
		&i.Status,
		&i.RiverJobID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.TimeoutSeconds,
		&i.CancelRequestedAt,
		&i.HeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRSSEntryRelations = `-- name: GetRSSEntryRelations :one
SELECT
    acquisition.id AS acquisition_id,
    latest_download.id AS download_id
FROM acquisitions AS acquisition
LEFT JOIN LATERAL (
    SELECT download.id
    FROM downloads AS download
    WHERE download.acquisition_id = acquisition.id
      AND download.deleted_at IS NULL
    ORDER BY (download.status = 'cancelled'), download.attempt DESC
    LIMIT 1
) AS latest_download ON true
WHERE acquisition.rss_entry_id = $1
  AND latest_download.id IS NOT NULL
`

type GetRSSEntryRelationsRow struct {
	AcquisitionID pgtype.UUID `db:"acquisition_id" json:"acquisition_id"`
	DownloadID    pgtype.UUID `db:"download_id" json:"download_id"`
}

func (q *Queries) GetRSSEntryRelations(ctx context.Context, rssEntryID pgtype.UUID) (GetRSSEntryRelationsRow, error) {
	row := q.db.QueryRow(ctx, getRSSEntryRelations, rssEntryID)
	var i GetRSSEntryRelationsRow
	err := row.Scan(&i.AcquisitionID, &i.DownloadID)
	return i, err
}

const listAcquisitionTaskSummaries = `-- name: ListAcquisitionTaskSummaries :many
SELECT
    task.id,
    task.media_type,
    source_file.download_id,
    source_file.source_season,
    source_file.source_episode,
    season.season_number AS target_season,
    episode.episode_number AS target_episode,
    episode.title AS target_episode_title,
    task.state,
    task.video_state,
    task.subtitle_state,
    artifact_set.basename AS artifact_basename,
    review.decision AS review_decision,
    review.reviewed_at,
    COALESCE(latest_import.status, '')::text AS import_status,
    latest_import.destination_video_path,
    latest_import.destination_subtitle_path,
    COALESCE(latest_refresh.status, '')::text AS emby_refresh_status,
    COALESCE(latest_cleanup.status, '')::text AS cleanup_status,
    task.failure_stage,
    task.error_code,
    task.error_message,
    GREATEST(
        task.updated_at,
        review.reviewed_at,
        latest_import.updated_at,
        latest_refresh.updated_at,
        latest_cleanup.updated_at
    )::timestamptz AS updated_at
FROM episode_tasks AS task
JOIN download_files AS source_file ON source_file.id = task.source_video_file_id
JOIN downloads AS source_download ON source_download.id = source_file.download_id AND source_download.deleted_at IS NULL
LEFT JOIN episode_mappings AS mapping ON mapping.id = task.mapping_id
LEFT JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
LEFT JOIN tmdb_seasons AS season ON season.id = episode.season_id
LEFT JOIN artifact_sets AS artifact_set ON artifact_set.task_id = task.id
LEFT JOIN reviews AS review ON review.task_id = task.id
LEFT JOIN LATERAL (
    SELECT import.id, import.task_id, import.attempt, import.status, import.destination_video_path, import.destination_subtitle_path, import.error_code, import.error_message, import.started_at, import.completed_at, import.created_at, import.updated_at
    FROM imports AS import
    WHERE import.task_id = task.id
    ORDER BY import.attempt DESC
    LIMIT 1
) AS latest_import ON true
LEFT JOIN LATERAL (
    SELECT operation.id, operation.kind, operation.resource_type, operation.resource_id, operation.idempotency_key, operation.status, operation.river_job_id, operation.max_attempts, operation.attempt_count, operation.timeout_seconds, operation.cancel_requested_at, operation.heartbeat_at, operation.error_code, operation.error_message, operation.payload, operation.created_at, operation.started_at, operation.finished_at, operation.updated_at
    FROM operations AS operation
    WHERE operation.resource_type = 'episode_task'
      AND operation.resource_id = task.id
      AND operation.kind = 'emby.refresh'
    ORDER BY operation.created_at DESC, operation.id DESC
    LIMIT 1
) AS latest_refresh ON true
LEFT JOIN LATERAL (
    SELECT cleanup.id, cleanup.task_id, cleanup.download_id, cleanup.attempt, cleanup.status, cleanup.torrent_removed, cleanup.staged_files_removed, cleanup.error_code, cleanup.error_message, cleanup.started_at, cleanup.completed_at, cleanup.created_at, cleanup.updated_at
    FROM cleanup_runs AS cleanup
    WHERE cleanup.task_id = task.id
    ORDER BY cleanup.attempt DESC
    LIMIT 1
) AS latest_cleanup ON true
WHERE task.acquisition_id = $1
ORDER BY source_file.source_season, source_file.source_episode, task.id
`

type ListAcquisitionTaskSummariesRow struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	MediaType               string             `db:"media_type" json:"media_type"`
	DownloadID              pgtype.UUID        `db:"download_id" json:"download_id"`
	SourceSeason            *int32             `db:"source_season" json:"source_season"`
	SourceEpisode           *int32             `db:"source_episode" json:"source_episode"`
	TargetSeason            *int32             `db:"target_season" json:"target_season"`
	TargetEpisode           *int32             `db:"target_episode" json:"target_episode"`
	TargetEpisodeTitle      *string            `db:"target_episode_title" json:"target_episode_title"`
	State                   string             `db:"state" json:"state"`
	VideoState              string             `db:"video_state" json:"video_state"`
	SubtitleState           string             `db:"subtitle_state" json:"subtitle_state"`
	ArtifactBasename        *string            `db:"artifact_basename" json:"artifact_basename"`
	ReviewDecision          *string            `db:"review_decision" json:"review_decision"`
	ReviewedAt              pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ImportStatus            string             `db:"import_status" json:"import_status"`
	DestinationVideoPath    *string            `db:"destination_video_path" json:"destination_video_path"`
	DestinationSubtitlePath *string            `db:"destination_subtitle_path" json:"destination_subtitle_path"`
	EmbyRefreshStatus       string             `db:"emby_refresh_status" json:"emby_refresh_status"`
	CleanupStatus           string             `db:"cleanup_status" json:"cleanup_status"`
	FailureStage            *string            `db:"failure_stage" json:"failure_stage"`
	ErrorCode               *string            `db:"error_code" json:"error_code"`
	ErrorMessage            *string            `db:"error_message" json:"error_message"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAcquisitionTaskSummaries(ctx context.Context, acquisitionID pgtype.UUID) ([]ListAcquisitionTaskSummariesRow, error) {
	rows, err := q.db.Query(ctx, listAcquisitionTaskSummaries, acquisitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcquisitionTaskSummariesRow{}
	for rows.Next() {
		var i ListAcquisitionTaskSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.MediaType,
			&i.DownloadID,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.TargetSeason,
			&i.TargetEpisode,
			&i.TargetEpisodeTitle,
			&i.State,
			&i.VideoState,
			&i.SubtitleState,
			&i.ArtifactBasename,
			&i.ReviewDecision,
			&i.ReviewedAt,
			&i.ImportStatus,
			&i.DestinationVideoPath,
			&i.DestinationSubtitlePath,
			&i.EmbyRefreshStatus,
			&i.CleanupStatus,
			&i.FailureStage,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcquisitionTaskSummariesByAcquisitionIDs = `-- name: ListAcquisitionTaskSummariesByAcquisitionIDs :many
SELECT
    task.acquisition_id,
    task.id,
    task.media_type,
    source_file.download_id,
    source_file.source_season,
    source_file.source_episode,
    season.season_number AS target_season,
    episode.episode_number AS target_episode,
    episode.title AS target_episode_title,
    task.state,
    task.video_state,
    task.subtitle_state,
    artifact_set.basename AS artifact_basename,
    review.decision AS review_decision,
    review.reviewed_at,
    COALESCE(latest_import.status, '')::text AS import_status,
    latest_import.destination_video_path,
    latest_import.destination_subtitle_path,
    COALESCE(latest_refresh.status, '')::text AS emby_refresh_status,
    COALESCE(latest_cleanup.status, '')::text AS cleanup_status,
    task.failure_stage,
    task.error_code,
    task.error_message,
    GREATEST(
        task.updated_at,
        review.reviewed_at,
        latest_import.updated_at,
        latest_refresh.updated_at,
        latest_cleanup.updated_at
    )::timestamptz AS updated_at
FROM episode_tasks AS task
JOIN download_files AS source_file ON source_file.id = task.source_video_file_id
JOIN downloads AS source_download ON source_download.id = source_file.download_id AND source_download.deleted_at IS NULL
LEFT JOIN episode_mappings AS mapping ON mapping.id = task.mapping_id
LEFT JOIN media_episodes AS episode ON episode.id = mapping.target_episode_id
LEFT JOIN tmdb_seasons AS season ON season.id = episode.season_id
LEFT JOIN artifact_sets AS artifact_set ON artifact_set.task_id = task.id
LEFT JOIN reviews AS review ON review.task_id = task.id
LEFT JOIN LATERAL (
    SELECT import.id, import.task_id, import.attempt, import.status, import.destination_video_path, import.destination_subtitle_path, import.error_code, import.error_message, import.started_at, import.completed_at, import.created_at, import.updated_at
    FROM imports AS import
    WHERE import.task_id = task.id
    ORDER BY import.attempt DESC
    LIMIT 1
) AS latest_import ON true
LEFT JOIN LATERAL (
    SELECT operation.id, operation.kind, operation.resource_type, operation.resource_id, operation.idempotency_key, operation.status, operation.river_job_id, operation.max_attempts, operation.attempt_count, operation.timeout_seconds, operation.cancel_requested_at, operation.heartbeat_at, operation.error_code, operation.error_message, operation.payload, operation.created_at, operation.started_at, operation.finished_at, operation.updated_at
    FROM operations AS operation
    WHERE operation.resource_type = 'episode_task'
      AND operation.resource_id = task.id
      AND operation.kind = 'emby.refresh'
    ORDER BY operation.created_at DESC, operation.id DESC
    LIMIT 1
) AS latest_refresh ON true
LEFT JOIN LATERAL (
    SELECT cleanup.id, cleanup.task_id, cleanup.download_id, cleanup.attempt, cleanup.status, cleanup.torrent_removed, cleanup.staged_files_removed, cleanup.error_code, cleanup.error_message, cleanup.started_at, cleanup.completed_at, cleanup.created_at, cleanup.updated_at
    FROM cleanup_runs AS cleanup
    WHERE cleanup.task_id = task.id
    ORDER BY cleanup.attempt DESC
    LIMIT 1
) AS latest_cleanup ON true
WHERE task.acquisition_id = ANY($1::uuid[])
ORDER BY task.acquisition_id, source_file.source_season, source_file.source_episode, task.id
`

type ListAcquisitionTaskSummariesByAcquisitionIDsRow struct {
	AcquisitionID           pgtype.UUID        `db:"acquisition_id" json:"acquisition_id"`
	ID                      pgtype.UUID        `db:"id" json:"id"`
	MediaType               string             `db:"media_type" json:"media_type"`
	DownloadID              pgtype.UUID        `db:"download_id" json:"download_id"`
	SourceSeason            *int32             `db:"source_season" json:"source_season"`
	SourceEpisode           *int32             `db:"source_episode" json:"source_episode"`
	TargetSeason            *int32             `db:"target_season" json:"target_season"`
	TargetEpisode           *int32             `db:"target_episode" json:"target_episode"`
	TargetEpisodeTitle      *string            `db:"target_episode_title" json:"target_episode_title"`
	State                   string             `db:"state" json:"state"`
	VideoState              string             `db:"video_state" json:"video_state"`
	SubtitleState           string             `db:"subtitle_state" json:"subtitle_state"`
	ArtifactBasename        *string            `db:"artifact_basename" json:"artifact_basename"`
	ReviewDecision          *string            `db:"review_decision" json:"review_decision"`
	ReviewedAt              pgtype.Timestamptz `db:"reviewed_at" json:"reviewed_at"`
	ImportStatus            string             `db:"import_status" json:"import_status"`
	DestinationVideoPath    *string            `db:"destination_video_path" json:"destination_video_path"`
	DestinationSubtitlePath *string            `db:"destination_subtitle_path" json:"destination_subtitle_path"`
	EmbyRefreshStatus       string             `db:"emby_refresh_status" json:"emby_refresh_status"`
	CleanupStatus           string             `db:"cleanup_status" json:"cleanup_status"`
	FailureStage            *string            `db:"failure_stage" json:"failure_stage"`
	ErrorCode               *string            `db:"error_code" json:"error_code"`
	ErrorMessage            *string            `db:"error_message" json:"error_message"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListAcquisitionTaskSummariesByAcquisitionIDs(ctx context.Context, acquisitionIds []pgtype.UUID) ([]ListAcquisitionTaskSummariesByAcquisitionIDsRow, error) {
	rows, err := q.db.Query(ctx, listAcquisitionTaskSummariesByAcquisitionIDs, acquisitionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcquisitionTaskSummariesByAcquisitionIDsRow{}
	for rows.Next() {
		var i ListAcquisitionTaskSummariesByAcquisitionIDsRow
		if err := rows.Scan(
			&i.AcquisitionID,
			&i.ID,
			&i.MediaType,
			&i.DownloadID,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.TargetSeason,
			&i.TargetEpisode,
			&i.TargetEpisodeTitle,
			&i.State,
			&i.VideoState,
			&i.SubtitleState,
			&i.ArtifactBasename,
			&i.ReviewDecision,
			&i.ReviewedAt,
			&i.ImportStatus,
			&i.DestinationVideoPath,
			&i.DestinationSubtitlePath,
			&i.EmbyRefreshStatus,
			&i.CleanupStatus,
			&i.FailureStage,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAcquisitions = `-- name: ListAcquisitions :many
SELECT id, series_id, mapping_profile_id, source_kind, release_candidate_id, rss_entry_id, source_uri, source_payload, legacy_id, created_by, created_at, updated_at, deletion_requested_at
FROM acquisitions
WHERE acquisitions.deletion_requested_at IS NULL
  AND (
      NOT EXISTS (SELECT 1 FROM downloads WHERE downloads.acquisition_id = acquisitions.id)
      OR EXISTS (
          SELECT 1 FROM downloads
          WHERE downloads.acquisition_id = acquisitions.id
            AND downloads.deleted_at IS NULL
            AND downloads.status <> 'cancelled'
      )
      OR EXISTS (
          SELECT 1
          FROM episode_tasks AS task
          JOIN download_files AS source_file ON source_file.id = task.source_video_file_id
          JOIN downloads AS source_download ON source_download.id = source_file.download_id
          WHERE task.acquisition_id = acquisitions.id
            AND source_download.deleted_at IS NULL
      )
  )
  AND ($1::text IS NULL OR source_kind = $1::text)
  AND (
      $2::bigint IS NULL
      OR series_id IN (SELECT id FROM media_series WHERE tmdb_series_id = $2::bigint)
  )
  AND (
      $3::text IS NULL
      OR (
          $3::text = 'mapping_pending'
          AND acquisitions.series_id IN (SELECT id FROM media_series WHERE media_type = 'tv')
          AND EXISTS (
              SELECT 1
              FROM downloads AS download
              WHERE download.id = (
                    SELECT candidate.id
                    FROM downloads AS candidate
                    WHERE candidate.acquisition_id = acquisitions.id
                      AND candidate.deleted_at IS NULL
                    ORDER BY (candidate.status = 'cancelled'), candidate.attempt DESC
                    LIMIT 1
                )
                AND (
                    download.status IN ('completed', 'selecting_files', 'materialized')
                    OR (
                        download.status = 'failed'
                        AND download.failure_stage = 'materialize'
                        AND download.error_code IN (
                            'mapping_profile_required',
                            'episode_mapping_required',
                            'mapping_source_invalid',
                            'mapping_source_out_of_range',
                            'mapping_context_incomplete',
                            'mapping_target_out_of_range',
                            'mapping_title_missing'
                        )
                    )
                )
                AND (
                    NOT EXISTS (
                        SELECT 1 FROM download_files AS file
                        WHERE file.download_id = download.id AND file.selected AND file.media_kind = 'video'
                    )
                    OR EXISTS (
                        SELECT 1
                        FROM download_files AS file
                        WHERE file.download_id = download.id
                          AND file.selected
                          AND file.media_kind = 'video'
                          AND NOT EXISTS (
                              SELECT 1
                              FROM episode_mappings AS mapping
                              WHERE mapping.profile_id = acquisitions.mapping_profile_id
                                AND mapping.source_season = file.source_season
                                AND mapping.source_episode = file.source_episode
                                AND mapping.mapping_status = 'mapped'
                                AND mapping.target_episode_id IS NOT NULL
                          )
                    )
                )
          )
      )
  )
  AND (
      $4::uuid IS NULL
      OR (
          COALESCE($5::text, 'newest') = 'oldest'
          AND (acquisitions.created_at, acquisitions.id) > (
              SELECT cursor_acquisition.created_at, cursor_acquisition.id
              FROM acquisitions AS cursor_acquisition
              WHERE cursor_acquisition.id = $4::uuid
          )
      )
      OR (
          COALESCE($5::text, 'newest') = 'newest'
          AND (acquisitions.created_at, acquisitions.id) < (
              SELECT cursor_acquisition.created_at, cursor_acquisition.id
              FROM acquisitions AS cursor_acquisition
              WHERE cursor_acquisition.id = $4::uuid
          )
      )
  )
ORDER BY
    CASE WHEN COALESCE($5::text, 'newest') = 'oldest' THEN acquisitions.created_at END ASC,
    CASE WHEN COALESCE($5::text, 'newest') = 'newest' THEN acquisitions.created_at END DESC,
    CASE WHEN COALESCE($5::text, 'newest') = 'oldest' THEN acquisitions.id END ASC,
    CASE WHEN COALESCE($5::text, 'newest') = 'newest' THEN acquisitions.id END DESC
LIMIT $6
`

type ListAcquisitionsParams struct {
	SourceKind   *string     `db:"source_kind" json:"source_kind"`
	TmdbSeriesID *int64      `db:"tmdb_series_id" json:"tmdb_series_id"`
	Phase        *string     `db:"phase" json:"phase"`
	Cursor       pgtype.UUID `db:"cursor" json:"cursor"`
	Sort         *string     `db:"sort" json:"sort"`
	RowLimit     int32       `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListAcquisitions(ctx context.Context, arg ListAcquisitionsParams) ([]Acquisition, error) {
	rows, err := q.db.Query(ctx, listAcquisitions,
		arg.SourceKind,
		arg.TmdbSeriesID,
		arg.Phase,
		arg.Cursor,
		arg.Sort,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Acquisition{}
	for rows.Next() {
		var i Acquisition
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.MappingProfileID,
			&i.SourceKind,
			&i.ReleaseCandidateID,
			&i.RssEntryID,
			&i.SourceUri,
			&i.SourcePayload,
			&i.LegacyID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletionRequestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadFiles = `-- name: ListDownloadFiles :many
SELECT id, download_id, file_index, relative_path, size_bytes, media_kind, selected, source_season, source_episode, language, created_at, updated_at
FROM download_files
WHERE download_id = $1
ORDER BY file_index
`

func (q *Queries) ListDownloadFiles(ctx context.Context, downloadID pgtype.UUID) ([]DownloadFile, error) {
	rows, err := q.db.Query(ctx, listDownloadFiles, downloadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownloadFile{}
	for rows.Next() {
		var i DownloadFile
		if err := rows.Scan(
			&i.ID,
			&i.DownloadID,
			&i.FileIndex,
			&i.RelativePath,
			&i.SizeBytes,
			&i.MediaKind,
			&i.Selected,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloads = `-- name: ListDownloads :many
SELECT download.id, download.acquisition_id, download.attempt, download.client_name, download.torrent_hash, download.status, download.progress, download.save_path, download.error_code, download.error_message, download.started_at, download.completed_at, download.created_at, download.updated_at, download.version, download.failure_stage, download.client_state, download.last_synced_at, download.deletion_requested_at, download.deleted_at, download.file_resolution_source, download.agent_resolution_id
FROM downloads AS download
WHERE download.deleted_at IS NULL
  AND ($1::text IS NULL OR download.status = $1::text)
  AND (
      $2::text IS NULL
      OR ($2::text = 'active' AND download.status IN ('enqueue_pending', 'file_resolution_pending', 'downloading'))
      OR (
          $2::text = 'waiting'
          AND (
              download.status IN ('enqueue_pending', 'file_resolution_pending')
              OR (download.status = 'downloading' AND download.client_state IN ('metaDL', 'queuedDL', 'stalledDL'))
          )
      )
      OR (
          $2::text = 'downloading'
          AND download.status = 'downloading'
          AND (
              download.client_state IS NULL
              OR download.client_state NOT IN ('metaDL', 'queuedDL', 'stalledDL', 'pausedDL', 'stoppedDL')
          )
      )
      OR (
          $2::text = 'paused'
          AND download.status = 'downloading'
          AND download.client_state IN ('pausedDL', 'stoppedDL')
      )
      OR (
          $2::text = 'completed'
          AND (
              download.status IN ('completed', 'selecting_files', 'materialized')
              OR (download.status = 'failed' AND download.failure_stage = 'materialize' AND download.progress = 1)
          )
      )
      OR (
          $2::text = 'failed'
          AND download.status = 'failed'
          AND download.failure_stage IS DISTINCT FROM 'materialize'
      )
  )
  AND (
      $3::text IS NULL
      OR download.id::text ILIKE '%' || $3::text || '%'
      OR COALESCE(download.save_path, '') ILIKE '%' || $3::text || '%'
      OR COALESCE(download.torrent_hash, '') ILIKE '%' || $3::text || '%'
      OR EXISTS (
          SELECT 1
          FROM acquisitions AS acquisition
          JOIN media_series AS media ON media.id = acquisition.series_id
          WHERE acquisition.id = download.acquisition_id
            AND (media.title ILIKE '%' || $3::text || '%' OR COALESCE(media.original_title, '') ILIKE '%' || $3::text || '%')
      )
  )
  AND (
      $4::uuid IS NULL
      OR (
          COALESCE($5::text, 'newest') = 'oldest'
          AND (download.created_at, download.id) > (
              SELECT cursor_download.created_at, cursor_download.id
              FROM downloads AS cursor_download
              WHERE cursor_download.id = $4::uuid
          )
      )
      OR (
          COALESCE($5::text, 'newest') = 'newest'
          AND (download.created_at, download.id) < (
              SELECT cursor_download.created_at, cursor_download.id
              FROM downloads AS cursor_download
              WHERE cursor_download.id = $4::uuid
          )
      )
  )
ORDER BY
    CASE WHEN COALESCE($5::text, 'newest') = 'oldest' THEN download.created_at END ASC,
    CASE WHEN COALESCE($5::text, 'newest') = 'newest' THEN download.created_at END DESC,
    CASE WHEN COALESCE($5::text, 'newest') = 'oldest' THEN download.id END ASC,
    CASE WHEN COALESCE($5::text, 'newest') = 'newest' THEN download.id END DESC
LIMIT $6
`

type ListDownloadsParams struct {
	Status   *string     `db:"status" json:"status"`
	Phase    *string     `db:"phase" json:"phase"`
	Query    *string     `db:"query" json:"query"`
	Cursor   pgtype.UUID `db:"cursor" json:"cursor"`
	Sort     *string     `db:"sort" json:"sort"`
	RowLimit int32       `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListDownloads(ctx context.Context, arg ListDownloadsParams) ([]Download, error) {
	rows, err := q.db.Query(ctx, listDownloads,
		arg.Status,
		arg.Phase,
		arg.Query,
		arg.Cursor,
		arg.Sort,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.AcquisitionID,
			&i.Attempt,
			&i.ClientName,
			&i.TorrentHash,
			&i.Status,
			&i.Progress,
			&i.SavePath,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.FailureStage,
			&i.ClientState,
			&i.LastSyncedAt,
			&i.DeletionRequestedAt,
			&i.DeletedAt,
			&i.FileResolutionSource,
			&i.AgentResolutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDownloadsByAcquisitionIDs = `-- name: ListLatestDownloadsByAcquisitionIDs :many
SELECT DISTINCT ON (acquisition_id) id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
FROM downloads
WHERE acquisition_id = ANY($1::uuid[])
  AND deleted_at IS NULL
ORDER BY acquisition_id, (status = 'cancelled'), attempt DESC
`

func (q *Queries) ListLatestDownloadsByAcquisitionIDs(ctx context.Context, acquisitionIds []pgtype.UUID) ([]Download, error) {
	rows, err := q.db.Query(ctx, listLatestDownloadsByAcquisitionIDs, acquisitionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.AcquisitionID,
			&i.Attempt,
			&i.ClientName,
			&i.TorrentHash,
			&i.Status,
			&i.Progress,
			&i.SavePath,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
			&i.FailureStage,
			&i.ClientState,
			&i.LastSyncedAt,
			&i.DeletionRequestedAt,
			&i.DeletedAt,
			&i.FileResolutionSource,
			&i.AgentResolutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationAttempts = `-- name: ListOperationAttempts :many
SELECT id, operation_id, attempt, status, worker_id, error_code, error_message, started_at, heartbeat_at, finished_at
FROM operation_attempts
WHERE operation_id = $1
ORDER BY attempt
`

func (q *Queries) ListOperationAttempts(ctx context.Context, operationID pgtype.UUID) ([]OperationAttempt, error) {
	rows, err := q.db.Query(ctx, listOperationAttempts, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OperationAttempt{}
	for rows.Next() {
		var i OperationAttempt
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.Attempt,
			&i.Status,
			&i.WorkerID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.HeartbeatAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
SELECT id, kind, resource_type, resource_id, idempotency_key, status, river_job_id, max_attempts, attempt_count, timeout_seconds, cancel_requested_at, heartbeat_at, error_code, error_message, payload, created_at, started_at, finished_at, updated_at
FROM operations
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR resource_type = $2::text)
  AND ($3::uuid IS NULL OR resource_id = $3::uuid)
  AND (
      $4::uuid IS NULL
      OR (created_at, id) < (
          SELECT cursor_operation.created_at, cursor_operation.id
          FROM operations AS cursor_operation
          WHERE cursor_operation.id = $4::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListOperationsParams struct {
	Status       *string     `db:"status" json:"status"`
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	Cursor       pgtype.UUID `db:"cursor" json:"cursor"`
	RowLimit     int32       `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListOperations(ctx context.Context, arg ListOperationsParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperations,
		arg.Status,
		arg.ResourceType,
		arg.ResourceID,
		arg.Cursor,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ResourceType,
			&i.ResourceID,
			&i.IdempotencyKey,
			&i.Status,
			&i.RiverJobID,
			&i.MaxAttempts,
			&i.AttemptCount,
			&i.TimeoutSeconds,
			&i.CancelRequestedAt,
			&i.HeartbeatAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSSEntries = `-- name: ListRSSEntries :many
SELECT
    entry.id, entry.subscription_id, entry.release_candidate_id, entry.identity_key, entry.guid, entry.btih, entry.canonical_url, entry.title, entry.published_at, entry.status, entry.enqueue_attempts, entry.last_error_code, entry.last_error_message, entry.upstream_payload, entry.discovered_at, entry.enqueued_at, entry.updated_at, entry.download_uri, entry.downloadable, entry.rejection_reasons, entry.source_season, entry.source_episode, entry.duplicate_count, entry.last_error_retryable, entry.imported_at, entry.coordinate_source, entry.agent_resolution_id, entry.fulfillment_source,
    adjudication.batch_id AS adjudication_batch_id,
    COALESCE(adjudication.state, 'not_required')::text AS adjudication_state,
    adjudication.source AS adjudication_source,
    adjudication.resolution_id AS adjudication_resolution_id,
    adjudication.related_entry_id,
    EXISTS (
        SELECT 1
        FROM events AS enqueue
        JOIN events AS created
          ON created.resource_type = 'episode_task'
         AND created.topic = 'task.created'
         AND created.data->>'downloadId' = enqueue.data->>'downloadId'
        JOIN events AS imported
          ON imported.resource_type = 'episode_task'
         AND imported.resource_id = created.resource_id
         AND imported.topic = 'task.imported'
        WHERE enqueue.resource_type = 'rss_entry'
          AND enqueue.topic = 'rss.entry.enqueueing'
          AND enqueue.resource_id = entry.id
          AND enqueue.data ? 'acquisitionId'
          AND enqueue.data ? 'downloadId'
    ) AS successful_import_present
FROM rss_entries AS entry
LEFT JOIN rss_entry_adjudications AS adjudication ON adjudication.entry_id = entry.id
WHERE entry.subscription_id = $1
  AND ($2::text IS NULL OR entry.status = $2::text)
  AND (
      $3::uuid IS NULL
      OR (
          COALESCE($4::text, 'newest') = 'oldest'
          AND (entry.discovered_at, entry.id) > (
              SELECT cursor_entry.discovered_at, cursor_entry.id
              FROM rss_entries AS cursor_entry
              WHERE cursor_entry.id = $3::uuid
          )
      )
      OR (
          COALESCE($4::text, 'newest') = 'newest'
          AND (entry.discovered_at, entry.id) < (
              SELECT cursor_entry.discovered_at, cursor_entry.id
              FROM rss_entries AS cursor_entry
              WHERE cursor_entry.id = $3::uuid
          )
      )
  )
ORDER BY
    CASE WHEN COALESCE($4::text, 'newest') = 'oldest' THEN entry.discovered_at END ASC,
    CASE WHEN COALESCE($4::text, 'newest') = 'newest' THEN entry.discovered_at END DESC,
    CASE WHEN COALESCE($4::text, 'newest') = 'oldest' THEN entry.id END ASC,
    CASE WHEN COALESCE($4::text, 'newest') = 'newest' THEN entry.id END DESC
LIMIT $5
`

type ListRSSEntriesParams struct {
	SubscriptionID pgtype.UUID `db:"subscription_id" json:"subscription_id"`
	Status         *string     `db:"status" json:"status"`
	Cursor         pgtype.UUID `db:"cursor" json:"cursor"`
	Sort           *string     `db:"sort" json:"sort"`
	RowLimit       int32       `db:"row_limit" json:"row_limit"`
}

type ListRSSEntriesRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	SubscriptionID           pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	ReleaseCandidateID       pgtype.UUID        `db:"release_candidate_id" json:"release_candidate_id"`
	IdentityKey              string             `db:"identity_key" json:"identity_key"`
	Guid                     *string            `db:"guid" json:"guid"`
	Btih                     *string            `db:"btih" json:"btih"`
	CanonicalUrl             *string            `db:"canonical_url" json:"canonical_url"`
	Title                    string             `db:"title" json:"title"`
	PublishedAt              pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Status                   string             `db:"status" json:"status"`
	EnqueueAttempts          int32              `db:"enqueue_attempts" json:"enqueue_attempts"`
	LastErrorCode            *string            `db:"last_error_code" json:"last_error_code"`
	LastErrorMessage         *string            `db:"last_error_message" json:"last_error_message"`
	UpstreamPayload          []byte             `db:"upstream_payload" json:"upstream_payload"`
	DiscoveredAt             pgtype.Timestamptz `db:"discovered_at" json:"discovered_at"`
	EnqueuedAt               pgtype.Timestamptz `db:"enqueued_at" json:"enqueued_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DownloadUri              *string            `db:"download_uri" json:"download_uri"`
	Downloadable             bool               `db:"downloadable" json:"downloadable"`
	RejectionReasons         []string           `db:"rejection_reasons" json:"rejection_reasons"`
	SourceSeason             *int32             `db:"source_season" json:"source_season"`
	SourceEpisode            *int32             `db:"source_episode" json:"source_episode"`
	DuplicateCount           int32              `db:"duplicate_count" json:"duplicate_count"`
	LastErrorRetryable       bool               `db:"last_error_retryable" json:"last_error_retryable"`
	ImportedAt               pgtype.Timestamptz `db:"imported_at" json:"imported_at"`
	CoordinateSource         *string            `db:"coordinate_source" json:"coordinate_source"`
	AgentResolutionID        pgtype.UUID        `db:"agent_resolution_id" json:"agent_resolution_id"`
	FulfillmentSource        *string            `db:"fulfillment_source" json:"fulfillment_source"`
	AdjudicationBatchID      pgtype.UUID        `db:"adjudication_batch_id" json:"adjudication_batch_id"`
	AdjudicationState        string             `db:"adjudication_state" json:"adjudication_state"`
	AdjudicationSource       *string            `db:"adjudication_source" json:"adjudication_source"`
	AdjudicationResolutionID pgtype.UUID        `db:"adjudication_resolution_id" json:"adjudication_resolution_id"`
	RelatedEntryID           pgtype.UUID        `db:"related_entry_id" json:"related_entry_id"`
	SuccessfulImportPresent  bool               `db:"successful_import_present" json:"successful_import_present"`
}

func (q *Queries) ListRSSEntries(ctx context.Context, arg ListRSSEntriesParams) ([]ListRSSEntriesRow, error) {
	rows, err := q.db.Query(ctx, listRSSEntries,
		arg.SubscriptionID,
		arg.Status,
		arg.Cursor,
		arg.Sort,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRSSEntriesRow{}
	for rows.Next() {
		var i ListRSSEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.ReleaseCandidateID,
			&i.IdentityKey,
			&i.Guid,
			&i.Btih,
			&i.CanonicalUrl,
			&i.Title,
			&i.PublishedAt,
			&i.Status,
			&i.EnqueueAttempts,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.UpstreamPayload,
			&i.DiscoveredAt,
			&i.EnqueuedAt,
			&i.UpdatedAt,
			&i.DownloadUri,
			&i.Downloadable,
			&i.RejectionReasons,
			&i.SourceSeason,
			&i.SourceEpisode,
			&i.DuplicateCount,
			&i.LastErrorRetryable,
			&i.ImportedAt,
			&i.CoordinateSource,
			&i.AgentResolutionID,
			&i.FulfillmentSource,
			&i.AdjudicationBatchID,
			&i.AdjudicationState,
			&i.AdjudicationSource,
			&i.AdjudicationResolutionID,
			&i.RelatedEntryID,
			&i.SuccessfulImportPresent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourceEvents = `-- name: ListResourceEvents :many
SELECT event.id, event.event_sequence, event.topic, event.resource_type, event.resource_id, event.operation_id, event.actor_user_id, event.data, event.occurred_at
FROM events AS event
WHERE event.resource_type = $1
  AND event.resource_id = $2::uuid
  AND (
      $3::uuid IS NULL
      OR event.event_sequence < (
          SELECT cursor_event.event_sequence
          FROM events AS cursor_event
          WHERE cursor_event.id = $3::uuid
      )
  )
ORDER BY event.event_sequence DESC
LIMIT $4
`

type ListResourceEventsParams struct {
	ResourceType *string     `db:"resource_type" json:"resource_type"`
	ResourceID   pgtype.UUID `db:"resource_id" json:"resource_id"`
	Cursor       pgtype.UUID `db:"cursor" json:"cursor"`
	RowLimit     int32       `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListResourceEvents(ctx context.Context, arg ListResourceEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listResourceEvents,
		arg.ResourceType,
		arg.ResourceID,
		arg.Cursor,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventSequence,
			&i.Topic,
			&i.ResourceType,
			&i.ResourceID,
			&i.OperationID,
			&i.ActorUserID,
			&i.Data,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchRuns = `-- name: ListSearchRuns :many
SELECT id, query, status, requested_by, error_code, error_message, started_at, completed_at, created_at, updated_at
FROM search_runs
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR query ILIKE '%' || $2::text || '%')
  AND (
      $3::uuid IS NULL
      OR (created_at, id) < (
          SELECT cursor_search.created_at, cursor_search.id
          FROM search_runs AS cursor_search
          WHERE cursor_search.id = $3::uuid
      )
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListSearchRunsParams struct {
	Status   *string     `db:"status" json:"status"`
	Query    *string     `db:"query" json:"query"`
	Cursor   pgtype.UUID `db:"cursor" json:"cursor"`
	RowLimit int32       `db:"row_limit" json:"row_limit"`
}

func (q *Queries) ListSearchRuns(ctx context.Context, arg ListSearchRunsParams) ([]SearchRun, error) {
	rows, err := q.db.Query(ctx, listSearchRuns,
		arg.Status,
		arg.Query,
		arg.Cursor,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchRun{}
	for rows.Next() {
		var i SearchRun
		if err := rows.Scan(
			&i.ID,
			&i.Query,
			&i.Status,
			&i.RequestedBy,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDownloadByID = `-- name: LockDownloadByID :one
SELECT id, acquisition_id, attempt, client_name, torrent_hash, status, progress, save_path, error_code, error_message, started_at, completed_at, created_at, updated_at, version, failure_stage, client_state, last_synced_at, deletion_requested_at, deleted_at, file_resolution_source, agent_resolution_id
FROM downloads
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockDownloadByID(ctx context.Context, id pgtype.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, lockDownloadByID, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.AcquisitionID,
		&i.Attempt,
		&i.ClientName,
		&i.TorrentHash,
		&i.Status,
		&i.Progress,
		&i.SavePath,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.FailureStage,
		&i.ClientState,
		&i.LastSyncedAt,
		&i.DeletionRequestedAt,
		&i.DeletedAt,
		&i.FileResolutionSource,
		&i.AgentResolutionID,
	)
	return i, err
}
