// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rss_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRSSSubscriptionProgress = `-- name: GetRSSSubscriptionProgress :one
SELECT subscription_id, overall_progress, task_count, completed_task_count, attention_task_count, source_revision, calculated_revision, model_version, dirty, dirtied_transaction_id, dirtied_at, calculated_at
FROM rss_subscription_progress
WHERE subscription_id = $1
`

func (q *Queries) GetRSSSubscriptionProgress(ctx context.Context, subscriptionID pgtype.UUID) (RssSubscriptionProgress, error) {
	row := q.db.QueryRow(ctx, getRSSSubscriptionProgress, subscriptionID)
	var i RssSubscriptionProgress
	err := row.Scan(
		&i.SubscriptionID,
		&i.OverallProgress,
		&i.TaskCount,
		&i.CompletedTaskCount,
		&i.AttentionTaskCount,
		&i.SourceRevision,
		&i.CalculatedRevision,
		&i.ModelVersion,
		&i.Dirty,
		&i.DirtiedTransactionID,
		&i.DirtiedAt,
		&i.CalculatedAt,
	)
	return i, err
}

const getRSSSubscriptionProgressReadiness = `-- name: GetRSSSubscriptionProgressReadiness :one
SELECT
    EXISTS (
        SELECT 1
        FROM rss_subscription_progress AS dirty_progress
        WHERE dirty_progress.dirty
    ) AS has_dirty,
    EXISTS (
        SELECT 1
        FROM rss_subscription_progress AS outdated_progress
        WHERE NOT outdated_progress.dirty
          AND outdated_progress.model_version < $1
    ) AS has_outdated_model,
    EXISTS (
        SELECT 1
        FROM rss_subscription_progress AS newer_progress
        WHERE newer_progress.model_version > $1
    ) AS has_newer_model
`

type GetRSSSubscriptionProgressReadinessRow struct {
	HasDirty         bool `db:"has_dirty" json:"has_dirty"`
	HasOutdatedModel bool `db:"has_outdated_model" json:"has_outdated_model"`
	HasNewerModel    bool `db:"has_newer_model" json:"has_newer_model"`
}

func (q *Queries) GetRSSSubscriptionProgressReadiness(ctx context.Context, targetModelVersion int32) (GetRSSSubscriptionProgressReadinessRow, error) {
	row := q.db.QueryRow(ctx, getRSSSubscriptionProgressReadiness, targetModelVersion)
	var i GetRSSSubscriptionProgressReadinessRow
	err := row.Scan(&i.HasDirty, &i.HasOutdatedModel, &i.HasNewerModel)
	return i, err
}

const listRSSSubscriptionProgressByIDs = `-- name: ListRSSSubscriptionProgressByIDs :many
SELECT subscription_id, overall_progress, task_count, completed_task_count, attention_task_count, source_revision, calculated_revision, model_version, dirty, dirtied_transaction_id, dirtied_at, calculated_at
FROM rss_subscription_progress
WHERE subscription_id = ANY($1::uuid[])
ORDER BY subscription_id
`

func (q *Queries) ListRSSSubscriptionProgressByIDs(ctx context.Context, subscriptionIds []pgtype.UUID) ([]RssSubscriptionProgress, error) {
	rows, err := q.db.Query(ctx, listRSSSubscriptionProgressByIDs, subscriptionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RssSubscriptionProgress{}
	for rows.Next() {
		var i RssSubscriptionProgress
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.OverallProgress,
			&i.TaskCount,
			&i.CompletedTaskCount,
			&i.AttentionTaskCount,
			&i.SourceRevision,
			&i.CalculatedRevision,
			&i.ModelVersion,
			&i.Dirty,
			&i.DirtiedTransactionID,
			&i.DirtiedAt,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSSSubscriptionRetryableTaskCountsByIDs = `-- name: ListRSSSubscriptionRetryableTaskCountsByIDs :many
SELECT
    requested.id AS subscription_id,
    count(task.id)::bigint AS retryable_task_count
FROM rss_subscriptions AS requested
LEFT JOIN rss_entries AS entry ON entry.subscription_id = requested.id
LEFT JOIN acquisitions AS acquisition ON acquisition.rss_entry_id = entry.id
LEFT JOIN episode_tasks AS task
  ON task.acquisition_id = acquisition.id
 AND task.state = 'failed'
WHERE requested.id = ANY($1::uuid[])
GROUP BY requested.id
ORDER BY requested.id
`

type ListRSSSubscriptionRetryableTaskCountsByIDsRow struct {
	SubscriptionID     pgtype.UUID `db:"subscription_id" json:"subscription_id"`
	RetryableTaskCount int64       `db:"retryable_task_count" json:"retryable_task_count"`
}

func (q *Queries) ListRSSSubscriptionRetryableTaskCountsByIDs(ctx context.Context, subscriptionIds []pgtype.UUID) ([]ListRSSSubscriptionRetryableTaskCountsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listRSSSubscriptionRetryableTaskCountsByIDs, subscriptionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRSSSubscriptionRetryableTaskCountsByIDsRow{}
	for rows.Next() {
		var i ListRSSSubscriptionRetryableTaskCountsByIDsRow
		if err := rows.Scan(&i.SubscriptionID, &i.RetryableTaskCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSSSubscriptionsByProgressAsc = `-- name: ListRSSSubscriptionsByProgressAsc :many
SELECT
    subscription.id,
    subscription.series_id,
    subscription.mapping_profile_id,
    subscription.name,
    subscription.feed_url,
    subscription.enabled,
    subscription.poll_interval_seconds,
    subscription.last_polled_at,
    subscription.next_poll_at,
    subscription.version,
    subscription.created_at,
    subscription.updated_at,
    subscription.source_season,
    subscription.deleted_at,
    subscription.auto_review,
    subscription.cleanup_source_on_completion,
    subscription.completed_at,
    subscription.include_keywords,
    subscription.exclude_keywords,
    subscription.auto_episode_mapping,
    series.title AS series_title,
    series.tmdb_series_id,
    progress.overall_progress,
    progress.task_count,
    progress.completed_task_count,
    progress.attention_task_count
FROM rss_subscription_progress AS progress
JOIN rss_subscriptions AS subscription ON subscription.id = progress.subscription_id
JOIN media_series AS series ON series.id = subscription.series_id
WHERE subscription.deleted_at IS NULL
  AND NOT progress.dirty
  AND progress.model_version = $1
  AND (
      $2::text IS NULL
      OR strpos(LOWER(subscription.name), LOWER($2::text)) > 0
      OR strpos(LOWER(series.title), LOWER($2::text)) > 0
  )
  AND (
      $3::uuid IS NULL
      OR (progress.overall_progress, progress.subscription_id) > (
          $4::double precision,
          $3::uuid
      )
  )
ORDER BY progress.overall_progress ASC, progress.subscription_id ASC
LIMIT $5
`

type ListRSSSubscriptionsByProgressAscParams struct {
	ModelVersion   int32       `db:"model_version" json:"model_version"`
	Query          *string     `db:"query" json:"query"`
	CursorID       pgtype.UUID `db:"cursor_id" json:"cursor_id"`
	CursorProgress *float64    `db:"cursor_progress" json:"cursor_progress"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

type ListRSSSubscriptionsByProgressAscRow struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	SeriesID                  pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID          pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	Name                      string             `db:"name" json:"name"`
	FeedUrl                   string             `db:"feed_url" json:"feed_url"`
	Enabled                   bool               `db:"enabled" json:"enabled"`
	PollIntervalSeconds       int32              `db:"poll_interval_seconds" json:"poll_interval_seconds"`
	LastPolledAt              pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	NextPollAt                pgtype.Timestamptz `db:"next_poll_at" json:"next_poll_at"`
	Version                   int32              `db:"version" json:"version"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SourceSeason              int32              `db:"source_season" json:"source_season"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	AutoReview                bool               `db:"auto_review" json:"auto_review"`
	CleanupSourceOnCompletion bool               `db:"cleanup_source_on_completion" json:"cleanup_source_on_completion"`
	CompletedAt               pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	IncludeKeywords           []string           `db:"include_keywords" json:"include_keywords"`
	ExcludeKeywords           []string           `db:"exclude_keywords" json:"exclude_keywords"`
	AutoEpisodeMapping        bool               `db:"auto_episode_mapping" json:"auto_episode_mapping"`
	SeriesTitle               string             `db:"series_title" json:"series_title"`
	TmdbSeriesID              *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
	OverallProgress           float64            `db:"overall_progress" json:"overall_progress"`
	TaskCount                 int32              `db:"task_count" json:"task_count"`
	CompletedTaskCount        int32              `db:"completed_task_count" json:"completed_task_count"`
	AttentionTaskCount        int32              `db:"attention_task_count" json:"attention_task_count"`
}

func (q *Queries) ListRSSSubscriptionsByProgressAsc(ctx context.Context, arg ListRSSSubscriptionsByProgressAscParams) ([]ListRSSSubscriptionsByProgressAscRow, error) {
	rows, err := q.db.Query(ctx, listRSSSubscriptionsByProgressAsc,
		arg.ModelVersion,
		arg.Query,
		arg.CursorID,
		arg.CursorProgress,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRSSSubscriptionsByProgressAscRow{}
	for rows.Next() {
		var i ListRSSSubscriptionsByProgressAscRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.MappingProfileID,
			&i.Name,
			&i.FeedUrl,
			&i.Enabled,
			&i.PollIntervalSeconds,
			&i.LastPolledAt,
			&i.NextPollAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceSeason,
			&i.DeletedAt,
			&i.AutoReview,
			&i.CleanupSourceOnCompletion,
			&i.CompletedAt,
			&i.IncludeKeywords,
			&i.ExcludeKeywords,
			&i.AutoEpisodeMapping,
			&i.SeriesTitle,
			&i.TmdbSeriesID,
			&i.OverallProgress,
			&i.TaskCount,
			&i.CompletedTaskCount,
			&i.AttentionTaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRSSSubscriptionsByProgressDesc = `-- name: ListRSSSubscriptionsByProgressDesc :many
SELECT
    subscription.id,
    subscription.series_id,
    subscription.mapping_profile_id,
    subscription.name,
    subscription.feed_url,
    subscription.enabled,
    subscription.poll_interval_seconds,
    subscription.last_polled_at,
    subscription.next_poll_at,
    subscription.version,
    subscription.created_at,
    subscription.updated_at,
    subscription.source_season,
    subscription.deleted_at,
    subscription.auto_review,
    subscription.cleanup_source_on_completion,
    subscription.completed_at,
    subscription.include_keywords,
    subscription.exclude_keywords,
    subscription.auto_episode_mapping,
    series.title AS series_title,
    series.tmdb_series_id,
    progress.overall_progress,
    progress.task_count,
    progress.completed_task_count,
    progress.attention_task_count
FROM rss_subscription_progress AS progress
JOIN rss_subscriptions AS subscription ON subscription.id = progress.subscription_id
JOIN media_series AS series ON series.id = subscription.series_id
WHERE subscription.deleted_at IS NULL
  AND NOT progress.dirty
  AND progress.model_version = $1
  AND (
      $2::text IS NULL
      OR strpos(LOWER(subscription.name), LOWER($2::text)) > 0
      OR strpos(LOWER(series.title), LOWER($2::text)) > 0
  )
  AND (
      $3::uuid IS NULL
      OR (progress.overall_progress, progress.subscription_id) < (
          $4::double precision,
          $3::uuid
      )
  )
ORDER BY progress.overall_progress DESC, progress.subscription_id DESC
LIMIT $5
`

type ListRSSSubscriptionsByProgressDescParams struct {
	ModelVersion   int32       `db:"model_version" json:"model_version"`
	Query          *string     `db:"query" json:"query"`
	CursorID       pgtype.UUID `db:"cursor_id" json:"cursor_id"`
	CursorProgress *float64    `db:"cursor_progress" json:"cursor_progress"`
	PageSize       int32       `db:"page_size" json:"page_size"`
}

type ListRSSSubscriptionsByProgressDescRow struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	SeriesID                  pgtype.UUID        `db:"series_id" json:"series_id"`
	MappingProfileID          pgtype.UUID        `db:"mapping_profile_id" json:"mapping_profile_id"`
	Name                      string             `db:"name" json:"name"`
	FeedUrl                   string             `db:"feed_url" json:"feed_url"`
	Enabled                   bool               `db:"enabled" json:"enabled"`
	PollIntervalSeconds       int32              `db:"poll_interval_seconds" json:"poll_interval_seconds"`
	LastPolledAt              pgtype.Timestamptz `db:"last_polled_at" json:"last_polled_at"`
	NextPollAt                pgtype.Timestamptz `db:"next_poll_at" json:"next_poll_at"`
	Version                   int32              `db:"version" json:"version"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SourceSeason              int32              `db:"source_season" json:"source_season"`
	DeletedAt                 pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	AutoReview                bool               `db:"auto_review" json:"auto_review"`
	CleanupSourceOnCompletion bool               `db:"cleanup_source_on_completion" json:"cleanup_source_on_completion"`
	CompletedAt               pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
	IncludeKeywords           []string           `db:"include_keywords" json:"include_keywords"`
	ExcludeKeywords           []string           `db:"exclude_keywords" json:"exclude_keywords"`
	AutoEpisodeMapping        bool               `db:"auto_episode_mapping" json:"auto_episode_mapping"`
	SeriesTitle               string             `db:"series_title" json:"series_title"`
	TmdbSeriesID              *int64             `db:"tmdb_series_id" json:"tmdb_series_id"`
	OverallProgress           float64            `db:"overall_progress" json:"overall_progress"`
	TaskCount                 int32              `db:"task_count" json:"task_count"`
	CompletedTaskCount        int32              `db:"completed_task_count" json:"completed_task_count"`
	AttentionTaskCount        int32              `db:"attention_task_count" json:"attention_task_count"`
}

func (q *Queries) ListRSSSubscriptionsByProgressDesc(ctx context.Context, arg ListRSSSubscriptionsByProgressDescParams) ([]ListRSSSubscriptionsByProgressDescRow, error) {
	rows, err := q.db.Query(ctx, listRSSSubscriptionsByProgressDesc,
		arg.ModelVersion,
		arg.Query,
		arg.CursorID,
		arg.CursorProgress,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRSSSubscriptionsByProgressDescRow{}
	for rows.Next() {
		var i ListRSSSubscriptionsByProgressDescRow
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.MappingProfileID,
			&i.Name,
			&i.FeedUrl,
			&i.Enabled,
			&i.PollIntervalSeconds,
			&i.LastPolledAt,
			&i.NextPollAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceSeason,
			&i.DeletedAt,
			&i.AutoReview,
			&i.CleanupSourceOnCompletion,
			&i.CompletedAt,
			&i.IncludeKeywords,
			&i.ExcludeKeywords,
			&i.AutoEpisodeMapping,
			&i.SeriesTitle,
			&i.TmdbSeriesID,
			&i.OverallProgress,
			&i.TaskCount,
			&i.CompletedTaskCount,
			&i.AttentionTaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCurrentTransactionRSSSubscriptionProgress = `-- name: LockCurrentTransactionRSSSubscriptionProgress :many
SELECT
    progress.subscription_id,
    progress.source_revision,
    progress.model_version,
    subscription.completed_at
FROM rss_subscription_progress AS progress
JOIN rss_subscriptions AS subscription ON subscription.id = progress.subscription_id
WHERE progress.dirty
  AND progress.dirtied_transaction_id = txid_current()
ORDER BY progress.subscription_id
FOR UPDATE OF progress
`

type LockCurrentTransactionRSSSubscriptionProgressRow struct {
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	SourceRevision int64              `db:"source_revision" json:"source_revision"`
	ModelVersion   int32              `db:"model_version" json:"model_version"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) LockCurrentTransactionRSSSubscriptionProgress(ctx context.Context) ([]LockCurrentTransactionRSSSubscriptionProgressRow, error) {
	rows, err := q.db.Query(ctx, lockCurrentTransactionRSSSubscriptionProgress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockCurrentTransactionRSSSubscriptionProgressRow{}
	for rows.Next() {
		var i LockCurrentTransactionRSSSubscriptionProgressRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.SourceRevision,
			&i.ModelVersion,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDirtyRSSSubscriptionProgress = `-- name: LockDirtyRSSSubscriptionProgress :many
SELECT
    progress.subscription_id,
    progress.source_revision,
    progress.model_version,
    subscription.completed_at
FROM rss_subscription_progress AS progress
JOIN rss_subscriptions AS subscription ON subscription.id = progress.subscription_id
WHERE progress.dirty
ORDER BY progress.dirtied_at, progress.subscription_id
LIMIT $1
FOR UPDATE OF progress SKIP LOCKED
`

type LockDirtyRSSSubscriptionProgressRow struct {
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	SourceRevision int64              `db:"source_revision" json:"source_revision"`
	ModelVersion   int32              `db:"model_version" json:"model_version"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) LockDirtyRSSSubscriptionProgress(ctx context.Context, batchSize int32) ([]LockDirtyRSSSubscriptionProgressRow, error) {
	rows, err := q.db.Query(ctx, lockDirtyRSSSubscriptionProgress, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDirtyRSSSubscriptionProgressRow{}
	for rows.Next() {
		var i LockDirtyRSSSubscriptionProgressRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.SourceRevision,
			&i.ModelVersion,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDirtyRSSSubscriptionProgressByIDs = `-- name: LockDirtyRSSSubscriptionProgressByIDs :many
SELECT
    progress.subscription_id,
    progress.source_revision,
    progress.model_version,
    subscription.completed_at
FROM rss_subscription_progress AS progress
JOIN rss_subscriptions AS subscription ON subscription.id = progress.subscription_id
WHERE progress.subscription_id = ANY($1::uuid[])
  AND progress.dirty
ORDER BY progress.subscription_id
FOR UPDATE OF progress
`

type LockDirtyRSSSubscriptionProgressByIDsRow struct {
	SubscriptionID pgtype.UUID        `db:"subscription_id" json:"subscription_id"`
	SourceRevision int64              `db:"source_revision" json:"source_revision"`
	ModelVersion   int32              `db:"model_version" json:"model_version"`
	CompletedAt    pgtype.Timestamptz `db:"completed_at" json:"completed_at"`
}

func (q *Queries) LockDirtyRSSSubscriptionProgressByIDs(ctx context.Context, subscriptionIds []pgtype.UUID) ([]LockDirtyRSSSubscriptionProgressByIDsRow, error) {
	rows, err := q.db.Query(ctx, lockDirtyRSSSubscriptionProgressByIDs, subscriptionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockDirtyRSSSubscriptionProgressByIDsRow{}
	for rows.Next() {
		var i LockDirtyRSSSubscriptionProgressByIDsRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.SourceRevision,
			&i.ModelVersion,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutdatedRSSSubscriptionProgressByIDsDirty = `-- name: MarkOutdatedRSSSubscriptionProgressByIDsDirty :execrows
UPDATE rss_subscription_progress
SET source_revision = source_revision + 1,
    dirty = true,
    dirtied_transaction_id = txid_current(),
    dirtied_at = clock_timestamp()
WHERE subscription_id = ANY($1::uuid[])
  AND model_version < $2
  AND NOT dirty
`

type MarkOutdatedRSSSubscriptionProgressByIDsDirtyParams struct {
	SubscriptionIds []pgtype.UUID `db:"subscription_ids" json:"subscription_ids"`
	ModelVersion    int32         `db:"model_version" json:"model_version"`
}

func (q *Queries) MarkOutdatedRSSSubscriptionProgressByIDsDirty(ctx context.Context, arg MarkOutdatedRSSSubscriptionProgressByIDsDirtyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutdatedRSSSubscriptionProgressByIDsDirty, arg.SubscriptionIds, arg.ModelVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutdatedRSSSubscriptionProgressDirty = `-- name: MarkOutdatedRSSSubscriptionProgressDirty :execrows
UPDATE rss_subscription_progress
SET source_revision = source_revision + 1,
    dirty = true,
    dirtied_transaction_id = txid_current(),
    dirtied_at = clock_timestamp()
WHERE model_version < $1
  AND NOT dirty
`

func (q *Queries) MarkOutdatedRSSSubscriptionProgressDirty(ctx context.Context, modelVersion int32) (int64, error) {
	result, err := q.db.Exec(ctx, markOutdatedRSSSubscriptionProgressDirty, modelVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRSSSubscriptionProgress = `-- name: UpdateRSSSubscriptionProgress :one
UPDATE rss_subscription_progress
SET overall_progress = $1,
    task_count = $2,
    completed_task_count = $3,
    attention_task_count = $4,
    calculated_revision = source_revision,
    model_version = $5,
    dirty = false,
    calculated_at = clock_timestamp()
WHERE subscription_id = $6
  AND source_revision = $7
RETURNING subscription_id, overall_progress, task_count, completed_task_count, attention_task_count, source_revision, calculated_revision, model_version, dirty, dirtied_transaction_id, dirtied_at, calculated_at
`

type UpdateRSSSubscriptionProgressParams struct {
	OverallProgress        float64     `db:"overall_progress" json:"overall_progress"`
	TaskCount              int32       `db:"task_count" json:"task_count"`
	CompletedTaskCount     int32       `db:"completed_task_count" json:"completed_task_count"`
	AttentionTaskCount     int32       `db:"attention_task_count" json:"attention_task_count"`
	ModelVersion           int32       `db:"model_version" json:"model_version"`
	SubscriptionID         pgtype.UUID `db:"subscription_id" json:"subscription_id"`
	ExpectedSourceRevision int64       `db:"expected_source_revision" json:"expected_source_revision"`
}

func (q *Queries) UpdateRSSSubscriptionProgress(ctx context.Context, arg UpdateRSSSubscriptionProgressParams) (RssSubscriptionProgress, error) {
	row := q.db.QueryRow(ctx, updateRSSSubscriptionProgress,
		arg.OverallProgress,
		arg.TaskCount,
		arg.CompletedTaskCount,
		arg.AttentionTaskCount,
		arg.ModelVersion,
		arg.SubscriptionID,
		arg.ExpectedSourceRevision,
	)
	var i RssSubscriptionProgress
	err := row.Scan(
		&i.SubscriptionID,
		&i.OverallProgress,
		&i.TaskCount,
		&i.CompletedTaskCount,
		&i.AttentionTaskCount,
		&i.SourceRevision,
		&i.CalculatedRevision,
		&i.ModelVersion,
		&i.Dirty,
		&i.DirtiedTransactionID,
		&i.DirtiedAt,
		&i.CalculatedAt,
	)
	return i, err
}
